// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/java/org/apache/lucene/analysis/classic/ClassicTokenizerImpl.jflex

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gnit.lucenekmp.analysis.classic

import okio.IOException
import okio.ArrayIndexOutOfBoundsException
import org.gnit.lucenekmp.analysis.tokenattributes.CharTermAttribute
import org.gnit.lucenekmp.jdkport.Character
import org.gnit.lucenekmp.jdkport.Reader
import org.gnit.lucenekmp.jdkport.System
import org.gnit.lucenekmp.jdkport.fromCharArray


/** This class implements the classic lucene StandardTokenizer up until 3.0 */

// See https://github.com/jflex-de/jflex/issues/222
@Suppress("fallthrough", "unused")
class ClassicTokenizerImpl(`in`: Reader) {

  companion object {

  /** This character denotes the end of file. */
      const val YYEOF = -1;

  /** Initial size of the lookahead buffer. */
      private const val ZZ_BUFFERSIZE = 4096;

  /** Lexical states. */
      const val YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l ZZ_LEXSTATE[l+1] is the state in
   * the DFA for the lexical state l at the beginning of a line l is of the form l = 2*k, k a non
   * negative integer
   */
  private val ZZ_LEXSTATE = intArrayOf(0, 0);

  /** Top-level table for translating characters to character classes */
      private val ZZ_CMAP_TOP: IntArray by lazy { zzUnpackcmap_top() }

      private val ZZ_CMAP_TOP_PACKED_0: String = ("\u0001\u0000\u0001\u0100\u0001\u0200\u0001\u0300\u0001\u0400\u0001\u0500\u0001\u0600\u0001\u0700"
              + "\u0001\u0800\u0001\u0900\u0001\u0a00\u0001\u0b00\u0001\u0c00\u0001\u0d00\u0001\u0e00\u0001\u0f00"
              + "\u0001\u1000\u0001\u1100\u0001\u1200\u0001\u1300\u0001\u1400\u0001\u0100\u0001\u1500\u0001\u1600"
              + "\u0001\u1700\u0005\u0800\u0001\u1800\u0001\u1900\u0001\u1a00\u0001\u1b00\u000e\u0800\u0001\u1c00"
              + "\u0001\u1d00\u0001\u0800\u0001\u1e00\u0019\u1f00\u0001\u2000\u0051\u1f00\u0001\u2100\u0004\u0100"
              + "\u0001\u2200\u0007\u0800\u002b\u0100\u0001\u2300\u0021\u0800\u0001\u1f00\u0001\u2400\u0001\u2500"
              + "\u0001\u0100\u0001\u2600\u0001\u2700\u0001\u2800\u1000\u0800")

      private fun zzUnpackcmap_top(): IntArray {
    val result = IntArray(4352)
    var offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackcmap_top(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var count = packed[i++].code;
      var value = packed[i++].code;
      do {
      result[j++] = value
    } while (--count > 0)
    }
    return j;
  }

  /** Second-level tables for translating characters to character classes */
      private val ZZ_CMAP_BLOCKS: IntArray by lazy { zzUnpackcmap_blocks() }

      private val ZZ_CMAP_BLOCKS_PACKED_0: String = ("\u0026\u0000\u0001\u0001\u0001\u0002\u0004\u0000\u0001\u0003\u0001\u0004\u0001\u0005\u0001\u0003"
              + "\n\u0006\u0006\u0000\u0001\u0007\u001a\u0008\u0004\u0000\u0001\t\u0001\u0000\u001a\u0008"
              + "\u002f\u0000\u0001\u0008\n\u0000\u0001\u0008\u0004\u0000\u0001\u0008\u0005\u0000\u0017\u0008"
              + "\u0001\u0000\u001f\u0008\u0001\u0000\u0128\u0008\u0002\u0000\u0012\u0008\u001c\u0000\u005e\u0008"
              + "\u0002\u0000\t\u0008\u0002\u0000\u0007\u0008\u000e\u0000\u0002\u0008\u000e\u0000\u0005\u0008"
              + "\t\u0000\u0001\u0008\u008b\u0000\u0001\u0008\u000b\u0000\u0001\u0008\u0001\u0000\u0003\u0008"
              + "\u0001\u0000\u0001\u0008\u0001\u0000\u0014\u0008\u0001\u0000\u002c\u0008\u0001\u0000\u0008\u0008"
              + "\u0002\u0000\u001a\u0008\u000C\u0000\u0082\u0008\n\u0000\u0039\u0008\u0002\u0000\u0002\u0008"
              + "\u0002\u0000\u0002\u0008\u0003\u0000\u0026\u0008\u0002\u0000\u0002\u0008\u0037\u0000\u0026\u0008"
              + "\u0002\u0000\u0001\u0008\u0007\u0000\u0027\u0008\u0048\u0000\u001b\u0008\u0005\u0000\u0003\u0008"
              + "\u002e\u0000\u001a\u0008\u0005\u0000\u000b\u0008\u0015\u0000\n\u0006\u0007\u0000\u0063\u0008"
              + "\u0001\u0000\u0001\u0008\u000f\u0000\u0002\u0008\t\u0000\n\u0006\u0003\u0008\u0013\u0000"
              + "\u0001\u0008\u0001\u0000\u001b\u0008\u0053\u0000\u0026\u0008\u015f\u0000\u0035\u0008\u0003\u0000"
              + "\u0001\u0008\u0012\u0000\u0001\u0008\u0007\u0000\n\u0008\u0004\u0000\n\u0006\u0015\u0000"
              + "\u0008\u0008\u0002\u0000\u0002\u0008\u0002\u0000\u0016\u0008\u0001\u0000\u0007\u0008\u0001\u0000"
              + "\u0001\u0008\u0003\u0000\u0004\u0008\u0022\u0000\u0002\u0008\u0001\u0000\u0003\u0008\u0004\u0000"
              + "\n\u0006\u0002\u0008\u0013\u0000\u0006\u0008\u0004\u0000\u0002\u0008\u0002\u0000\u0016\u0008"
              + "\u0001\u0000\u0007\u0008\u0001\u0000\u0002\u0008\u0001\u0000\u0002\u0008\u0001\u0000\u0002\u0008"
              + "\u001f\u0000\u0004\u0008\u0001\u0000\u0001\u0008\u0007\u0000\n\u0006\u0002\u0000\u0003\u0008"
              + "\u0010\u0000\u0007\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0003\u0008\u0001\u0000\u0016\u0008"
              + "\u0001\u0000\u0007\u0008\u0001\u0000\u0002\u0008\u0001\u0000\u0005\u0008\u0003\u0000\u0001\u0008"
              + "\u0012\u0000\u0001\u0008\u000f\u0000\u0001\u0008\u0005\u0000\n\u0006\u0015\u0000\u0008\u0008"
              + "\u0002\u0000\u0002\u0008\u0002\u0000\u0016\u0008\u0001\u0000\u0007\u0008\u0001\u0000\u0002\u0008"
              + "\u0002\u0000\u0004\u0008\u0003\u0000\u0001\u0008\u001e\u0000\u0002\u0008\u0001\u0000\u0003\u0008"
              + "\u0004\u0000\n\u0006\u0015\u0000\u0006\u0008\u0003\u0000\u0003\u0008\u0001\u0000\u0004\u0008"
              + "\u0003\u0000\u0002\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0002\u0008\u0003\u0000\u0002\u0008"
              + "\u0003\u0000\u0003\u0008\u0003\u0000\u0008\u0008\u0001\u0000\u0003\u0008\u002d\u0000\t\u0006"
              + "\u0015\u0000\u0008\u0008\u0001\u0000\u0003\u0008\u0001\u0000\u0017\u0008\u0001\u0000\n\u0008"
              + "\u0001\u0000\u0005\u0008\u0026\u0000\u0002\u0008\u0004\u0000\n\u0006\u0015\u0000\u0008\u0008"
              + "\u0001\u0000\u0003\u0008\u0001\u0000\u0017\u0008\u0001\u0000\n\u0008\u0001\u0000\u0005\u0008"
              + "\u0024\u0000\u0001\u0008\u0001\u0000\u0002\u0008\u0004\u0000\n\u0006\u0015\u0000\u0008\u0008"
              + "\u0001\u0000\u0003\u0008\u0001\u0000\u0017\u0008\u0001\u0000\u0010\u0008\u0026\u0000\u0002\u0008"
              + "\u0004\u0000\n\u0006\u0015\u0000\u0012\u0008\u0003\u0000\u0018\u0008\u0001\u0000\t\u0008"
              + "\u0001\u0000\u0001\u0008\u0002\u0000\u0007\u0008\u0039\u0000\u0001\n\u0030\u0008\u0001\n"
              + "\u0002\u0008\u000C\n\u0007\u0008\t\n\n\u0006\u0027\u0000\u0002\u0008\u0001\u0000"
              + "\u0001\u0008\u0002\u0000\u0002\u0008\u0001\u0000\u0001\u0008\u0002\u0000\u0001\u0008\u0006\u0000"
              + "\u0004\u0008\u0001\u0000\u0007\u0008\u0001\u0000\u0003\u0008\u0001\u0000\u0001\u0008\u0001\u0000"
              + "\u0001\u0008\u0002\u0000\u0002\u0008\u0001\u0000\u0004\u0008\u0001\u0000\u0002\u0008\t\u0000"
              + "\u0001\u0008\u0002\u0000\u0005\u0008\u0001\u0000\u0001\u0008\t\u0000\n\u0006\u0002\u0000"
              + "\u0002\u0008\u0022\u0000\u0001\u0008\u001f\u0000\n\u0006\u0016\u0000\u0008\u0008\u0001\u0000"
              + "\u0022\u0008\u001d\u0000\u0004\u0008\u0074\u0000\u0022\u0008\u0001\u0000\u0005\u0008\u0001\u0000"
              + "\u0002\u0008\u0015\u0000\n\u0006\u0006\u0000\u0006\u0008\u004a\u0000\u0026\u0008\n\u0000"
              + "\u0027\u0008\t\u0000\u005a\u0008\u0005\u0000\u0044\u0008\u0005\u0000\u0052\u0008\u0006\u0000"
              + "\u0007\u0008\u0001\u0000\u003f\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0004\u0008\u0002\u0000"
              + "\u0007\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0004\u0008\u0002\u0000\u0027\u0008\u0001\u0000"
              + "\u0001\u0008\u0001\u0000\u0004\u0008\u0002\u0000\u001f\u0008\u0001\u0000\u0001\u0008\u0001\u0000"
              + "\u0004\u0008\u0002\u0000\u0007\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0004\u0008\u0002\u0000"
              + "\u0007\u0008\u0001\u0000\u0007\u0008\u0001\u0000\u0017\u0008\u0001\u0000\u001f\u0008\u0001\u0000"
              + "\u0001\u0008\u0001\u0000\u0004\u0008\u0002\u0000\u0007\u0008\u0001\u0000\u0027\u0008\u0001\u0000"
              + "\u0013\u0008\u000e\u0000\t\u0006\u002e\u0000\u0055\u0008\u000C\u0000\u016c\u0008\u0002\u0000"
              + "\u0008\u0008\n\u0000\u001a\u0008\u0005\u0000\u004b\u0008\u0095\u0000\u0034\u0008\u002c\u0000"
              + "\n\u0006\u0026\u0000\n\u0006\u0006\u0000\u0058\u0008\u0008\u0000\u0029\u0008\u0057\u0000"
              + "\u009c\u0008\u0004\u0000\u005a\u0008\u0006\u0000\u0016\u0008\u0002\u0000\u0006\u0008\u0002\u0000"
              + "\u0026\u0008\u0002\u0000\u0006\u0008\u0002\u0000\u0008\u0008\u0001\u0000\u0001\u0008\u0001\u0000"
              + "\u0001\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u001f\u0008\u0002\u0000\u0035\u0008\u0001\u0000"
              + "\u0007\u0008\u0001\u0000\u0001\u0008\u0003\u0000\u0003\u0008\u0001\u0000\u0007\u0008\u0003\u0000"
              + "\u0004\u0008\u0002\u0000\u0006\u0008\u0004\u0000\r\u0008\u0005\u0000\u0003\u0008\u0001\u0000"
              + "\u0007\u0008\u0082\u0000\u0001\u0008\u0082\u0000\u0001\u0008\u0004\u0000\u0001\u0008\u0002\u0000"
              + "\n\u0008\u0001\u0000\u0001\u0008\u0003\u0000\u0005\u0008\u0006\u0000\u0001\u0008\u0001\u0000"
              + "\u0001\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0004\u0008\u0001\u0000\u0003\u0008\u0001\u0000"
              + "\u0007\u0008\u00cb\u0000\u0002\u0008\u002a\u0000\u0005\u0008\n\u0000\u00f0\u000b\u0001\u0000"
              + "\u005e\u0008\u0011\u0000\u0018\u0008\u0038\u0000\u0090\u000b\u0080\u0000\u01c0\u000b\u0040\u0000"
              + "\u0100\u000b\u008d\u0008\u0073\u0000\u00a4\u0008\u005c\u0000\u0100\u000b\u0007\u0008\u000C\u0000"
              + "\u0005\u0008\u0005\u0000\u0001\u0008\u0001\u0000\n\u0008\u0001\u0000\r\u0008\u0001\u0000"
              + "\u0005\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0002\u0008\u0001\u0000\u0002\u0008\u0001\u0000"
              + "\u006c\u0008\u0021\u0000\u006b\u0008\u0012\u0000\u0040\u0008\u0002\u0000\u0036\u0008\u0028\u0000"
              + "\u000C\u0008\u0074\u0000\u0003\u0008\u0001\u0000\u0001\u0008\u0001\u0000\u0087\u0008\u0013\u0000"
              + "\n\u0006\u0007\u0000\u001a\u0008\u0006\u0000\u001a\u0008\n\u0000\u003b\u000b\u001f\u0008"
              + "\u0003\u0000\u0006\u0008\u0002\u0000\u0006\u0008\u0002\u0000\u0006\u0008\u0002\u0000\u0003\u0008"
              + "\u0023\u0000")

      private fun zzUnpackcmap_blocks(): IntArray {
    val result = IntArray(10496)
    var offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackcmap_blocks(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var count = packed[i++].code;
      var value = packed[i++].code;
      do {
      result[j++] = value
    } while (--count > 0)
    }
    return j;
  }

  /** Translates DFA states to action switch labels. */
      private val ZZ_ACTION: IntArray by lazy { zzUnpackAction() }

      private const val ZZ_ACTION_PACKED_0 = (
      "\u0001\u0000\u0001\u0001\u0003\u0002\u0001\u0003\n\u0000\u0001\u0002\u0001\u0000\u0006\u0004"
          + "\u0003\u0005\u0001\u0000\u0001\u0006\u0001\u0007\u0002\u0004\u0002\u0000\u0003\u0005\u0001\u0006"
          + "\u0001\u0005\u0002\u0008\u0004\u0000\u0001\u0008\u0001\t\u0001\u0008\u0001\n\u0001\u0005")

      private fun zzUnpackAction(): IntArray {
    val result = IntArray(50)
    var offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackAction(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var count = packed[i++].code;
      var value = packed[i++].code;
      do {
      result[j++] = value
    } while (--count > 0)
    }
    return j;
  }

  /** Translates a state to a row index in the transition table */
      private val ZZ_ROWMAP: IntArray by lazy { zzUnpackRowMap() }

      private const val ZZ_ROWMAP_PACKED_0 = (
      "\u0000\u0000\u0000\u000C\u0000\u0018\u0000\u0024\u0000\u0030\u0000\u000C\u0000\u003C\u0000\u0048"
          + "\u0000\u0054\u0000\u0060\u0000\u006C\u0000\u0078\u0000\u0084\u0000\u0090\u0000\u009C\u0000\u00A8"
          + "\u0000\u00B4\u0000\u00C0\u0000\u00CC\u0000\u00D8\u0000\u00E4\u0000\u00F0\u0000\u00FC\u0000\u0108"
          + "\u0000\u0114\u0000\u0120\u0000\u012c\u0000\u0138\u0000\u006C\u0000\u0144\u0000\u0150\u0000\u015c"
          + "\u0000\u0168\u0000\u0174\u0000\u0180\u0000\u018c\u0000\u0198\u0000\u01a4\u0000\u01b0\u0000\u0054"
          + "\u0000\u00C0\u0000\u01bc\u0000\u01c8\u0000\u01d4\u0000\u01e0\u0000\u01ec\u0000\u01f8\u0000\u0204"
          + "\u0000\u0210\u0000\u021c")

      private fun zzUnpackRowMap(): IntArray {
    val result = IntArray(50)
    var offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackRowMap(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var high = packed[i++].code shl 16;
      result[j++] = high or packed[i++].code
    }
    return j;
  }

  /** The transition table of the DFA */
      private val ZZ_TRANS: IntArray by lazy { zzUnpackTrans() }

      private const val ZZ_TRANS_PACKED_0 = (
      "\u0006\u0002\u0001\u0003\u0001\u0002\u0001\u0004\u0001\u0002\u0001\u0005\u0001\u0006\u000F\u0000"
          + "\u0001\u0007\u0001\u0008\u0001\t\u0001\u0003\u0001\n\u0001\u0003\u0001\u0008\u0001\u0005"
          + "\u0002\u0000\u0001\u000B\u0001\u000C\u0001\r\u0001\u000E\u0001\u000F\u0001\u0003\u0001\u0010"
          + "\u0001\u0011\u0001\u000E\u0001\u0005\u0004\u0000\u0001\r\u0001\u000E\u0001\u0012\u0001\u0005"
          + "\u0001\n\u0001\u0005\u0001\u000E\u0001\u0005\u0007\u0000\u0001\u0013\u0001\u0000\u0001\u0014"
          + "\u0001\u0000\u0001\u0015\u0007\u0000\u0001\u0016\u0001\u0000\u0001\u0017\u0001\u0000\u0001\u0018"
          + "\u0007\u0000\u0001\u0019\u0001\u0000\u0001\u001A\u0001\u0000\u0001\u001B\u0007\u0000\u0001\u001C"
          + "\u0001\u0000\u0001\u001C\u0001\u0000\u0001\u001C\t\u0000\u0001\u001D\u000B\u0000\u0001\u001E"
          + "\t\u0000\u0001\u001F\u0001\u0000\u0001\r\t\u0000\u0001\u0020\u0001\u0000\u0001\u0021"
          + "\u0001\u0000\u0001\u0022\u0007\u0000\u0001\u0023\u0001\u0000\u0001\u0024\u0001\u0000\u0001\u0025"
          + "\u0007\u0000\u0001\u001C\u0001\u0000\u0001\u0026\u0001\u0000\u0001\u001C\u0002\u0000\u0001\u000B"
          + "\u0001\u000C\u0001\r\u0001\u000E\u0001\u0012\u0001\u0003\u0001\u0010\u0001\u0011\u0001\u000E"
          + "\u0001\u0005\u0007\u0000\u0001\u0023\u0001\u0000\u0001\u0027\u0001\u0000\u0001\u0025\u0004\u0000"
          + "\u0003\u0007\u0001\u0013\u0001\u0000\u0001\u0013\u0001\u0007\u0001\u0015\u0004\u0000\u0003\r"
          + "\u0001\u0013\u0001\u0000\u0001\u0014\u0001\r\u0001\u0015\u0004\u0000\u0003\r\u0001\u0015"
          + "\u0001\u0000\u0001\u0015\u0001\r\u0001\u0015\u0004\u0000\u0001\u0007\u0002\u0008\u0001\u0016"
          + "\u0001\n\u0001\u0016\u0001\u0008\u0001\u0018\u0004\u0000\u0001\r\u0002\u000E\u0001\u0016"
          + "\u0001\n\u0001\u0017\u0001\u000E\u0001\u0018\u0004\u0000\u0001\r\u0002\u000E\u0001\u0018"
          + "\u0001\n\u0001\u0018\u0001\u000E\u0001\u0018\u0004\u0000\u0001\u0007\u0001\u0008\u0001\u0028"
          + "\u0001\u0019\u0001\n\u0001\u0019\u0001\u0008\u0001\u001B\u0004\u0000\u0001\r\u0001\u000E"
          + "\u0001\u0029\u0001\u0019\u0001\n\u0001\u001A\u0001\u000E\u0001\u001B\u0004\u0000\u0001\r"
          + "\u0001\u000E\u0001\u0029\u0001\u001B\u0001\n\u0001\u001B\u0001\u000E\u0001\u001B\u0005\u0000"
          + "\u0002\u002A\u0001\u001C\u0001\u0000\u0001\u001C\u0001\u0000\u0001\u001C\u0003\u0000\u0001\u000C"
          + "\u0005\u0000\u0001\u001E\u0006\u0000\u0003\u002B\u0001\u001F\u0001\u0000\u0001\u001F\u0001\u002B"
          + "\u0005\u0000\u0001\u002B\u0002\u002C\u0001\u0020\u0001\n\u0001\u0020\u0001\u002C\u0001\u0022"
          + "\u0005\u0000\u0002\u002D\u0001\u0020\u0001\n\u0001\u0021\u0001\u002D\u0001\u0022\u0005\u0000"
          + "\u0002\u002D\u0001\u0022\u0001\n\u0001\u0022\u0001\u002D\u0001\u0022\u0004\u0000\u0001\u002B"
          + "\u0001\u002C\u0001\u002E\u0001\u0023\u0001\n\u0001\u0023\u0001\u002C\u0001\u0025\u0005\u0000"
          + "\u0001\u002D\u0001\u002F\u0001\u0023\u0001\n\u0001\u0027\u0001\u002D\u0001\u0025\u0005\u0000"
          + "\u0001\u002D\u0001\u0030\u0001\u0025\u0001\n\u0001\u0025\u0001\u002D\u0001\u0025\u0005\u0000"
          + "\u0002\u002A\u0001\u001C\u0001\u0000\u0001\u0026\u0001\u0000\u0001\u001C\u0005\u0000\u0001\u002D"
          + "\u0001\u0030\u0001\u0023\u0001\n\u0001\u0027\u0001\u002D\u0001\u0025\u0007\u0000\u0001\u0031"
          + "\u0001\u0000\u0001\u0031\u0001\u0000\u0001\u0031\u0007\u0000\u0001\u0015\u0001\u0000\u0001\u0015"
          + "\u0001\u0000\u0001\u0015\u0007\u0000\u0001\u0018\u0001\u0000\u0001\u0018\u0001\u0000\u0001\u0018"
          + "\u0007\u0000\u0001\u0022\u0001\u0000\u0001\u0022\u0001\u0000\u0001\u0022\u0007\u0000\u0001\u001B"
          + "\u0001\u0000\u0001\u001B\u0001\u0000\u0001\u001B\u0007\u0000\u0001\u0025\u0001\u0000\u0001\u0032"
          + "\u0001\u0000\u0001\u0025\u0007\u0000\u0001\u0025\u0001\u0000\u0001\u0025\u0001\u0000\u0001\u0025"
          + "\u0005\u0000\u0002\u002A\u0001\u0031\u0001\u0000\u0001\u0031\u0001\u0000\u0001\u0031\u0005\u0000"
          + "\u0001\u002D\u0001\u002F\u0001\u0025\u0001\n\u0001\u0025\u0001\u002D\u0001\u0025\u0001\u0000")

      private fun zzUnpackTrans(): IntArray {
    val result = IntArray(552)
    var offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackTrans(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var count = packed[i++].code;
      var value = packed[i++].code;
      value--;
      do {
      result[j++] = value
    } while (--count > 0)
    }
    return j;
  }

  /** Error code for "Unknown internal scanner error". */
      private const val ZZ_UNKNOWN_ERROR = 0;

  /** Error code for "could not match input". */
      private const val ZZ_NO_MATCH = 1;

  /** Error code for "pushback value was too large". */
      private const val ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and {@link
   * #ZZ_PUSHBACK_2BIG} respectively.
   */
      private val ZZ_ERROR_MSG = arrayOf(
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  )

  /** ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState} */
      private val ZZ_ATTRIBUTE: IntArray by lazy { zzUnpackAttribute() }

      private const val ZZ_ATTRIBUTE_PACKED_0 = (
      "\u0001\u0000\u0001\t\u0003\u0001\u0001\t\n\u0000\u0001\u0001\u0001\u0000\t\u0001" + "\u0001\u0000\u0004\u0001\u0002\u0000\u0007\u0001\u0004\u0000\u0005\u0001")

      private fun zzUnpackAttribute(): IntArray {
    val result = IntArray(50)
    var offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

      private fun zzUnpackAttribute(packed: String, offset: Int, result: IntArray): Int {
    var i = 0; /* index in packed string  */
    var j = offset; /* index in unpacked array */
    var l = packed.length;
    while (i < l) {
      var count = packed[i++].code;
      var value = packed[i++].code;
      do {
      result[j++] = value
    } while (--count > 0)
    }
    return j;
  }

  }

  /** Input device. */
      private var zzReader: Reader = `in`;

  /** Current state of the DFA. */
      private var zzState = 0;

  /** Current lexical state. */
      private var zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
      private var zzBuffer: CharArray = CharArray(ZZ_BUFFERSIZE);

  /** Text position at the last accepting state. */
      private var zzMarkedPos = 0;

  /** Current text position in the buffer. */
      private var zzCurrentPos = 0;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
      private var zzStartRead = 0;

  /** Marks the last character in the buffer, that has been read from input. */
      private var zzEndRead = 0;

  /**
   * Whether the scanner is at the end of file.
   *
   * @see #yyatEOF
   */
      private var zzAtEOF = false;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final {@link
   * #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
      private var zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @Suppress("unused")
      private var yyline = 0;

  /** Number of characters from the last newline up to the start of the matched text. */
  @Suppress("unused")
      private var yycolumn = 0;

  /** Number of characters up to the start of the matched text. */
      private var yychar: Long = 0L;

  /** Whether the scanner is currently at the beginning of a line. */
  @Suppress("unused")
      private var zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @Suppress("unused")
      private var zzEOFDone = false;

  /* user code: */

      val ALPHANUM = ClassicTokenizer.ALPHANUM;
      val APOSTROPHE = ClassicTokenizer.APOSTROPHE;
      val ACRONYM = ClassicTokenizer.ACRONYM;
      val COMPANY = ClassicTokenizer.COMPANY;
      val EMAIL = ClassicTokenizer.EMAIL;
      val HOST = ClassicTokenizer.HOST;
      val NUM = ClassicTokenizer.NUM;
      val CJ = ClassicTokenizer.CJ;
      val ACRONYM_DEP = ClassicTokenizer.ACRONYM_DEP;

      val TOKEN_TYPES = ClassicTokenizer.TOKEN_TYPES;

      fun yychar(): Int {
    // jflex supports > 2GB docs but not lucene
    return yychar.toInt();
  }

  /** Fills CharTermAttribute with the current token text. */
      fun getText(t: CharTermAttribute) {
    t.copyBuffer(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
  }

      fun setBufferSize(numChars: Int) {
    throw UnsupportedOperationException()
  }

  /**
   * Creates a new scanner
   *
   * @param in the java.io.Reader to read input from.
   */
  init {
    this.zzReader = `in`
  }

  /** Translates raw input code points to DFA table row */
      private fun zzCMap(input: Int): Int {
    val offset = input and 255
    return if (offset == input) ZZ_CMAP_BLOCKS[offset] else ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input shr 8] or offset]
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException if any I/O-Error occurs
   */
  @Throws(IOException::class)
  private fun zzRefill(): Boolean {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead, zzBuffer, 0, zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.size - zzFinalHighSurrogate) {
      /* if not: blow it up */
      val newBuffer = CharArray(zzBuffer.size * 2);
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.size);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    val requested = zzBuffer.size - zzEndRead;
    val numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else { // There is room in the buffer for at least one more char
          val c = zzReader.read(); // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = c.toChar();
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  @Throws(IOException::class)
  fun yyclose() {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    zzReader.close()
  }

  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  fun yyreset(reader: Reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.size > ZZ_BUFFERSIZE) {
      zzBuffer = CharArray(ZZ_BUFFERSIZE);
    }
  }

  /** Resets the input position. */
  private fun yyResetPosition() {
    zzAtBOL = true;
    zzAtEOF = false;
    zzCurrentPos = 0;
    zzMarkedPos = 0;
    zzStartRead = 0;
    zzEndRead = 0;
    zzFinalHighSurrogate = 0;
    yyline = 0;
    yycolumn = 0;
    yychar = 0L;
  }

  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  fun yyatEOF(): Boolean {
    return zzAtEOF;
  }

  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  fun yystate(): Int {
    return zzLexicalState;
  }

  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  fun yybegin(newState: Int) {
    zzLexicalState = newState;
  }

  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  fun yytext(): String {
    return String.fromCharArray(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
  }

  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   * @return the character at {@code position}.
   */
  fun yycharat(position: Int): Char {
    return zzBuffer[zzStartRead + position];
  }

  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  fun yylength(): Int {
    return zzMarkedPos - zzStartRead;
  }

  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that "Can't Possibly
   * Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private fun zzScanError(errorCode: Int) {
    var message: String
    try {
      message = ZZ_ERROR_MSG[errorCode]
    } catch (e: ArrayIndexOutOfBoundsException) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR]
    }

    throw Error(message)
  }

  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  fun yypushback(number: Int) {
    if (number > yylength()) zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }

  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Throws(IOException::class)
  fun getNextToken(): Int {
    var zzInput: Int
    var zzAction: Int

    // cached fields:
    var zzCurrentPosL: Int
    var zzMarkedPosL: Int
    var zzEndReadL = zzEndRead
    var zzBufferL = zzBuffer

    val zzTransL = ZZ_TRANS
    val zzRowMapL = ZZ_ROWMAP
    val zzAttrL = ZZ_ATTRIBUTE

    while (true) {
      zzMarkedPosL = zzMarkedPos

      yychar += (zzMarkedPosL - zzStartRead).toLong()

      zzAction = -1

      zzMarkedPos = zzMarkedPosL
      zzStartRead = zzMarkedPosL
      zzCurrentPos = zzMarkedPosL
      zzCurrentPosL = zzMarkedPosL

      zzState = ZZ_LEXSTATE[zzLexicalState]

      // set up zzAction for empty match case:
      var zzAttributes = zzAttrL[zzState]
      if ((zzAttributes and 1) == 1) {
        zzAction = zzState
      }

      zzForAction@ while (true) {
        if (zzCurrentPosL < zzEndReadL) {
          zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
          zzCurrentPosL += Character.charCount(zzInput)
        } else if (zzAtEOF) {
          zzInput = YYEOF
          break@zzForAction
        } else {
          // store back cached positions
          zzCurrentPos = zzCurrentPosL
          zzMarkedPos = zzMarkedPosL
          val eof = zzRefill()
          // get translated positions and possibly new buffer
          zzCurrentPosL = zzCurrentPos
          zzMarkedPosL = zzMarkedPos
          zzBufferL = zzBuffer
          zzEndReadL = zzEndRead
          if (eof) {
            zzInput = YYEOF
            break@zzForAction
          } else {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
            zzCurrentPosL += Character.charCount(zzInput)
          }
        }
        val zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)]
        if (zzNext == -1) break@zzForAction
        zzState = zzNext

        zzAttributes = zzAttrL[zzState]
        if ((zzAttributes and 1) == 1) {
          zzAction = zzState
          zzMarkedPosL = zzCurrentPosL
          if ((zzAttributes and 8) == 8) break@zzForAction
        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true
        return YYEOF
      } else {
        when (if (zzAction < 0) zzAction else ZZ_ACTION[zzAction]) {
          1, 11 -> {
          }
          2 -> {
            return ALPHANUM
          }
          12 -> {
          }
          3 -> {
            return CJ
          }
          13 -> {
          }
          4 -> {
            return NUM
          }
          14 -> {
          }
          5 -> {
            return HOST
          }
          15 -> {
          }
          6 -> {
            return COMPANY
          }
          16 -> {
          }
          7 -> {
            return APOSTROPHE
          }
          17 -> {
          }
          8 -> {
            return ACRONYM_DEP
          }
          18 -> {
          }
          9 -> {
            return ACRONYM
          }
          19 -> {
          }
          10 -> {
            return EMAIL
          }
          20 -> {
          }
          else -> {
            zzScanError(ZZ_NO_MATCH)
          }
        }
      }
    }
  }
}
