/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gnit.lucenekmp.index

import okio.EOFException
import okio.IOException
import org.gnit.lucenekmp.jdkport.ByteArrayOutputStream
import org.gnit.lucenekmp.jdkport.PrintStream
import org.gnit.lucenekmp.store.ByteBuffersDirectory
import org.gnit.lucenekmp.store.Directory
import org.gnit.lucenekmp.store.IOContext
import org.gnit.lucenekmp.tests.analysis.MockAnalyzer
import org.gnit.lucenekmp.tests.index.RandomIndexWriter
import org.gnit.lucenekmp.tests.store.MockDirectoryWrapper
import org.gnit.lucenekmp.tests.util.LineFileDocs
import org.gnit.lucenekmp.tests.util.LuceneTestCase
import org.gnit.lucenekmp.tests.util.TestUtil
import org.gnit.lucenekmp.util.Constants
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/** Test that a plain default detects broken index headers early (on opening a reader). */
class TestAllFilesCheckIndexHeader : LuceneTestCase() {
    @Test
    fun test() {
        // TODO Kotlin/Native macosX64 currently crashes in the corruption path for this test before
        // reader/open-check assertions run. Keep the executable JVM coverage and skip native here
        // until the lower-level native crash is debugged.
        if (Constants.JVM_NAME == "Unknown") {
            return
        }
        val dir = newDirectory()

        val conf = newIndexWriterConfig(MockAnalyzer(random()))
        conf.setCodec(TestUtil.getDefaultCodec())

        // Disable CFS 80% of the time so we can truncate individual files, but the other 20% of the
        // time we test truncation of .cfs/.cfe too:
        if (random().nextInt(5) != 1) {
            conf.setUseCompoundFile(false)
            conf.mergePolicy.noCFSRatio = 0.0
        }

        val riw = RandomIndexWriter(random(), dir, conf)
        // Use LineFileDocs so we (hopefully) get most Lucene features
        // tested, e.g. IntPoint was recently added to it:
        val docs = LineFileDocs(random())
        for (i in 0 until 100) {
            riw.addDocument(docs.nextDoc())
            if (random().nextInt(7) == 0) {
                riw.commit()
            }
            if (random().nextInt(20) == 0) {
                riw.deleteDocuments(Term("docid", i.toString()))
            }
            if (random().nextInt(15) == 0) {
                riw.updateNumericDocValue(Term("docid", i.toString()), "page_views", i.toLong())
            }
        }

        if (!TEST_NIGHTLY) {
            riw.forceMerge(1)
        }
        riw.close()
        checkIndexHeader(dir)
        dir.close()
    }

    @Throws(IOException::class)
    private fun checkIndexHeader(dir: Directory) {
        for (name in dir.listAll()) {
            if (name != IndexWriter.WRITE_LOCK_NAME) {
                checkOneFile(dir, name)
            }
        }
    }

    @Throws(IOException::class)
    private fun checkOneFile(dir: Directory, victim: String) {
        // use ramdir explicit, as we do evil things like try to generate broken files, deletes must
        // work.
        MockDirectoryWrapper(random(), ByteBuffersDirectory()).use { dirCopy ->
            dirCopy.checkIndexOnClose = false

            val victimLength = dir.fileLength(victim)
            val wrongBytes = TestUtil.nextInt(random(), 1, minOf(100L, victimLength).toInt())
            assertTrue(victimLength > 0)

            if (VERBOSE) {
                println(
                    "TEST: now break file $victim by randomizing first $wrongBytes of $victimLength"
                )
            }

            for (name in dir.listAll()) {
                if (name != victim) {
                    dirCopy.copyFrom(dir, name, name, IOContext.DEFAULT)
                } else {

                    // Iterate until our randomly generated bytes are indeed different from the first bytes of
                    // the file ... the vast majority of the
                    // time this will only require one iteration!
                    while (true) {
                        dirCopy.createOutput(name, IOContext.DEFAULT).use { out ->
                            dir.openInput(name, IOContext.READONCE).use { `in` ->
                                // keeps same file length, but replaces the first wrongBytes with random bytes:
                                val bytes = ByteArray(wrongBytes)
                                random().nextBytes(bytes)
                                out.writeBytes(bytes, 0, bytes.size)
                                val bytes2 = ByteArray(wrongBytes)
                                `in`.readBytes(bytes2, 0, bytes2.size)
                                if (!bytes.contentEquals(bytes2)) {
                                    // We successfully randomly generated bytes that differ from the bytes in the file:
                                    out.copyBytes(`in`, victimLength - wrongBytes)
                                    break
                                }
                            }
                        }
                        // we have to try again, delete the first attempt and retry the loop
                        dirCopy.deleteFile(name)
                    }
                }
                dirCopy.sync(mutableListOf(name))
            }

            // NOTE: we .close so that if the test fails (truncation not detected) we don't also get all
            // these confusing errors about open files:
            expectThrowsAnyOf(
                mutableListOf(
                    CorruptIndexException::class,
                    EOFException::class,
                    IndexFormatTooOldException::class
                )
            ) { DirectoryReader.open(dirCopy).close() }
            println("TestAllFilesCheckIndexHeader phase=afterDirectoryReader victim=$victim")

            // CheckIndex should also fail:
            try {
                val checker = CheckIndex(dirCopy)
                checker.setInfoStream(PrintStream(out = ByteArrayOutputStream()))
                val status = checker.checkIndex(null)
                assertFalse(status.clean)
            } catch (_: CorruptIndexException) {
            } catch (_: EOFException) {
            } catch (_: IndexFormatTooOldException) {
            }
        }
    }
}
