/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gnit.lucenekmp.queryparser.flexible.standard.processors

import org.gnit.lucenekmp.queryparser.flexible.core.config.QueryConfigHandler
import org.gnit.lucenekmp.queryparser.flexible.core.processors.NoChildOptimizationQueryNodeProcessor
import org.gnit.lucenekmp.queryparser.flexible.core.processors.QueryNodeProcessorPipeline
import org.gnit.lucenekmp.queryparser.flexible.core.processors.RemoveDeletedQueryNodesProcessor
import org.gnit.lucenekmp.queryparser.flexible.standard.builders.StandardQueryTreeBuilder
import org.gnit.lucenekmp.queryparser.flexible.standard.config.StandardQueryConfigHandler
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParser
import org.gnit.lucenekmp.search.Query

/**
 * This pipeline has all the processors needed to process a query node tree, generated by
 * [StandardSyntaxParser], already assembled. <br>
 * <br>
 * The order they are assembled affects the results. <br>
 * <br>
 * This processor pipeline was designed to work with [StandardQueryConfigHandler]. <br>
 * <br>
 * The result query node tree can be used to build a [Query] object using
 * [StandardQueryTreeBuilder].
 *
 * @see StandardQueryTreeBuilder
 * @see StandardQueryConfigHandler
 * @see StandardSyntaxParser
 */
open class StandardQueryNodeProcessorPipeline(queryConfig: QueryConfigHandler?) :
    QueryNodeProcessorPipeline() {

    init {
        this.queryConfigHandler = queryConfig
        add(WildcardQueryNodeProcessor())
        add(MultiFieldQueryNodeProcessor())
        add(FuzzyQueryNodeProcessor())
        add(RegexpQueryNodeProcessor())
        add(MatchAllDocsQueryNodeProcessor())
        add(OpenRangeQueryNodeProcessor())
        add(PointQueryNodeProcessor())
        add(PointRangeQueryNodeProcessor())
        add(TermRangeQueryNodeProcessor())
        add(AllowLeadingWildcardProcessor())
        add(AnalyzerQueryNodeProcessor())
        add(PhraseSlopQueryNodeProcessor())
        // add(new GroupQueryNodeProcessor());
        add(BooleanQuery2ModifierNodeProcessor())
        add(NoChildOptimizationQueryNodeProcessor())
        add(RemoveDeletedQueryNodesProcessor())
        add(RemoveEmptyNonLeafQueryNodeProcessor())
        add(BooleanSingleChildOptimizationQueryNodeProcessor())
        add(DefaultPhraseSlopQueryNodeProcessor())
        add(BoostQueryNodeProcessor())
        add(MultiTermRewriteMethodProcessor())
        add(IntervalQueryNodeProcessor())
    }
}
