/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gnit.lucenekmp.queryparser.flexible.spans

import org.gnit.lucenekmp.queries.spans.SpanOrQuery
import org.gnit.lucenekmp.queries.spans.SpanQuery
import org.gnit.lucenekmp.queries.spans.SpanTermQuery
import org.gnit.lucenekmp.queryparser.flexible.core.QueryNodeException
import org.gnit.lucenekmp.queryparser.flexible.core.nodes.OrQueryNode
import org.gnit.lucenekmp.queryparser.flexible.core.nodes.QueryNode
import org.gnit.lucenekmp.queryparser.flexible.core.parser.SyntaxParser
import org.gnit.lucenekmp.queryparser.flexible.core.processors.QueryNodeProcessorPipeline
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParser
import org.gnit.lucenekmp.queryparser.flexible.standard.processors.WildcardQueryNodeProcessor
import org.gnit.lucenekmp.search.Query
import org.gnit.lucenekmp.tests.util.LuceneTestCase
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * This test case demonstrates how the new query parser can be used.<br></br>
 * <br></br>
 * It tests queries likes "term", "field:term" "term1 term2" "term1 OR term2", which are all already
 * supported by the current syntax parser ( [StandardSyntaxParser]).<br></br>
 * <br></br>
 * The goals is to create a new query parser that supports only the pair "field:term" or a list of
 * pairs separated or not by an OR operator, and from this query generate [SpanQuery] objects
 * instead of the regular [Query] objects. Basically, every pair will be converted to a
 * [SpanTermQuery] object and if there are more than one pair they will be grouped by an
 * [OrQueryNode].<br></br>
 * <br></br>
 * Another functionality that will be added is the ability to convert every field defined in the
 * query to an unique specific field.<br></br>
 * <br></br>
 * The query generation is divided in three different steps: parsing (syntax), processing (semantic)
 * and building.<br></br>
 * <br></br>
 * The parsing phase, as already mentioned will be performed by the current query parser:
 * [StandardSyntaxParser].<br></br>
 * <br></br>
 * The processing phase will be performed by a processor pipeline which is compound by 2 processors:
 * [SpansValidatorQueryNodeProcessor] and [UniqueFieldQueryNodeProcessor].
 *
 * <pre>
 *
 *   [SpansValidatorQueryNodeProcessor]: as it's going to use the current
 *   query parser to parse the syntax, it will support more features than we want,
 *   this processor basically validates the query node tree generated by the parser
 *   and just let got through the elements we want, all the other elements as
 *   wildcards, range queries, etc...if found, an exception is thrown.
 *
 *   [UniqueFieldQueryNodeProcessor]: this processor will take care of reading
 *   what is the &quot;unique field&quot; from the configuration and convert every field defined
 *   in every pair to this &quot;unique field&quot;. For that, a [SpansQueryConfigHandler] is
 *   used, which has the [UniqueFieldAttribute] defined in it.
 * </pre>
 *
 * The building phase is performed by the [SpansQueryTreeBuilder], which basically contains a
 * map that defines which builder will be used to generate [SpanQuery] objects from [QueryNode]
 * objects.<br></br>
 * <br></br>
 *
 * @see SpansQueryConfigHandler
 * @see SpansQueryTreeBuilder
 * @see SpansValidatorQueryNodeProcessor
 * @see SpanOrQueryNodeBuilder
 * @see SpanTermQueryNodeBuilder
 * @see StandardSyntaxParser
 * @see UniqueFieldQueryNodeProcessor
 * @see UniqueFieldAttribute
 */
class TestSpanQueryParser : LuceneTestCase() {

    private lateinit var spanProcessorPipeline: QueryNodeProcessorPipeline

    private lateinit var spanQueryConfigHandler: SpansQueryConfigHandler

    private lateinit var spansQueryTreeBuilder: SpansQueryTreeBuilder

    private val queryParser: SyntaxParser = StandardSyntaxParser()

    // empty constructor

    @BeforeTest
    fun setUp() {
        this.spanProcessorPipeline = QueryNodeProcessorPipeline()
        this.spanQueryConfigHandler = SpansQueryConfigHandler()
        this.spansQueryTreeBuilder = SpansQueryTreeBuilder()

        // set up the processor pipeline
        this.spanProcessorPipeline.queryConfigHandler = this.spanQueryConfigHandler

        this.spanProcessorPipeline.add(WildcardQueryNodeProcessor())
        this.spanProcessorPipeline.add(SpansValidatorQueryNodeProcessor())
        this.spanProcessorPipeline.add(UniqueFieldQueryNodeProcessor())
    }

    fun getSpanQuery(query: CharSequence): SpanQuery {
        return getSpanQuery("", query)
    }

    fun getSpanQuery(uniqueField: String, query: CharSequence): SpanQuery {

        this.spanQueryConfigHandler.set(SpansQueryConfigHandler.UNIQUE_FIELD, uniqueField)

        var queryTree = this.queryParser.parse(query, "defaultField")
        queryTree = this.spanProcessorPipeline.process(queryTree)

        return this.spansQueryTreeBuilder.build(queryTree)
    }

    @Test
    fun testTermSpans() {
        assertEquals(getSpanQuery("field:term").toString(), "term")
        assertEquals(getSpanQuery("term").toString(), "term")

        assertTrue(getSpanQuery("field:term") is SpanTermQuery)
        assertTrue(getSpanQuery("term") is SpanTermQuery)
    }

    @Test
    fun testUniqueField() {
        assertEquals(getSpanQuery("field", "term").toString(), "field:term")
        assertEquals(getSpanQuery("field", "field:term").toString(), "field:term")
        assertEquals(getSpanQuery("field", "anotherField:term").toString(), "field:term")
    }

    @Test
    fun testOrSpans() {
        assertEquals(getSpanQuery("term1 term2").toString(), "spanOr([term1, term2])")
        assertEquals(getSpanQuery("term1 OR term2").toString(), "spanOr([term1, term2])")

        assertTrue(getSpanQuery("term1 term2") is SpanOrQuery)
        assertTrue(getSpanQuery("term1 term2") is SpanOrQuery)
    }

    @Test
    fun testQueryValidator() {

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("term*") // wildcard queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("[a TO z]") // range queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("a~0.5") // boost queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("a^0.5") // fuzzy queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("\"a b\"") // quoted queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("(a b)") // parenthesized queries should not be supported
        }

        expectThrows<QueryNodeException>(QueryNodeException::class) {
            getSpanQuery("a AND b") // AND queries should not be supported
        }
    }
}
