import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.plugins.ExtensionAware
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GenerateGB2312MappingKotlinTask : DefaultTask() {
    @get:InputFile
    abstract val mapFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generateKotlin() {
        val map = mapFile.get().asFile
        if (!map.isFile) {
            throw GradleException("GB2312 mapping file not found at ${map.absolutePath}")
        }

        val minByte = 0xA1
        val maxByte = 0xFE
        val rowLen = 94
        val tableSize = rowLen * rowLen

        val b2c = CharArray(tableSize) { '\uFFFD' }
        val c2b = IntArray(0x10000) { -1 }

        map.forEachLine { raw ->
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) return@forEachLine
            val parts = line.split(Regex("\\s+")).filter { it.isNotEmpty() }
            if (parts.size < 2) return@forEachLine
            val byteValue = parts[0].removePrefix("0x").toInt(16)
            val unicode = parts[1].removePrefix("0x").toInt(16)
            if (byteValue <= 0xFF) {
                if (unicode in 0..0xFFFF && c2b[unicode] == -1) {
                    c2b[unicode] = byteValue
                }
            } else {
                val b1 = (byteValue shr 8) and 0xFF
                val b2 = byteValue and 0xFF
                if (b1 in minByte..maxByte && b2 in minByte..maxByte) {
                    val index = (b1 - minByte) * rowLen + (b2 - minByte)
                    if (unicode in 0..0xFFFF) {
                        b2c[index] = unicode.toChar()
                        if (c2b[unicode] == -1) {
                            c2b[unicode] = byteValue
                        }
                    }
                }
            }
        }

        val packageName = "org.gnit.lucenekmp.jdkport"
        val outputRoot = outputDir.get()
            .dir(packageName.replace('.', '/'))
            .asFile
        outputRoot.mkdirs()

        fun renderChar(c: Char): String {
            val hex = c.code.toString(16).uppercase().padStart(4, '0')
            return "'\\u$hex'"
        }

        fun writeCharParts(baseName: String, data: CharArray, maxFileSize: Int = 2_500_000): List<String> {
            val chunkSize = 4096
            val totalChunks = (data.size + chunkSize - 1) / chunkSize
            val partNames = mutableListOf<String>()
            var partIndex = 0
            var chunkIndex = 0

            while (chunkIndex < totalChunks) {
                val sb = StringBuilder()
                sb.append("// Auto-generated by generateGB2312MappingKotlin. Do not edit.\n")
                sb.append("package ").append(packageName).append("\n\n")
                val partName = baseName + "Part" + partIndex
                partNames.add(partName)
                val chunkNames = mutableListOf<String>()

                while (chunkIndex < totalChunks) {
                    val start = chunkIndex * chunkSize
                    val endExclusive = minOf(data.size, start + chunkSize)
                    val chunkBuilder = StringBuilder()
                    chunkBuilder.append("private fun ").append(baseName).append("Chunk").append(chunkIndex)
                        .append("(): CharArray = charArrayOf(\n")
                    val perLine = 16
                    for (i in start until endExclusive) {
                        val local = i - start
                        if (local % perLine == 0) chunkBuilder.append("    ")
                        chunkBuilder.append(renderChar(data[i]))
                        if (i != endExclusive - 1) chunkBuilder.append(", ")
                        if (local % perLine == perLine - 1 || i == endExclusive - 1) chunkBuilder.append("\n")
                    }
                    chunkBuilder.append(")\n\n")
                    if (sb.length + chunkBuilder.length > maxFileSize && chunkNames.isNotEmpty()) {
                        break
                    }
                    sb.append(chunkBuilder)
                    chunkNames.add(baseName + "Chunk" + chunkIndex)
                    chunkIndex++
                }

                sb.append("private fun build").append(partName.replaceFirstChar { it.uppercase() })
                    .append("(): CharArray {\n")
                sb.append("    val parts = arrayOf(\n")
                for (name in chunkNames) {
                    sb.append("        ").append(name).append("(),\n")
                }
                sb.append("    )\n")
                sb.append("    var total = 0\n")
                sb.append("    for (p in parts) total += p.size\n")
                sb.append("    val out = CharArray(total)\n")
                sb.append("    var pos = 0\n")
                sb.append("    for (p in parts) {\n")
                sb.append("        p.copyInto(out, pos)\n")
                sb.append("        pos += p.size\n")
                sb.append("    }\n")
                sb.append("    return out\n")
                sb.append("}\n")
                sb.append("internal val ").append(partName)
                    .append(": CharArray by lazy { build")
                    .append(partName.replaceFirstChar { it.uppercase() }).append("() }\n")

                val partFile = outputRoot.resolve("GB2312Mapping_${baseName}_${partIndex}.kt")
                partFile.writeText(sb.toString())
                partIndex++
            }
            return partNames
        }

        fun writeIntParts(baseName: String, data: IntArray, maxFileSize: Int = 2_500_000): List<String> {
            val chunkSize = 4096
            val totalChunks = (data.size + chunkSize - 1) / chunkSize
            val partNames = mutableListOf<String>()
            var partIndex = 0
            var chunkIndex = 0

            while (chunkIndex < totalChunks) {
                val sb = StringBuilder()
                sb.append("// Auto-generated by generateGB2312MappingKotlin. Do not edit.\n")
                sb.append("package ").append(packageName).append("\n\n")
                val partName = baseName + "Part" + partIndex
                partNames.add(partName)
                val chunkNames = mutableListOf<String>()

                while (chunkIndex < totalChunks) {
                    val start = chunkIndex * chunkSize
                    val endExclusive = minOf(data.size, start + chunkSize)
                    val chunkBuilder = StringBuilder()
                    chunkBuilder.append("private fun ").append(baseName).append("Chunk").append(chunkIndex)
                        .append("(): IntArray = intArrayOf(\n")
                    val perLine = 16
                    for (i in start until endExclusive) {
                        val local = i - start
                        if (local % perLine == 0) chunkBuilder.append("    ")
                        chunkBuilder.append(data[i])
                        if (i != endExclusive - 1) chunkBuilder.append(", ")
                        if (local % perLine == perLine - 1 || i == endExclusive - 1) chunkBuilder.append("\n")
                    }
                    chunkBuilder.append(")\n\n")
                    if (sb.length + chunkBuilder.length > maxFileSize && chunkNames.isNotEmpty()) {
                        break
                    }
                    sb.append(chunkBuilder)
                    chunkNames.add(baseName + "Chunk" + chunkIndex)
                    chunkIndex++
                }

                sb.append("private fun build").append(partName.replaceFirstChar { it.uppercase() })
                    .append("(): IntArray {\n")
                sb.append("    val parts = arrayOf(\n")
                for (name in chunkNames) {
                    sb.append("        ").append(name).append("(),\n")
                }
                sb.append("    )\n")
                sb.append("    var total = 0\n")
                sb.append("    for (p in parts) total += p.size\n")
                sb.append("    val out = IntArray(total)\n")
                sb.append("    var pos = 0\n")
                sb.append("    for (p in parts) {\n")
                sb.append("        p.copyInto(out, pos)\n")
                sb.append("        pos += p.size\n")
                sb.append("    }\n")
                sb.append("    return out\n")
                sb.append("}\n")
                sb.append("internal val ").append(partName)
                    .append(": IntArray by lazy { build")
                    .append(partName.replaceFirstChar { it.uppercase() }).append("() }\n")

                val partFile = outputRoot.resolve("GB2312Mapping_${baseName}_${partIndex}.kt")
                partFile.writeText(sb.toString())
                partIndex++
            }
            return partNames
        }

        val b2cParts = writeCharParts("gb2312B2c", b2c)
        val c2bParts = writeIntParts("gb2312C2b", c2b)

        val main = buildString {
            append("// Auto-generated by generateGB2312MappingKotlin. Do not edit.\n")
            append("package ").append(packageName).append("\n\n")
            fun renderAggregate(name: String, parts: List<String>, type: String) {
                val builderName = name.replaceFirstChar { it.uppercase() }
                append("private fun build").append(builderName).append("(): ").append(type).append(" {\n")
                append("    val parts = arrayOf(\n")
                for (part in parts) {
                    append("        ").append(part).append(",\n")
                }
                append("    )\n")
                append("    var total = 0\n")
                append("    for (p in parts) total += p.size\n")
                append("    val out = ").append(type).append("(total)\n")
                append("    var pos = 0\n")
                append("    for (p in parts) {\n")
                append("        p.copyInto(out, pos)\n")
                append("        pos += p.size\n")
                append("    }\n")
                append("    return out\n")
                append("}\n")
                append("internal val ").append(name).append(": ").append(type).append(" by lazy { build")
                    .append(builderName).append("() }\n")
            }
            renderAggregate("GB2312_B2C", b2cParts, "CharArray")
            append("\n")
            renderAggregate("GB2312_C2B", c2bParts, "IntArray")
        }

        outputRoot.resolve("GB2312Mapping.kt").writeText(main)
    }
}

val gb2312MapFile = rootProject.projectDir
    .resolve("../jdk24u/make/data/charsetmapping/EUC_CN.map")
    .normalize()
val generatedKotlinDir = layout.buildDirectory.dir("generated/gb2312/kotlin")

val generateGB2312MappingKotlin = tasks.register<GenerateGB2312MappingKotlinTask>("generateGB2312MappingKotlin") {
    mapFile.set(gb2312MapFile)
    outputDir.set(generatedKotlinDir)
}

afterEvaluate {
    val kotlinExtension = extensions.findByName("kotlin") as? ExtensionAware ?: return@afterEvaluate
    val sourceSets = kotlinExtension.extensions.getByName("sourceSets") as NamedDomainObjectContainer<*>
    val commonMain = sourceSets.getByName("commonMain") as ExtensionAware

    tasks.matching {
        it.name.startsWith("compile") && it.name.contains("Kotlin")
    }.configureEach {
        dependsOn(generateGB2312MappingKotlin)
    }
}
