import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.BufferedReader
import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.io.InputStreamReader
import java.util.Base64
import java.util.zip.GZIPInputStream

abstract class GenerateHebMorphDataKotlinTask : DefaultTask() {
    @get:InputFile
    abstract val dictionaryFile: RegularFileProperty

    @get:InputFile
    abstract val prefixesFile: RegularFileProperty

    @get:InputFile
    abstract val descFile: RegularFileProperty

    @get:InputFile
    abstract val stemsFile: RegularFileProperty

    @get:InputFile
    abstract val sizesFile: RegularFileProperty

    @get:InputFile
    abstract val dmaskFile: RegularFileProperty

    @get:InputFile
    abstract val defaultPrefixesFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generateKotlin() {
        val inputs = listOf(
            dictionaryFile.get().asFile,
            prefixesFile.get().asFile,
            descFile.get().asFile,
            stemsFile.get().asFile,
            sizesFile.get().asFile,
            dmaskFile.get().asFile,
            defaultPrefixesFile.get().asFile,
        )
        for (file in inputs) {
            if (!file.isFile) throw GradleException("HebMorph data not found at ${file.absolutePath}")
        }

        val packageName = "org.gnit.lucenekmp.analysis.he"
        val outputRoot = outputDir.get().dir(packageName.replace('.', '/')).asFile
        outputRoot.mkdirs()

        val dmasks = readDmasks()
        val lookup = readWords(readWordCount())
        val prefixHints = GZIPInputStream(prefixesFile.get().asFile.inputStream()).use { input ->
            ByteArray(lookup.size) { input.read().toByte() }
        }
        val descRows = readDescRows(dmasks)
        val stemRows = readStemRows()
        val defaultPrefixes = readDefaultPrefixes()

        fun escaped(s: String): String = buildString {
            append('"')
            for (ch in s) {
                when (ch) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(ch)
                }
            }
            append('"')
        }

        outputRoot.listFiles { file -> file.name.startsWith("HSpellGeneratedData") && file.extension == "kt" }
            ?.forEach { it.delete() }

        fun descFlagOrdinal(dmask: Int): Int = dmask and 3

        fun DataOutputStream.writeUtf8(value: String) {
            val bytes = value.toByteArray(Charsets.UTF_8)
            writeInt(bytes.size)
            write(bytes)
        }

        fun buildEntryData(): ByteArray {
            val baos = ByteArrayOutputStream()
            DataOutputStream(baos).use { out ->
                out.writeInt(lookup.size)
                for (i in lookup.indices) {
                    val desc = descRows[i]
                    val stems = stemRows[i]
                    if (desc.size != stems.size) {
                        throw GradleException("HebMorph desc/stem count mismatch for index $i word ${lookup[i]}")
                    }
                    out.writeUtf8(lookup[i])
                    out.writeInt(prefixHints[i].toInt() and 0xff)
                    out.writeInt(stems.size)
                    for (stemPosition in stems.indices) {
                        val lemma = lookup[stems[stemPosition]]
                        val generatedLemma = if (lemma == "שונות" && lemma != lookup[i]) null else lemma
                        out.writeBoolean(generatedLemma != null)
                        if (generatedLemma != null) out.writeUtf8(generatedLemma)
                        out.writeInt(descFlagOrdinal(desc[stemPosition]))
                        out.writeInt(dmaskToPrefix(dmask = desc[stemPosition]))
                    }
                }
            }
            return baos.toByteArray()
        }

        val encoded = Base64.getEncoder().encodeToString(buildEntryData())
        val chunkSize = 60_000
        val chunkNames = mutableListOf<String>()
        encoded.chunked(chunkSize).forEachIndexed { index, chunk ->
            val name = "hSpellEntryDataChunk$index"
            chunkNames.add(name)
            outputRoot.resolve("HSpellGeneratedData_Blob_$index.kt").writeText(buildString {
                append("// Auto-generated by generateHebMorphDataKotlin. Do not edit.\n")
                append("package ").append(packageName).append("\n\n")
                append("private const val ").append(name).append(" = ").append(escaped(chunk)).append("\n\n")
                append("internal val hSpellEntryDataPart").append(index).append(": String = ").append(name).append("\n")
            })
        }

        outputRoot.resolve("HSpellGeneratedData.kt").writeText(buildString {
            append("// Auto-generated by generateHebMorphDataKotlin. Do not edit.\n")
            append("package ").append(packageName).append("\n\n")
            append("internal object HSpellGeneratedData {\n")
            append("    val prefixes: Map<String, Int> = mapOf(\n")
            for ((prefix, mask) in defaultPrefixes) {
                append("        ").append(escaped(prefix)).append(" to ").append(mask).append(",\n")
            }
            append("    )\n\n")
            append("    val entryDataBase64: String by lazy {\n")
            append("        buildString {\n")
            for (index in chunkNames.indices) {
                append("            append(hSpellEntryDataPart").append(index).append(")\n")
            }
            append("        }\n")
            append("    }\n")
            append("}\n")
        })
    }

    private fun readWordCount(): Int {
        val lines = sizesFile.get().asFile.readLines()
        val sizes = lines.getOrNull(1) ?: throw GradleException("Invalid hebrew.wgz.sizes")
        val count = sizes.substringAfter(' ').trim().toInt()
        return count - 1
    }

    private fun readDmasks(): List<Int> {
        val dmasks = mutableListOf<Int>()
        var foundStartLine = false
        for (line in dmaskFile.get().asFile.readLines()) {
            if (!foundStartLine) {
                if (line.contains("dmasks[]")) foundStartLine = true
                continue
            }
            val value = tryParseInt(line)
            if (value >= 0) dmasks.add(value)
        }
        return dmasks
    }

    private fun readWords(lookupLen: Int): Array<String> {
        val lookup = arrayOfNulls<String>(lookupLen)
        GZIPInputStream(dictionaryFile.get().asFile.inputStream()).use { input ->
            val sbuf = CharArray(127)
            var slen = 0
            var i = 0
            var c = input.read()
            while (c > -1) {
                if (c in '0'.code..'9'.code) {
                    if (i < lookup.size) lookup[i++] = String(sbuf, 0, slen)
                    var n = 0
                    do {
                        n *= 10
                        n += c - '0'.code
                        c = input.read()
                    } while (c > -1 && c in '0'.code..'9'.code)
                    slen -= n
                }
                if (c > -1) {
                    sbuf[slen++] = iso8859ToUnicode(c)
                    c = input.read()
                }
            }
        }
        return Array(lookupLen) { i -> lookup[i] ?: throw GradleException("Missing HebMorph lookup word at $i") }
    }

    private fun readDescRows(dmasks: List<Int>): List<List<Int>> {
        val rows = mutableListOf<List<Int>>()
        GZIPInputStream(descFile.get().asFile.inputStream()).use { input ->
            val buf = IntArray(5)
            var bufPos = 0
            val wordMasks = mutableListOf<Int>()
            while (true) {
                val b = input.read()
                if (b <= -1) break
                if (b == '\n'.code || b == 0) {
                    rows.add(wordMasks.toList())
                    wordMasks.clear()
                    bufPos = 0
                    continue
                }
                buf[bufPos++] = b
                if (bufPos % 2 == 0) {
                    val i = buf[0] - 'A'.code + (buf[1] - 'A'.code) * 26
                    wordMasks.add(dmasks[i])
                    bufPos = 0
                }
            }
        }
        return rows
    }

    private fun readStemRows(): List<List<Int>> {
        val rows = mutableListOf<List<Int>>()
        GZIPInputStream(stemsFile.get().asFile.inputStream()).use { input ->
            val buf = IntArray(5)
            var bufPos = 0
            val wordStems = mutableListOf<Int>()
            while (true) {
                val b = input.read()
                if (b <= -1) break
                if (b == '\n'.code || b == 0) {
                    rows.add(wordStems.toList())
                    wordStems.clear()
                    bufPos = 0
                    continue
                }
                buf[bufPos++] = b
                if (bufPos % 3 == 0) {
                    wordStems.add(buf[0] - 33 + (buf[1] - 33) * 94 + (buf[2] - 33) * 94 * 94)
                    bufPos = 0
                }
            }
        }
        return rows
    }

    private fun readDefaultPrefixes(): Map<String, Int> {
        val map = linkedMapOf<String, Int>()
        GZIPInputStream(defaultPrefixesFile.get().asFile.inputStream()).use { gzip ->
            BufferedReader(InputStreamReader(gzip, Charsets.UTF_8)).useLines { lines ->
                lines.forEach { line ->
                    val split = line.split("#")
                    if (split.size != 2) throw GradleException("Wrong HebMorph prefix format: $line")
                    map[split[0]] = split[1].toInt()
                }
            }
        }
        return map
    }

    private fun tryParseInt(str: String?): Int {
        if (str == null) return -1
        var length = str.length
        if (str.endsWith(",")) length--
        if (length == 0) return -1
        var num = 0
        for (i in 0 until length) {
            val c = str[i]
            if (c <= '/' || c >= ':') return -1
            num *= 10
            num += c - '0'
        }
        return num
    }

    private fun iso8859ToUnicode(c: Int): Char {
        return if (c in 0xE0..0xFA) {
            (c + 0x4F0).toChar()
        } else if (c <= 0xBE) {
            c.toChar()
        } else {
            ' '
        }
    }

    private fun dmaskToPrefix(dmask: Int): Int {
        var specifier: Int
        if ((dmask and D_TYPEMASK) == D_VERB) {
            specifier = if ((dmask and D_TENSEMASK) == D_IMPERATIVE) {
                PS_IMPER
            } else if ((dmask and D_TENSEMASK) != D_PRESENT) {
                PS_VERB
            } else if (((dmask and D_OSMICHUT) > 0) || ((dmask and D_OMASK) > 0)) {
                PS_NONDEF
            } else {
                PS_ALL
            }
            if ((dmask and D_TENSEMASK) == D_INFINITIVE) {
                specifier = PS_L
            } else if ((dmask and D_TENSEMASK) == D_BINFINITIVE) {
                specifier = PS_B
            }
        } else if (((dmask and D_TYPEMASK) == D_NOUN) || ((dmask and D_TYPEMASK) == D_ADJ)) {
            specifier = if (((dmask and D_OSMICHUT) > 0) || ((dmask and D_OMASK) > 0) || ((dmask and D_SPECNOUN) > 0)) {
                PS_NONDEF
            } else {
                PS_ALL
            }
        } else {
            specifier = PS_ALL
        }
        return specifier
    }

    companion object {
        private const val D_NOUN = 1
        private const val D_VERB = 2
        private const val D_ADJ = 3
        private const val D_TYPEMASK = 3
        private const val D_INFINITIVE = 256
        private const val D_BINFINITIVE = 1536
        private const val D_PRESENT = 768
        private const val D_IMPERATIVE = 1280
        private const val D_TENSEMASK = 1792
        private const val D_OMASK = 129024
        private const val D_OSMICHUT = 131072
        private const val D_SPECNOUN = 262144
        private const val PS_B = 1
        private const val PS_L = 2
        private const val PS_VERB = 4
        private const val PS_NONDEF = 8
        private const val PS_IMPER = 16
        private const val PS_ALL = 127
    }
}

val hebMorphDataDir = rootProject.projectDir.resolve("gradle/hebmorph/hspell-data-files").normalize()
val generatedHebMorphKotlinDir = layout.buildDirectory.dir("generated/hebmorph/kotlin")

val generateHebMorphDataKotlin = tasks.register<GenerateHebMorphDataKotlinTask>("generateHebMorphDataKotlin") {
    dictionaryFile.set(hebMorphDataDir.resolve("hebrew.wgz"))
    prefixesFile.set(hebMorphDataDir.resolve("hebrew.wgz.prefixes"))
    descFile.set(hebMorphDataDir.resolve("hebrew.wgz.desc"))
    stemsFile.set(hebMorphDataDir.resolve("hebrew.wgz.stems"))
    sizesFile.set(hebMorphDataDir.resolve("hebrew.wgz.sizes"))
    dmaskFile.set(hebMorphDataDir.resolve("dmask.c"))
    defaultPrefixesFile.set(hebMorphDataDir.resolve("prefix_noH.gz"))
    outputDir.set(generatedHebMorphKotlinDir)
}

tasks.matching {
    it.name.startsWith("compile") && it.name.contains("Kotlin")
}.configureEach {
    dependsOn(generateHebMorphDataKotlin)
}

tasks.matching { it.name == "compileAndroidMain" }.configureEach {
    dependsOn(generateHebMorphDataKotlin)
}

tasks.matching { it.name == "prepareKotlinIdeaImport" }.configureEach {
    dependsOn(generateHebMorphDataKotlin)
}

tasks.matching { it.name == "sourcesJar" || it.name.endsWith("SourcesJar") }.configureEach {
    dependsOn(generateHebMorphDataKotlin)
}
