import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

abstract class GenerateHornDataKotlinTask : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val amharicLexiconFiles: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val oromoLexiconFiles: ConfigurableFileCollection

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val amharicGeezSeraFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generateKotlin() {
        val allInputs = amharicLexiconFiles.files + oromoLexiconFiles.files + amharicGeezSeraFile.get().asFile
        for (file in allInputs) {
            if (!file.isFile) {
                throw GradleException("Horn data file not found at ${file.absolutePath}")
            }
        }

        val sourceBytes = allInputs.sumOf { it.length() }
        val maxBytes = 80L * 1024L * 1024L
        if (sourceBytes > maxBytes) {
            throw GradleException(
                "Selected Horn data is ${sourceBytes / 1024 / 1024} MiB, expected less than 80 MiB"
            )
        }

        val packageName = "org.gnit.lucenekmp.analysis.horn"
        val outputRoot = outputDir.get().dir(packageName.replace('.', '/')).asFile
        outputRoot.deleteRecursively()
        outputRoot.mkdirs()

        val amharicData = buildLexiconData(
            amharicLexiconFiles.files,
            prefixes = AMHARIC_GENERATED_PREFIXES,
            suffixes = AMHARIC_GENERATED_SUFFIXES,
            combinedSuffixes = AMHARIC_GENERATED_COMBINED_SUFFIXES
        )
        val oromoData = buildLexiconData(
            oromoLexiconFiles.files,
            lowercase = true,
            prefixes = emptyArray(),
            suffixes = OROMO_GENERATED_SUFFIXES,
            combinedSuffixes = emptyArray()
        )
        val geezSeraData = buildGeezSeraData(amharicGeezSeraFile.get().asFile)

        val partsMap = linkedMapOf<String, List<String>>()
        partsMap["amharicLexiconData"] = writeStringParts(packageName, outputRoot, "amharicLexiconData", amharicData)
        partsMap["oromoLexiconData"] = writeStringParts(packageName, outputRoot, "oromoLexiconData", oromoData)
        partsMap["amharicGeezSeraData"] = writeStringParts(packageName, outputRoot, "amharicGeezSeraData", geezSeraData)

        val generated = buildString {
            append("// Auto-generated by generateHornDataKotlin. Do not edit.\n")
            append("package ").append(packageName).append("\n\n")
            append("internal object HornGeneratedData {\n")
            for ((name, parts) in partsMap) {
                renderAggregateString(name, parts)
                append("\n")
            }
            append("}\n")
        }

        outputRoot.resolve("HornGeneratedData.kt").writeText(generated)
    }

    private fun buildLexiconData(
        files: Set<java.io.File>,
        lowercase: Boolean = false,
        prefixes: Array<String> = emptyArray(),
        suffixes: Array<String> = emptyArray(),
        combinedSuffixes: Array<String> = emptyArray()
    ): String {
        val entries = linkedMapOf<String, String>()
        for (file in files.sortedBy { it.name }) {
            file.forEachLine(Charsets.UTF_8) { raw ->
                val line = raw.substringBefore("#").trim()
                if (line.isEmpty()) return@forEachLine
                val columns = line.split(Regex("\\s+")).filter { it.isNotEmpty() }
                if (columns.isEmpty()) return@forEachLine
                val surface = cleanToken(columns[0], lowercase) ?: return@forEachLine
                val lemma = columns.getOrNull(1)
                    ?.let { cleanToken(it, lowercase) }
                    ?.takeUnless { it == "''" }
                    ?: surface
                if (lemma != surface) {
                    entries[surface] = lemma
                } else {
                    entries.putIfAbsent(surface, lemma)
                }
            }
        }
        addGeneratedVariants(entries, prefixes, suffixes, combinedSuffixes)
        return buildString {
            for ((surface, lemma) in entries) {
                append(surface)
                if (lemma != surface) {
                    append('\t').append(lemma)
                }
                append('\n')
            }
        }
    }

    private fun addGeneratedVariants(
        entries: LinkedHashMap<String, String>,
        prefixes: Array<String>,
        suffixes: Array<String>,
        combinedSuffixes: Array<String>
    ) {
        val baseEntries = entries.entries.toList()
        for ((surface, lemma) in baseEntries) {
            if (!shouldExpand(surface) || !shouldExpand(lemma)) continue
            for (suffix in suffixes) {
                entries.putIfAbsent(surface + suffix, lemma)
            }
            for (prefix in prefixes) {
                entries.putIfAbsent(prefix + surface, lemma)
                for (suffix in combinedSuffixes) {
                    entries.putIfAbsent(prefix + surface + suffix, lemma)
                }
            }
        }
    }

    private fun shouldExpand(token: String): Boolean {
        if (token.length < 3) return false
        if (token.any { it == '[' || it == ']' || it == '{' || it == '}' }) return false
        return true
    }

    private fun cleanToken(value: String, lowercase: Boolean): String? {
        val trimmed = value.trim()
        if (trimmed.isEmpty()) return null
        if (trimmed.startsWith("[") || trimmed.startsWith("{")) return null
        if (trimmed == "''") return null
        val cleaned = trimmed.trim(',', ';')
        if (cleaned.isEmpty()) return null
        return if (lowercase) cleaned.lowercase() else cleaned
    }

    private fun buildGeezSeraData(file: java.io.File): String {
        val entries = linkedMapOf<String, String>()
        file.forEachLine(Charsets.UTF_8) { raw ->
            val line = raw.substringBefore("#").trim()
            if (line.isEmpty()) return@forEachLine
            for (part in line.split(Regex("\\s+"))) {
                val columns = part.split("=")
                if (columns.size >= 2 && columns[0].isNotEmpty() && columns[1].isNotEmpty()) {
                    entries.putIfAbsent(columns[0], columns.last())
                }
            }
        }
        return buildString {
            for ((geez, sera) in entries) {
                append(geez).append('\t').append(sera).append('\n')
            }
        }
    }

    private fun writeStringParts(
        packageName: String,
        outputRoot: java.io.File,
        name: String,
        value: String,
        maxFileSize: Int = 900_000
    ): List<String> {
        val chunkSize = 20_000
        val chunks = value.chunked(chunkSize)
        val partNames = mutableListOf<String>()
        var partIndex = 0
        var chunkIndex = 0
        var chunkNames = mutableListOf<String>()
        var builder = newPartBuilder(packageName)

        fun closePart() {
            if (chunkNames.isEmpty()) return
            val partName = name + "Part" + partIndex
            builder.renderPartString(partName, chunkNames)
            outputRoot.resolve("HornGeneratedData_${name}_${partIndex}.kt").writeText(builder.toString())
            partNames.add(partName)
            partIndex++
            chunkNames = mutableListOf()
            builder = newPartBuilder(packageName)
        }

        for (chunk in chunks) {
            val chunkName = name + "Chunk" + chunkIndex
            val chunkSource = buildString {
                append("private const val ").append(chunkName).append(" = ")
                append(escaped(chunk)).append("\n")
            }
            if (builder.length + chunkSource.length >= maxFileSize && chunkNames.isNotEmpty()) {
                closePart()
            }
            builder.append(chunkSource)
            chunkNames.add(chunkName)
            chunkIndex++
        }
        closePart()
        return partNames
    }

    private fun newPartBuilder(packageName: String): StringBuilder {
        return StringBuilder()
            .append("// Auto-generated by generateHornDataKotlin. Do not edit.\n")
            .append("package ").append(packageName).append("\n\n")
    }

    private fun StringBuilder.renderPartString(partName: String, chunkNames: List<String>) {
        append("internal val ").append(partName).append(": String by lazy {\n")
        append("    buildString {\n")
        for (chunkName in chunkNames) {
            append("        append(").append(chunkName).append(")\n")
        }
        append("    }\n")
        append("}\n")
    }

    private fun StringBuilder.renderAggregateString(name: String, parts: List<String>) {
        append("    val ").append(name).append(": String by lazy {\n")
        append("        buildString {\n")
        for (part in parts) {
            append("            append(").append(part).append(")\n")
        }
        append("        }\n")
        append("    }\n")
    }

    private fun escaped(value: String): String {
        return buildString {
            append('"')
            for (ch in value) {
                when (ch) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(ch)
                }
            }
            append('"')
        }
    }

    companion object {
        private val AMHARIC_GENERATED_PREFIXES: Array<String> = arrayOf(
            "ye",
            "le",
            "be",
            "ke",
            "s",
            "'nde"
        )

        private val AMHARIC_GENERATED_SUFFIXES: Array<String> = arrayOf(
            "oc",
            "ocn",
            "ocm",
            "ocnm",
            "acn",
            "acnm",
            "Woc",
            "Wocn",
            "Wocm",
            "Wocnm",
            "N_a",
            "n_et",
            "m",
            "n",
            "s"
        )

        private val AMHARIC_GENERATED_COMBINED_SUFFIXES: Array<String> = arrayOf(
            "oc",
            "ocn",
            "Woc",
            "Wocn",
            "m",
            "n"
        )

        private val OROMO_GENERATED_SUFFIXES: Array<String> = arrayOf(
            "oota",
            "wwan",
            "leen",
            "tti",
            "irra",
            "iin",
            "aan",
            "een",
            "ummaa",
            "n",
            "ni"
        )
    }
}

val hornDir = rootProject.projectDir.resolve("gradle/horn").normalize()
val hornGeneratedKotlinDir = layout.buildDirectory.dir("generated/horn/kotlin")

val generateHornDataKotlin = tasks.register<GenerateHornDataKotlinTask>("generateHornDataKotlin") {
    amharicLexiconFiles.from(
        hornDir.resolve("am/lex/n_stem.lex"),
        hornDir.resolve("am/lex/n_stemG.lex"),
        hornDir.resolve("am/lex/n_stem_an.lex"),
        hornDir.resolve("am/lex/n_analyzed.lex"),
        hornDir.resolve("am/lex/n_analyzed_phon.lex"),
        hornDir.resolve("am/lex/irr_plr.lex"),
        hornDir.resolve("am/lex/irr_n.lex"),
        hornDir.resolve("am/lex/irr_conj.lex"),
        hornDir.resolve("am/lex/words.lex"),
        hornDir.resolve("am/lex/words_phon.lex"),
        hornDir.resolve("am/lex/n_name.lex"),
        hornDir.resolve("am/lex/n_nameG.lex"),
        hornDir.resolve("am/lex/n_place.lex"),
        hornDir.resolve("am/lex/n_placeG.lex"),
        hornDir.resolve("am/lex/prep_n.lex"),
        hornDir.resolve("am/lex/ppron.lex"),
        hornDir.resolve("am/lex/ppronG.lex"),
        hornDir.resolve("am/lex/alle.lex"),
        hornDir.resolve("am/lex/new.lex"),
        hornDir.resolve("am/lex/vb_root.lex"),
        hornDir.resolve("am/lex/vb_rootG.lex"),
        hornDir.resolve("am/lex/v_analyzed.lex"),
        hornDir.resolve("am/lex/v_analyzed_phon.lex"),
        hornDir.resolve("am/lex/irr_stem.lex"),
        hornDir.resolve("am/lex/irr_vnoun.lex"),
    )
    oromoLexiconFiles.from(
        hornDir.resolve("om/lex/nouns.lex"),
        hornDir.resolve("om/lex/nouns0.lex"),
        hornDir.resolve("om/lex/nouns_pl.lex"),
        hornDir.resolve("om/lex/nouns_f.lex"),
        hornDir.resolve("om/lex/nouns_m.lex"),
        hornDir.resolve("om/lex/words.lex"),
        hornDir.resolve("om/lex/v_stems.lex"),
        hornDir.resolve("om/lex/v_stem.lex"),
        hornDir.resolve("om/lex/irr_stem.lex"),
        hornDir.resolve("om/lex/irr_stem+.lex"),
        hornDir.resolve("om/lex/irr_stemG.lex"),
    )
    amharicGeezSeraFile.set(hornDir.resolve("geez/am_conv_sera.txt"))
    outputDir.set(hornGeneratedKotlinDir)
}

tasks.matching {
    it.name.startsWith("compile") && it.name.contains("Kotlin")
}.configureEach {
    dependsOn(generateHornDataKotlin)
}

tasks.matching { it.name == "prepareKotlinIdeaImport" }.configureEach {
    dependsOn(generateHornDataKotlin)
}
