#!/usr/bin/env -S kotlin -J--enable-native-access=ALL-UNNAMED -J--sun-misc-unsafe-memory-access=allow

package org.gnit.lucenekmp.tests.analysis

import java.io.File
import java.net.URL
import kotlin.system.exitProcess

fun usageAndExit(scriptName: String, badVersion: String? = null): Nothing {
    System.err.println("Usage: $scriptName -v <version>")
    if (!badVersion.isNullOrEmpty()) {
        System.err.println("\tversion must be of the form X.Y, e.g. 11.0")
    }
    exitProcess(1)
}

fun parseVersion(args: Array<String>, scriptName: String): String {
    var version: String? = null
    var i = 0
    while (i < args.size) {
        when (val arg = args[i]) {
            "-v", "--version" -> {
                if (i + 1 >= args.size) usageAndExit(scriptName)
                version = args[i + 1]
                i += 2
            }
            else -> {
                if (arg.startsWith("--version=")) {
                    version = arg.substringAfter('=')
                    i += 1
                } else {
                    usageAndExit(scriptName)
                }
            }
        }
    }

    val resolved = version ?: usageAndExit(scriptName)
    if (!Regex("\\d+\\.\\d+").matches(resolved)) {
        usageAndExit(scriptName, resolved)
    }
    return resolved
}

fun aboveBmpCharToSurrogates(hexCodePoint: String): List<String> {
    val ch = hexCodePoint.toInt(16)
    val highSurrogate = 0xD800 + ((ch - 0x10000) shr 10)
    val lowSurrogate = 0xDC00 + (ch and 0x3FF)
    return listOf("%04X".format(highSurrogate), "%04X".format(lowSurrogate))
}

fun getUrlContent(url: String): String {
    System.err.print("Retrieving '$url'...")
    return try {
        val content = URL(url).readText()
        System.err.println("done.")
        content
    } catch (e: Exception) {
        System.err.println("Failed to download '$url':\n\t${e.message}")
        exitProcess(1)
    }
}

val scriptName = File(System.getProperty("kotlin.script.file") ?: "generateEmojiTokenizationTest.main.kts").name
val version = parseVersion(args, scriptName)
val url = "http://www.unicode.org/Public/emoji/$version/emoji-test.txt"
val underscoreVersion = version.replace('.', '_')
val className = "EmojiTokenizationTestUnicode_$underscoreVersion"
val outputFilename = "$className.kt"

val header = """
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gnit.lucenekmp.tests.analysis.standard

import org.gnit.lucenekmp.analysis.Analyzer
import org.gnit.lucenekmp.tests.analysis.BaseTokenStreamTestCase

/**
 * This class was automatically generated by $scriptName.
 * from: <$url>
 */
object $className {

    @Throws(Exception::class)
    fun test(analyzer: Analyzer) {
        for (i in TESTS.indices step 2) {
            val test = TESTS[i + 1]
            try {
                BaseTokenStreamTestCase.assertAnalyzesTo(analyzer, test, arrayOf(test), arrayOf("<EMOJI>"))
            } catch (t: Throwable) {
                throw Exception("Failed to tokenize \"${'$'}{TESTS[i]}\":", t)
            }
        }
    }

    private val TESTS = arrayOf(
""".trimIndent()

val tests = getUrlContent(url).split(Regex("\\r?\\n"))

val scriptDir = File(System.getProperty("kotlin.script.file") ?: ".").absoluteFile.parentFile
val outputDir = scriptDir.resolve("../../../../../../kotlin/org/gnit/lucenekmp/tests/analysis/standard").canonicalFile
val outputPath = outputDir.resolve(outputFilename)

System.err.print("Writing '${outputPath.absolutePath}'...")

outputPath.bufferedWriter().use { out ->
    out.write(header)

    var isFirst = true
    for (rawLine in tests) {
        if (rawLine.isBlank() || rawLine.trimStart().startsWith("#")) {
            continue
        }

        if (!isFirst) {
            out.write(",\n\n")
        }
        isFirst = false

        var line = rawLine.trimEnd().replace("\t", "  ")
        out.write("        \"")
        out.write(line.replace("\\", "\\\\").replace("\"", "\\\""))
        out.write("\",\n")

        val testStringRaw = line.substringBefore(';').trimEnd()
        var testString = Regex("[0-9A-F]+").replace(testStringRaw) { "\\u${it.value}" }
        testString = Regex("\\\\u([0-9A-F]{5,})").replace(testString) { m ->
            aboveBmpCharToSurrogates(m.groupValues[1]).joinToString("") { "\\u$it" }
        }
        testString = testString.replace(" ", "")

        out.write("        \"")
        out.write(testString)
        out.write("\"")
    }

    out.write("\n    )\n}\n")
}

System.err.println("done.")
