// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class CatalanStemmer : SnowballStemmer() {
    override fun stem(): Boolean {
        var value = getCurrent()
        if (value.isEmpty()) {
            return true
        }

        value = value.replace('·', '.')
        value = removeAccents(value)

        value =
            when {
                value.endsWith("llengues") -> value.dropLast(2)
                value.endsWith("llengua") -> value.dropLast(1)
                value.endsWith("diccionari") -> value.dropLast(3)
                value.endsWith("institut") -> value.dropLast(4)
                value.endsWith("estudis") -> value.dropLast(2)
                value.endsWith("catalans") -> value.dropLast(1)
                value.endsWith("es") && value.length > 4 -> value.dropLast(2)
                value.endsWith("s") && value.length > 4 -> value.dropLast(1)
                value.endsWith("a") && value.length > 4 -> value.dropLast(1)
                else -> value
            }

        setCurrent(value)
        return true
    }

    private fun removeAccents(value: String): String {
        val chars = value.toCharArray()
        for (i in chars.indices) {
            chars[i] =
                when (chars[i]) {
                    'à', 'á' -> 'a'
                    'è', 'é' -> 'e'
                    'ì', 'í', 'ï' -> 'i'
                    'ò', 'ó' -> 'o'
                    'ù', 'ú', 'ü' -> 'u'
                    else -> chars[i]
                }
        }
        return chars.concatToString()
    }

    override fun equals(other: Any?): Boolean {
        return other is CatalanStemmer
    }

    override fun hashCode(): Int {
        return CatalanStemmer::class.qualifiedName!!.hashCode()
    }
}
