// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class DutchStemmer : SnowballStemmer() {
    private val a_0 = arrayOf(
        Among("", -1, 6),
        Among("\u00E1", 0, 1),
        Among("\u00E4", 0, 1),
        Among("\u00E9", 0, 2),
        Among("\u00EB", 0, 2),
        Among("\u00ED", 0, 3),
        Among("\u00EF", 0, 3),
        Among("\u00F3", 0, 4),
        Among("\u00F6", 0, 4),
        Among("\u00FA", 0, 5),
        Among("\u00FC", 0, 5)
    )

    private val a_1 = arrayOf(
        Among("", -1, 3),
        Among("I", 0, 2),
        Among("Y", 0, 1)
    )

    private val a_2 = arrayOf(
        Among("dd", -1, -1),
        Among("kk", -1, -1),
        Among("tt", -1, -1)
    )

    private val a_3 = arrayOf(
        Among("ene", -1, 2),
        Among("se", -1, 3),
        Among("en", -1, 2),
        Among("heden", 2, 1),
        Among("s", -1, 3)
    )

    private val a_4 = arrayOf(
        Among("end", -1, 1),
        Among("ig", -1, 2),
        Among("ing", -1, 1),
        Among("lijk", -1, 3),
        Among("baar", -1, 4),
        Among("bar", -1, 5)
    )

    private val a_5 = arrayOf(
        Among("aa", -1, -1),
        Among("ee", -1, -1),
        Among("oo", -1, -1),
        Among("uu", -1, -1)
    )

    private val g_v = charArrayOf(
        17.toChar(),
        65.toChar(),
        16.toChar(),
        1.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        128.toChar()
    )

    private val g_v_I = charArrayOf(
        1.toChar(),
        0.toChar(),
        0.toChar(),
        17.toChar(),
        65.toChar(),
        16.toChar(),
        1.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        128.toChar()
    )

    private val g_v_j = charArrayOf(
        17.toChar(),
        67.toChar(),
        16.toChar(),
        1.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        128.toChar()
    )

    private var I_p2 = 0
    private var I_p1 = 0
    private var B_e_found = false

    private fun r_prelude(): Boolean {
        val v_1 = cursor
        loop@ while (true) {
            val v_2 = cursor
            bra = cursor
            val among_var = find_among(a_0)
            ket = cursor
            when (among_var) {
                1 -> {
                    slice_from("a")
                    continue@loop
                }
                2 -> {
                    slice_from("e")
                    continue@loop
                }
                3 -> {
                    slice_from("i")
                    continue@loop
                }
                4 -> {
                    slice_from("o")
                    continue@loop
                }
                5 -> {
                    slice_from("u")
                    continue@loop
                }
                6 -> {
                    if (cursor >= limit) {
                        cursor = v_2
                        break@loop
                    }
                    cursor++
                    continue@loop
                }
                else -> {
                    cursor = v_2
                    break@loop
                }
            }
        }
        cursor = v_1
        val v_3 = cursor
        run lab1@{
            bra = cursor
            if (!eq_s("y")) {
                cursor = v_3
                return@lab1
            }
            ket = cursor
            slice_from("Y")
        }
        loop2@ while (true) {
            val v_4 = cursor
            var continueOuter = false
            while (true) {
                val v_5 = cursor
                if (in_grouping(g_v, 97, 232)) {
                    bra = cursor
                    val v_6 = cursor
                    if (eq_s("i")) {
                        ket = cursor
                        if (in_grouping(g_v, 97, 232)) {
                            slice_from("I")
                            cursor = v_5
                            continueOuter = true
                            break
                        }
                    }
                    cursor = v_6
                    if (eq_s("y")) {
                        ket = cursor
                        slice_from("Y")
                        cursor = v_5
                        continueOuter = true
                        break
                    }
                }
                cursor = v_5
                if (cursor >= limit) {
                    cursor = v_4
                    continueOuter = false
                    break
                }
                cursor++
            }
            if (continueOuter) {
                continue@loop2
            }
            break@loop2
        }
        return true
    }

    private fun r_mark_regions(): Boolean {
        I_p1 = limit
        I_p2 = limit
        while (true) {
            if (in_grouping(g_v, 97, 232)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        while (true) {
            if (out_grouping(g_v, 97, 232)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        I_p1 = cursor
        if (I_p1 < 3) {
            I_p1 = 3
        }
        while (true) {
            if (in_grouping(g_v, 97, 232)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        while (true) {
            if (out_grouping(g_v, 97, 232)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        I_p2 = cursor
        return true
    }

    private fun r_postlude(): Boolean {
        loop@ while (true) {
            val v_1 = cursor
            bra = cursor
            val among_var = find_among(a_1)
            ket = cursor
            when (among_var) {
                1 -> {
                    slice_from("y")
                    continue@loop
                }
                2 -> {
                    slice_from("i")
                    continue@loop
                }
                3 -> {
                    if (cursor >= limit) {
                        cursor = v_1
                        break@loop
                    }
                    cursor++
                    continue@loop
                }
                else -> {
                    cursor = v_1
                    break@loop
                }
            }
        }
        return true
    }

    private fun r_R1(): Boolean {
        return I_p1 <= cursor
    }

    private fun r_R2(): Boolean {
        return I_p2 <= cursor
    }

    private fun r_undouble(): Boolean {
        val v_1 = limit - cursor
        if (find_among_b(a_2) == 0) {
            return false
        }
        cursor = limit - v_1
        ket = cursor
        if (cursor <= limit_backward) {
            return false
        }
        cursor--
        bra = cursor
        slice_del()
        return true
    }

    private fun r_e_ending(): Boolean {
        B_e_found = false
        ket = cursor
        if (!eq_s_b("e")) {
            return false
        }
        bra = cursor
        if (!r_R1()) {
            return false
        }
        val v_1 = limit - cursor
        if (!out_grouping_b(g_v, 97, 232)) {
            return false
        }
        cursor = limit - v_1
        slice_del()
        B_e_found = true
        if (!r_undouble()) {
            return false
        }
        return true
    }

    private fun r_en_ending(): Boolean {
        if (!r_R1()) {
            return false
        }
        val v_1 = limit - cursor
        if (!out_grouping_b(g_v, 97, 232)) {
            return false
        }
        cursor = limit - v_1
        run lab0@{
            val v_2 = limit - cursor
            if (!eq_s_b("gem")) {
                cursor = limit - v_2
                return@lab0
            }
            return false
        }
        slice_del()
        if (!r_undouble()) {
            return false
        }
        return true
    }

    private fun r_standard_suffix(): Boolean {
        val v_1 = limit - cursor
        run lab0@{
            ket = cursor
            val among_var = find_among_b(a_3)
            if (among_var == 0) {
                return@lab0
            }
            bra = cursor
            when (among_var) {
                1 -> {
                    if (!r_R1()) {
                        return@lab0
                    }
                    slice_from("heid")
                }
                2 -> {
                    if (!r_en_ending()) {
                        return@lab0
                    }
                }
                3 -> {
                    if (!r_R1()) {
                        return@lab0
                    }
                    if (!out_grouping_b(g_v_j, 97, 232)) {
                        return@lab0
                    }
                    slice_del()
                }
            }
        }
        cursor = limit - v_1
        val v_2 = limit - cursor
        r_e_ending()
        cursor = limit - v_2
        val v_3 = limit - cursor
        run lab1@{
            ket = cursor
            if (!eq_s_b("heid")) {
                return@lab1
            }
            bra = cursor
            if (!r_R2()) {
                return@lab1
            }
            run lab2@{
                val v_4 = limit - cursor
                if (!eq_s_b("c")) {
                    cursor = limit - v_4
                    return@lab2
                }
                return@lab1
            }
            slice_del()
            ket = cursor
            if (!eq_s_b("en")) {
                return@lab1
            }
            bra = cursor
            if (!r_en_ending()) {
                return@lab1
            }
        }
        cursor = limit - v_3
        val v_5 = limit - cursor
        run lab3@{
            ket = cursor
            val among_var = find_among_b(a_4)
            if (among_var == 0) {
                return@lab3
            }
            bra = cursor
            when (among_var) {
                1 -> {
                    if (!r_R2()) {
                        return@lab3
                    }
                    slice_del()
                    run lab4@{
                        val v_6 = limit - cursor
                        run lab5@{
                            ket = cursor
                            if (!eq_s_b("ig")) {
                                return@lab5
                            }
                            bra = cursor
                            if (!r_R2()) {
                                return@lab5
                            }
                            run lab6@{
                                val v_7 = limit - cursor
                                if (!eq_s_b("e")) {
                                    cursor = limit - v_7
                                    return@lab6
                                }
                                return@lab5
                            }
                            slice_del()
                            return@lab4
                        }
                        cursor = limit - v_6
                        if (!r_undouble()) {
                            return@lab3
                        }
                    }
                }
                2 -> {
                    if (!r_R2()) {
                        return@lab3
                    }
                    run lab7@{
                        val v_8 = limit - cursor
                        if (!eq_s_b("e")) {
                            cursor = limit - v_8
                            return@lab7
                        }
                        return@lab3
                    }
                    slice_del()
                }
                3 -> {
                    if (!r_R2()) {
                        return@lab3
                    }
                    slice_del()
                    if (!r_e_ending()) {
                        return@lab3
                    }
                }
                4 -> {
                    if (!r_R2()) {
                        return@lab3
                    }
                    slice_del()
                }
                5 -> {
                    if (!r_R2()) {
                        return@lab3
                    }
                    if (!B_e_found) {
                        return@lab3
                    }
                    slice_del()
                }
            }
        }
        cursor = limit - v_5
        val v_9 = limit - cursor
        run lab8@{
            if (!out_grouping_b(g_v_I, 73, 232)) {
                return@lab8
            }
            val v_10 = limit - cursor
            if (find_among_b(a_5) == 0) {
                return@lab8
            }
            if (!out_grouping_b(g_v, 97, 232)) {
                return@lab8
            }
            cursor = limit - v_10
            ket = cursor
            if (cursor <= limit_backward) {
                return@lab8
            }
            cursor--
            bra = cursor
            slice_del()
        }
        cursor = limit - v_9
        return true
    }

    override fun stem(): Boolean {
        val v_1 = cursor
        r_prelude()
        cursor = v_1
        val v_2 = cursor
        r_mark_regions()
        cursor = v_2
        limit_backward = cursor
        cursor = limit
        r_standard_suffix()
        cursor = limit_backward
        val v_4 = cursor
        r_postlude()
        cursor = v_4
        return true
    }

    override fun equals(other: Any?): Boolean {
        return other is DutchStemmer
    }

    override fun hashCode(): Int {
        return DutchStemmer::class.qualifiedName!!.hashCode()
    }
}
