// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class EstonianStemmer : SnowballStemmer() {
    private val a_0 = arrayOf(Among("gi", -1, 1), Among("ki", -1, 2))

    private val a_1 = arrayOf(
        Among("da", -1, 3),
        Among("mata", -1, 1),
        Among("b", -1, 3),
        Among("ksid", -1, 1),
        Among("nuksid", 3, 1),
        Among("me", -1, 3),
        Among("sime", 5, 1),
        Among("ksime", 6, 1),
        Among("nuksime", 7, 1),
        Among("akse", -1, 2),
        Among("dakse", 9, 1),
        Among("takse", 9, 1),
        Among("site", -1, 1),
        Among("ksite", 12, 1),
        Among("nuksite", 13, 1),
        Among("n", -1, 3),
        Among("sin", 15, 1),
        Among("ksin", 16, 1),
        Among("nuksin", 17, 1),
        Among("daks", -1, 1),
        Among("taks", -1, 1)
    )

    private val a_2 = arrayOf(
        Among("aa", -1, -1),
        Among("ee", -1, -1),
        Among("ii", -1, -1),
        Among("oo", -1, -1),
        Among("uu", -1, -1),
        Among("ää", -1, -1),
        Among("õõ", -1, -1),
        Among("öö", -1, -1),
        Among("üü", -1, -1)
    )

    private val a_3 = arrayOf(Among("i", -1, 1))

    private val a_4 = arrayOf(
        Among("lane", -1, 1),
        Among("line", -1, 3),
        Among("mine", -1, 2),
        Among("lasse", -1, 1),
        Among("lisse", -1, 3),
        Among("misse", -1, 2),
        Among("lasi", -1, 1),
        Among("lisi", -1, 3),
        Among("misi", -1, 2),
        Among("last", -1, 1),
        Among("list", -1, 3),
        Among("mist", -1, 2)
    )

    private val a_5 = arrayOf(
        Among("ga", -1, 1),
        Among("ta", -1, 1),
        Among("le", -1, 1),
        Among("sse", -1, 1),
        Among("l", -1, 1),
        Among("s", -1, 1),
        Among("ks", 5, 1),
        Among("t", -1, 2),
        Among("lt", 7, 1),
        Among("st", 7, 1)
    )

    private val a_6 = arrayOf(
        Among("", -1, 2),
        Among("las", 0, 1),
        Among("lis", 0, 1),
        Among("mis", 0, 1),
        Among("t", 0, -1)
    )

    private val a_7 = arrayOf(
        Among("d", -1, 4),
        Among("sid", 0, 2),
        Among("de", -1, 4),
        Among("ikkude", 2, 1),
        Among("ike", -1, 1),
        Among("ikke", -1, 1),
        Among("te", -1, 3)
    )

    private val a_8 = arrayOf(
        Among("va", -1, -1),
        Among("du", -1, -1),
        Among("nu", -1, -1),
        Among("tu", -1, -1)
    )

    private val a_9 = arrayOf(Among("kk", -1, 1), Among("pp", -1, 2), Among("tt", -1, 3))

    private val a_10 = arrayOf(Among("ma", -1, 2), Among("mai", -1, 1), Among("m", -1, 1))

    private val a_11 = arrayOf(
        Among("joob", -1, 1),
        Among("jood", -1, 1),
        Among("joodakse", 1, 1),
        Among("jooma", -1, 1),
        Among("joomata", 3, 1),
        Among("joome", -1, 1),
        Among("joon", -1, 1),
        Among("joote", -1, 1),
        Among("joovad", -1, 1),
        Among("juua", -1, 1),
        Among("juuakse", 9, 1),
        Among("jäi", -1, 12),
        Among("jäid", 11, 12),
        Among("jäime", 11, 12),
        Among("jäin", 11, 12),
        Among("jäite", 11, 12),
        Among("jääb", -1, 12),
        Among("jääd", -1, 12),
        Among("jääda", 17, 12),
        Among("jäädakse", 18, 12),
        Among("jäädi", 17, 12),
        Among("jääks", -1, 12),
        Among("jääksid", 21, 12),
        Among("jääksime", 21, 12),
        Among("jääksin", 21, 12),
        Among("jääksite", 21, 12),
        Among("jääma", -1, 12),
        Among("jäämata", 26, 12),
        Among("jääme", -1, 12),
        Among("jään", -1, 12),
        Among("jääte", -1, 12),
        Among("jäävad", -1, 12),
        Among("jõi", -1, 1),
        Among("jõid", 32, 1),
        Among("jõime", 32, 1),
        Among("jõin", 32, 1),
        Among("jõite", 32, 1),
        Among("keeb", -1, 4),
        Among("keed", -1, 4),
        Among("keedakse", 38, 4),
        Among("keeks", -1, 4),
        Among("keeksid", 40, 4),
        Among("keeksime", 40, 4),
        Among("keeksin", 40, 4),
        Among("keeksite", 40, 4),
        Among("keema", -1, 4),
        Among("keemata", 45, 4),
        Among("keeme", -1, 4),
        Among("keen", -1, 4),
        Among("kees", -1, 4),
        Among("keeta", -1, 4),
        Among("keete", -1, 4),
        Among("keevad", -1, 4),
        Among("käia", -1, 8),
        Among("käiakse", 53, 8),
        Among("käib", -1, 8),
        Among("käid", -1, 8),
        Among("käidi", 56, 8),
        Among("käiks", -1, 8),
        Among("käiksid", 58, 8),
        Among("käiksime", 58, 8),
        Among("käiksin", 58, 8),
        Among("käiksite", 58, 8),
        Among("käima", -1, 8),
        Among("käimata", 63, 8),
        Among("käime", -1, 8),
        Among("käin", -1, 8),
        Among("käis", -1, 8),
        Among("käite", -1, 8),
        Among("käivad", -1, 8),
        Among("laob", -1, 16),
        Among("laod", -1, 16),
        Among("laoks", -1, 16),
        Among("laoksid", 72, 16),
        Among("laoksime", 72, 16),
        Among("laoksin", 72, 16),
        Among("laoksite", 72, 16),
        Among("laome", -1, 16),
        Among("laon", -1, 16),
        Among("laote", -1, 16),
        Among("laovad", -1, 16),
        Among("loeb", -1, 14),
        Among("loed", -1, 14),
        Among("loeks", -1, 14),
        Among("loeksid", 83, 14),
        Among("loeksime", 83, 14),
        Among("loeksin", 83, 14),
        Among("loeksite", 83, 14),
        Among("loeme", -1, 14),
        Among("loen", -1, 14),
        Among("loete", -1, 14),
        Among("loevad", -1, 14),
        Among("loob", -1, 7),
        Among("lood", -1, 7),
        Among("loodi", 93, 7),
        Among("looks", -1, 7),
        Among("looksid", 95, 7),
        Among("looksime", 95, 7),
        Among("looksin", 95, 7),
        Among("looksite", 95, 7),
        Among("looma", -1, 7),
        Among("loomata", 100, 7),
        Among("loome", -1, 7),
        Among("loon", -1, 7),
        Among("loote", -1, 7),
        Among("loovad", -1, 7),
        Among("luua", -1, 7),
        Among("luuakse", 106, 7),
        Among("lõi", -1, 6),
        Among("lõid", 108, 6),
        Among("lõime", 108, 6),
        Among("lõin", 108, 6),
        Among("lõite", 108, 6),
        Among("lööb", -1, 5),
        Among("lööd", -1, 5),
        Among("löödakse", 114, 5),
        Among("löödi", 114, 5),
        Among("lööks", -1, 5),
        Among("lööksid", 117, 5),
        Among("lööksime", 117, 5),
        Among("lööksin", 117, 5),
        Among("lööksite", 117, 5),
        Among("lööma", -1, 5),
        Among("löömata", 122, 5),
        Among("lööme", -1, 5),
        Among("löön", -1, 5),
        Among("lööte", -1, 5),
        Among("löövad", -1, 5),
        Among("lüüa", -1, 5),
        Among("lüüakse", 128, 5),
        Among("müüa", -1, 13),
        Among("müüakse", 130, 13),
        Among("müüb", -1, 13),
        Among("müüd", -1, 13),
        Among("müüdi", 133, 13),
        Among("müüks", -1, 13),
        Among("müüksid", 135, 13),
        Among("müüksime", 135, 13),
        Among("müüksin", 135, 13),
        Among("müüksite", 135, 13),
        Among("müüma", -1, 13),
        Among("müümata", 140, 13),
        Among("müüme", -1, 13),
        Among("müün", -1, 13),
        Among("müüs", -1, 13),
        Among("müüte", -1, 13),
        Among("müüvad", -1, 13),
        Among("näeb", -1, 18),
        Among("näed", -1, 18),
        Among("näeks", -1, 18),
        Among("näeksid", 149, 18),
        Among("näeksime", 149, 18),
        Among("näeksin", 149, 18),
        Among("näeksite", 149, 18),
        Among("näeme", -1, 18),
        Among("näen", -1, 18),
        Among("näete", -1, 18),
        Among("näevad", -1, 18),
        Among("nägema", -1, 18),
        Among("nägemata", 158, 18),
        Among("näha", -1, 18),
        Among("nähakse", 160, 18),
        Among("nähti", -1, 18),
        Among("põeb", -1, 15),
        Among("põed", -1, 15),
        Among("põeks", -1, 15),
        Among("põeksid", 165, 15),
        Among("põeksime", 165, 15),
        Among("põeksin", 165, 15),
        Among("põeksite", 165, 15),
        Among("põeme", -1, 15),
        Among("põen", -1, 15),
        Among("põete", -1, 15),
        Among("põevad", -1, 15),
        Among("saab", -1, 2),
        Among("saad", -1, 2),
        Among("saada", 175, 2),
        Among("saadakse", 176, 2),
        Among("saadi", 175, 2),
        Among("saaks", -1, 2),
        Among("saaksid", 179, 2),
        Among("saaksime", 179, 2),
        Among("saaksin", 179, 2),
        Among("saaksite", 179, 2),
        Among("saama", -1, 2),
        Among("saamata", 184, 2),
        Among("saame", -1, 2),
        Among("saan", -1, 2),
        Among("saate", -1, 2),
        Among("saavad", -1, 2),
        Among("sai", -1, 2),
        Among("said", 190, 2),
        Among("saime", 190, 2),
        Among("sain", 190, 2),
        Among("saite", 190, 2),
        Among("sõi", -1, 9),
        Among("sõid", 195, 9),
        Among("sõime", 195, 9),
        Among("sõin", 195, 9),
        Among("sõite", 195, 9),
        Among("sööb", -1, 9),
        Among("sööd", -1, 9),
        Among("söödakse", 201, 9),
        Among("söödi", 201, 9),
        Among("sööks", -1, 9),
        Among("sööksid", 204, 9),
        Among("sööksime", 204, 9),
        Among("sööksin", 204, 9),
        Among("sööksite", 204, 9),
        Among("sööma", -1, 9),
        Among("söömata", 209, 9),
        Among("sööme", -1, 9),
        Among("söön", -1, 9),
        Among("sööte", -1, 9),
        Among("söövad", -1, 9),
        Among("süüa", -1, 9),
        Among("süüakse", 215, 9),
        Among("teeb", -1, 17),
        Among("teed", -1, 17),
        Among("teeks", -1, 17),
        Among("teeksid", 219, 17),
        Among("teeksime", 219, 17),
        Among("teeksin", 219, 17),
        Among("teeksite", 219, 17),
        Among("teeme", -1, 17),
        Among("teen", -1, 17),
        Among("teete", -1, 17),
        Among("teevad", -1, 17),
        Among("tegema", -1, 17),
        Among("tegemata", 228, 17),
        Among("teha", -1, 17),
        Among("tehakse", 230, 17),
        Among("tehti", -1, 17),
        Among("toob", -1, 10),
        Among("tood", -1, 10),
        Among("toodi", 234, 10),
        Among("tooks", -1, 10),
        Among("tooksid", 236, 10),
        Among("tooksime", 236, 10),
        Among("tooksin", 236, 10),
        Among("tooksite", 236, 10),
        Among("tooma", -1, 10),
        Among("toomata", 241, 10),
        Among("toome", -1, 10),
        Among("toon", -1, 10),
        Among("toote", -1, 10),
        Among("toovad", -1, 10),
        Among("tuua", -1, 10),
        Among("tuuakse", 247, 10),
        Among("tõi", -1, 10),
        Among("tõid", 249, 10),
        Among("tõime", 249, 10),
        Among("tõin", 249, 10),
        Among("tõite", 249, 10),
        Among("viia", -1, 3),
        Among("viiakse", 254, 3),
        Among("viib", -1, 3),
        Among("viid", -1, 3),
        Among("viidi", 257, 3),
        Among("viiks", -1, 3),
        Among("viiksid", 259, 3),
        Among("viiksime", 259, 3),
        Among("viiksin", 259, 3),
        Among("viiksite", 259, 3),
        Among("viima", -1, 3),
        Among("viimata", 264, 3),
        Among("viime", -1, 3),
        Among("viin", -1, 3),
        Among("viisime", -1, 3),
        Among("viisin", -1, 3),
        Among("viisite", -1, 3),
        Among("viite", -1, 3),
        Among("viivad", -1, 3),
        Among("võib", -1, 11),
        Among("võid", -1, 11),
        Among("võida", 274, 11),
        Among("võidakse", 275, 11),
        Among("võidi", 274, 11),
        Among("võiks", -1, 11),
        Among("võiksid", 278, 11),
        Among("võiksime", 278, 11),
        Among("võiksin", 278, 11),
        Among("võiksite", 278, 11),
        Among("võima", -1, 11),
        Among("võimata", 283, 11),
        Among("võime", -1, 11),
        Among("võin", -1, 11),
        Among("võis", -1, 11),
        Among("võite", -1, 11),
        Among("võivad", -1, 11)
    )

    private val g_V1 = charArrayOf(
        17.toChar(), 65.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        8.toChar(), 0.toChar(), 48.toChar(), 8.toChar()
    )

    private val g_RV = charArrayOf(17.toChar(), 65.toChar(), 16.toChar())

    private val g_KI = charArrayOf(
        117.toChar(), 66.toChar(), 6.toChar(), 1.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 128.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 16.toChar()
    )

    private val g_GI = charArrayOf(
        21.toChar(), 123.toChar(), 243.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        8.toChar(), 0.toChar(), 48.toChar(), 8.toChar()
    )

    private var I_p1 = 0

    private fun r_mark_regions(): Boolean {
        I_p1 = limit
        while (true) {
            val v_1 = cursor
            if (in_grouping(g_V1, 97, 252)) {
                cursor = v_1
                break
            }
            cursor = v_1
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        while (true) {
            if (out_grouping(g_V1, 97, 252)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        I_p1 = cursor
        return true
    }

    private fun r_emphasis(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_0)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        val v_3 = limit - cursor
        val c = cursor - 4
        if (c < limit_backward) {
            return false
        }
        cursor = c
        cursor = limit - v_3
        when (among_var) {
            1 -> {
                val v_4 = limit - cursor
                if (!in_grouping_b(g_GI, 97, 252)) {
                    return false
                }
                cursor = limit - v_4
                val v_5 = limit - cursor
                if (r_LONGV()) {
                    return false
                }
                cursor = limit - v_5
                slice_del()
            }
            2 -> {
                if (!in_grouping_b(g_KI, 98, 382)) {
                    return false
                }
                slice_del()
            }
        }
        return true
    }

    private fun r_verb(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_1)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> slice_del()
            2 -> slice_from("a")
            3 -> {
                if (!in_grouping_b(g_V1, 97, 252)) {
                    return false
                }
                slice_del()
            }
        }
        return true
    }

    private fun r_LONGV(): Boolean {
        return find_among_b(a_2) != 0
    }

    private fun r_i_plural(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        if (find_among_b(a_3) == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        if (!in_grouping_b(g_RV, 97, 117)) {
            return false
        }
        slice_del()
        return true
    }

    private fun r_special_noun_endings(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_4)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> slice_from("lase")
            2 -> slice_from("mise")
            3 -> slice_from("lise")
        }
        return true
    }

    private fun r_case_ending(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_5)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> {
                val v_3 = limit - cursor
                if (!in_grouping_b(g_RV, 97, 117)) {
                    cursor = limit - v_3
                    if (!r_LONGV()) {
                        return false
                    }
                }
            }
            2 -> {
                val v_4 = limit - cursor
                val c = cursor - 4
                if (c < limit_backward) {
                    return false
                }
                cursor = c
                cursor = limit - v_4
            }
        }
        slice_del()
        return true
    }

    private fun r_plural_three_first_cases(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        var among_var = find_among_b(a_7)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> slice_from("iku")
            2 -> {
                val v_3 = limit - cursor
                if (r_LONGV()) {
                    return false
                }
                cursor = limit - v_3
                slice_del()
            }
            3 -> {
                val v_4 = limit - cursor
                val v_5 = limit - cursor
                val c = cursor - 4
                if (c >= limit_backward) {
                    cursor = c
                    cursor = limit - v_5
                    among_var = find_among_b(a_6)
                    when (among_var) {
                        1 -> slice_from("e")
                        2 -> slice_del()
                    }
                } else {
                    cursor = limit - v_4
                    slice_from("t")
                }
            }
            4 -> {
                val v_6 = limit - cursor
                if (!in_grouping_b(g_RV, 97, 117)) {
                    cursor = limit - v_6
                    if (!r_LONGV()) {
                        return false
                    }
                }
                slice_del()
            }
        }
        return true
    }

    private fun r_nu(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        if (find_among_b(a_8) == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        slice_del()
        return true
    }

    private fun r_undouble_kpt(): Boolean {
        if (!in_grouping_b(g_V1, 97, 252)) {
            return false
        }
        if (I_p1 > cursor) {
            return false
        }
        ket = cursor
        val among_var = find_among_b(a_9)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        when (among_var) {
            1 -> slice_from("k")
            2 -> slice_from("p")
            3 -> slice_from("t")
        }
        return true
    }

    private fun r_degrees(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_10)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> {
                if (!in_grouping_b(g_RV, 97, 117)) {
                    return false
                }
                slice_del()
            }
            2 -> slice_del()
        }
        return true
    }

    private fun r_substantive(): Boolean {
        var v_1 = limit - cursor
        r_special_noun_endings()
        cursor = limit - v_1
        v_1 = limit - cursor
        r_case_ending()
        cursor = limit - v_1
        v_1 = limit - cursor
        r_plural_three_first_cases()
        cursor = limit - v_1
        v_1 = limit - cursor
        r_degrees()
        cursor = limit - v_1
        v_1 = limit - cursor
        r_i_plural()
        cursor = limit - v_1
        v_1 = limit - cursor
        r_nu()
        cursor = limit - v_1
        return true
    }

    private fun r_verb_exceptions(): Boolean {
        bra = cursor
        val among_var = find_among(a_11)
        if (among_var == 0) {
            return false
        }
        ket = cursor
        if (cursor < limit) {
            return false
        }
        when (among_var) {
            1 -> slice_from("joo")
            2 -> slice_from("saa")
            3 -> slice_from("viima")
            4 -> slice_from("keesi")
            5 -> slice_from("löö")
            6 -> slice_from("lõi")
            7 -> slice_from("loo")
            8 -> slice_from("käisi")
            9 -> slice_from("söö")
            10 -> slice_from("too")
            11 -> slice_from("võisi")
            12 -> slice_from("jääma")
            13 -> slice_from("müüsi")
            14 -> slice_from("luge")
            15 -> slice_from("põde")
            16 -> slice_from("ladu")
            17 -> slice_from("tegi")
            18 -> slice_from("nägi")
        }
        return true
    }

    override fun stem(): Boolean {
        run {
            val v_1 = cursor
            if (r_verb_exceptions()) {
                return false
            }
            cursor = v_1
        }
        val v_2 = cursor
        r_mark_regions()
        cursor = v_2
        limit_backward = cursor
        cursor = limit
        var v_3 = limit - cursor
        r_emphasis()
        cursor = limit - v_3
        v_3 = limit - cursor
        run {
            val v_5 = limit - cursor
            if (r_verb()) {
                return@run
            }
            cursor = limit - v_5
            r_substantive()
        }
        cursor = limit - v_3
        val v_6 = limit - cursor
        r_undouble_kpt()
        cursor = limit - v_6
        cursor = limit_backward
        return true
    }

    override fun equals(other: Any?): Boolean {
        return other is EstonianStemmer
    }

    override fun hashCode(): Int {
        return EstonianStemmer::class.qualifiedName!!.hashCode()
    }
}
