// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class FinnishStemmer : SnowballStemmer() {

  private val a_0 = arrayOf(
    Among("pa", -1, 1),
    Among("sti", -1, 2),
    Among("kaan", -1, 1),
    Among("han", -1, 1),
    Among("kin", -1, 1),
    Among("h\u00E4n", -1, 1),
    Among("k\u00E4\u00E4n", -1, 1),
    Among("ko", -1, 1),
    Among("p\u00E4", -1, 1),
    Among("k\u00F6", -1, 1)
    )

  private val a_1 = arrayOf(
    Among("lla", -1, -1),
    Among("na", -1, -1),
    Among("ssa", -1, -1),
    Among("ta", -1, -1),
    Among("lta", 3, -1),
    Among("sta", 3, -1)
    )

  private val a_2 = arrayOf(
    Among("ll\u00E4", -1, -1),
    Among("n\u00E4", -1, -1),
    Among("ss\u00E4", -1, -1),
    Among("t\u00E4", -1, -1),
    Among("lt\u00E4", 3, -1),
    Among("st\u00E4", 3, -1)
    )

  private val a_3 = arrayOf(Among("lle", -1, -1), Among("ine", -1, -1))

  private val a_4 = arrayOf(
    Among("nsa", -1, 3),
    Among("mme", -1, 3),
    Among("nne", -1, 3),
    Among("ni", -1, 2),
    Among("si", -1, 1),
    Among("an", -1, 4),
    Among("en", -1, 6),
    Among("\u00E4n", -1, 5),
    Among("ns\u00E4", -1, 3)
    )

  private val a_5 = arrayOf(
    Among("aa", -1, -1),
    Among("ee", -1, -1),
    Among("ii", -1, -1),
    Among("oo", -1, -1),
    Among("uu", -1, -1),
    Among("\u00E4\u00E4", -1, -1),
    Among("\u00F6\u00F6", -1, -1)
    )

  private val a_6 = arrayOf(
    Among("a", -1, 8),
    Among("lla", 0, -1),
    Among("na", 0, -1),
    Among("ssa", 0, -1),
    Among("ta", 0, -1),
    Among("lta", 4, -1),
    Among("sta", 4, -1),
    Among("tta", 4, 2),
    Among("lle", -1, -1),
    Among("ine", -1, -1),
    Among("ksi", -1, -1),
    Among("n", -1, 7),
    Among("han", 11, 1),
    Among("den", 11, 9),
    Among("seen", 11, 10),
    Among("hen", 11, 2),
    Among("tten", 11, 9),
    Among("hin", 11, 3),
    Among("siin", 11, 9),
    Among("hon", 11, 4),
    Among("h\u00E4n", 11, 5),
    Among("h\u00F6n", 11, 6),
    Among("\u00E4", -1, 8),
    Among("ll\u00E4", 22, -1),
    Among("n\u00E4", 22, -1),
    Among("ss\u00E4", 22, -1),
    Among("t\u00E4", 22, -1),
    Among("lt\u00E4", 26, -1),
    Among("st\u00E4", 26, -1),
    Among("tt\u00E4", 26, 2)
    )

  private val a_7 = arrayOf(
    Among("eja", -1, -1),
    Among("mma", -1, 1),
    Among("imma", 1, -1),
    Among("mpa", -1, 1),
    Among("impa", 3, -1),
    Among("mmi", -1, 1),
    Among("immi", 5, -1),
    Among("mpi", -1, 1),
    Among("impi", 7, -1),
    Among("ej\u00E4", -1, -1),
    Among("mm\u00E4", -1, 1),
    Among("imm\u00E4", 10, -1),
    Among("mp\u00E4", -1, 1),
    Among("imp\u00E4", 12, -1)
    )

  private val a_8 = arrayOf(Among("i", -1, -1), Among("j", -1, -1))

  private val a_9 = arrayOf(Among("mma", -1, 1), Among("imma", 0, -1))

  private val g_AEI = charArrayOf(17.toChar(), 1.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 8.toChar())

  private val g_C = charArrayOf(119.toChar(), 223.toChar(), 119.toChar(), 1.toChar())

  private val g_V1 = charArrayOf(17.toChar(), 65.toChar(), 16.toChar(), 1.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 8.toChar(), 0.toChar(), 32.toChar())

  private val g_V2 = charArrayOf(17.toChar(), 65.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 8.toChar(), 0.toChar(), 32.toChar())

  private val g_particle_end = charArrayOf(17.toChar(), 97.toChar(), 24.toChar(), 1.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 8.toChar(), 0.toChar(), 32.toChar())

  private var B_ending_removed = false
  private val S_x = StringBuilder()
  private var I_p2 = 0
  private var I_p1 = 0

  private fun r_mark_regions(): Boolean {
    I_p1 = limit
    I_p2 = limit
    golab0@ while (true) {
      var v_1 = cursor
      run lab1@ {
        if (!in_grouping(g_V1, 97, 246)) {
          return@lab1
        }
        cursor = v_1
        break@golab0
      }
      cursor = v_1
      if (cursor >= limit) {
        return false
      }
      cursor++
    }
    golab2@ while (true) {
      run lab3@ {
        if (!out_grouping(g_V1, 97, 246)) {
          return@lab3
        }
        break@golab2
      }
      if (cursor >= limit) {
        return false
      }
      cursor++
    }
    I_p1 = cursor
    golab4@ while (true) {
      var v_3 = cursor
      run lab5@ {
        if (!in_grouping(g_V1, 97, 246)) {
          return@lab5
        }
        cursor = v_3
        break@golab4
      }
      cursor = v_3
      if (cursor >= limit) {
        return false
      }
      cursor++
    }
    golab6@ while (true) {
      run lab7@ {
        if (!out_grouping(g_V1, 97, 246)) {
          return@lab7
        }
        break@golab6
      }
      if (cursor >= limit) {
        return false
      }
      cursor++
    }
    I_p2 = cursor
    return true
  }

  private fun r_R2(): Boolean {
    return I_p2 <= cursor
  }

  private fun r_particle_etc(): Boolean {
    var among_var: Int
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    ket = cursor
    among_var = find_among_b(a_0)
    if (among_var == 0) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    limit_backward = v_2
    when (among_var) {
      1 -> {
        if (!in_grouping_b(g_particle_end, 97, 246)) {
          return false
        }
        }
      2 -> {
        if (!r_R2()) {
          return false
        }
        }
    }
    slice_del()
    return true
  }

  private fun r_possessive(): Boolean {
    var among_var: Int
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    ket = cursor
    among_var = find_among_b(a_4)
    if (among_var == 0) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    limit_backward = v_2
    when (among_var) {
      1 -> {
        var v_3 = limit - cursor
        if (eq_s_b("k")) {
          return false
        }
        cursor = limit - v_3
        slice_del()
        }
      2 -> {
        slice_del()
        ket = cursor
        if (!eq_s_b("kse")) {
          return false
        }
        bra = cursor
        slice_from("ksi")
        }
      3 -> {
        slice_del()
        }
      4 -> {
        if (find_among_b(a_1) == 0) {
          return false
        }
        slice_del()
        }
      5 -> {
        if (find_among_b(a_2) == 0) {
          return false
        }
        slice_del()
        }
      6 -> {
        if (find_among_b(a_3) == 0) {
          return false
        }
        slice_del()
        }
    }
    return true
  }

  private fun r_LONG(): Boolean {
    if (find_among_b(a_5) == 0) {
      return false
    }
    return true
  }

  private fun r_VI(): Boolean {
    if (!eq_s_b("i")) {
      return false
    }
    if (!in_grouping_b(g_V2, 97, 246)) {
      return false
    }
    return true
  }

  private fun r_case_ending(): Boolean {
    var among_var: Int
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    ket = cursor
    among_var = find_among_b(a_6)
    if (among_var == 0) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    limit_backward = v_2
    when (among_var) {
      1 -> {
        if (!eq_s_b("a")) {
          return false
        }
        }
      2 -> {
        if (!eq_s_b("e")) {
          return false
        }
        }
      3 -> {
        if (!eq_s_b("i")) {
          return false
        }
        }
      4 -> {
        if (!eq_s_b("o")) {
          return false
        }
        }
      5 -> {
        if (!eq_s_b("\u00E4")) {
          return false
        }
        }
      6 -> {
        if (!eq_s_b("\u00F6")) {
          return false
        }
        }
      7 -> {
        var v_3 = limit - cursor
        run lab0@ {
          var v_4 = limit - cursor
          run lab1@ {
            var v_5 = limit - cursor
            run lab2@ {
              if (!r_LONG()) {
                return@lab2
              }
              return@lab1
            }
            cursor = limit - v_5
            if (!eq_s_b("ie")) {
              cursor = limit - v_3
              return@lab0
            }
          }
          cursor = limit - v_4
          if (cursor <= limit_backward) {
            cursor = limit - v_3
            return@lab0
          }
          cursor--
          bra = cursor
        }
        }
      8 -> {
        if (!in_grouping_b(g_V1, 97, 246)) {
          return false
        }
        if (!in_grouping_b(g_C, 98, 122)) {
          return false
        }
        }
      9 -> {
        if (!r_VI()) {
          return false
        }
        }
      10 -> {
        if (!r_LONG()) {
          return false
        }
        }
    }
    slice_del()
    B_ending_removed = true
    return true
  }

  private fun r_other_endings(): Boolean {
    var among_var: Int
    if (cursor < I_p2) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p2
    ket = cursor
    among_var = find_among_b(a_7)
    if (among_var == 0) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    limit_backward = v_2
    when (among_var) {
      1 -> {
        var v_3 = limit - cursor
        if (eq_s_b("po")) {
          return false
        }
        cursor = limit - v_3
        }
    }
    slice_del()
    return true
  }

  private fun r_i_plural(): Boolean {
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    ket = cursor
    if (find_among_b(a_8) == 0) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    limit_backward = v_2
    slice_del()
    return true
  }

  private fun r_t_plural(): Boolean {
    var among_var: Int
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    ket = cursor
    if (!eq_s_b("t")) {
      limit_backward = v_2
      return false
    }
    bra = cursor
    var v_3 = limit - cursor
    if (!in_grouping_b(g_V1, 97, 246)) {
      limit_backward = v_2
      return false
    }
    cursor = limit - v_3
    slice_del()
    limit_backward = v_2
    if (cursor < I_p2) {
      return false
    }
    var v_5 = limit_backward
    limit_backward = I_p2
    ket = cursor
    among_var = find_among_b(a_9)
    if (among_var == 0) {
      limit_backward = v_5
      return false
    }
    bra = cursor
    limit_backward = v_5
    when (among_var) {
      1 -> {
        var v_6 = limit - cursor
        if (eq_s_b("po")) {
          return false
        }
        cursor = limit - v_6
        }
    }
    slice_del()
    return true
  }

  private fun r_tidy(): Boolean {
    if (cursor < I_p1) {
      return false
    }
    var v_2 = limit_backward
    limit_backward = I_p1
    var v_3 = limit - cursor
    run lab0@ {
      var v_4 = limit - cursor
      if (!r_LONG()) {
        return@lab0
      }
      cursor = limit - v_4
      ket = cursor
      if (cursor <= limit_backward) {
        return@lab0
      }
      cursor--
      bra = cursor
      slice_del()
    }
    cursor = limit - v_3
    var v_5 = limit - cursor
    run lab1@ {
      ket = cursor
      if (!in_grouping_b(g_AEI, 97, 228)) {
        return@lab1
      }
      bra = cursor
      if (!in_grouping_b(g_C, 98, 122)) {
        return@lab1
      }
      slice_del()
    }
    cursor = limit - v_5
    var v_6 = limit - cursor
    run lab2@ {
      ket = cursor
      if (!eq_s_b("j")) {
        return@lab2
      }
      bra = cursor
      run lab3@ {
        var v_7 = limit - cursor
        run lab4@ {
          if (!eq_s_b("o")) {
            return@lab4
          }
          return@lab3
        }
        cursor = limit - v_7
        if (!eq_s_b("u")) {
          return@lab2
        }
      }
      slice_del()
    }
    cursor = limit - v_6
    var v_8 = limit - cursor
    run lab5@ {
      ket = cursor
      if (!eq_s_b("o")) {
        return@lab5
      }
      bra = cursor
      if (!eq_s_b("j")) {
        return@lab5
      }
      slice_del()
    }
    cursor = limit - v_8
    limit_backward = v_2
    golab6@ while (true) {
      var v_9 = limit - cursor
      run lab7@ {
        if (!out_grouping_b(g_V1, 97, 246)) {
          return@lab7
        }
        cursor = limit - v_9
        break@golab6
      }
      cursor = limit - v_9
      if (cursor <= limit_backward) {
        return false
      }
      cursor--
    }
    ket = cursor
    if (!in_grouping_b(g_C, 98, 122)) {
      return false
    }
    bra = cursor
    slice_to(S_x)
    if (!eq_s_b(S_x)) {
      return false
    }
    slice_del()
    return true
  }

  override fun stem(): Boolean {
    var v_1 = cursor
    r_mark_regions()
    cursor = v_1
    B_ending_removed = false
    limit_backward = cursor
    cursor = limit
    var v_2 = limit - cursor
    r_particle_etc()
    cursor = limit - v_2
    var v_3 = limit - cursor
    r_possessive()
    cursor = limit - v_3
    var v_4 = limit - cursor
    r_case_ending()
    cursor = limit - v_4
    var v_5 = limit - cursor
    r_other_endings()
    cursor = limit - v_5
    run lab0@ {
      run lab1@ {
        if (!B_ending_removed) {
          return@lab1
        }
        var v_7 = limit - cursor
        r_i_plural()
        cursor = limit - v_7
        return@lab0
      }
      var v_8 = limit - cursor
      r_t_plural()
      cursor = limit - v_8
    }
    var v_9 = limit - cursor
    r_tidy()
    cursor = limit - v_9
    cursor = limit_backward
    return true
  }

  override fun equals(o: Any?): Boolean {
    return o is FinnishStemmer
  }

  override fun hashCode(): Int {
    return "org.tartarus.snowball.ext.FinnishStemmer".hashCode()
  }
}
