// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class IrishStemmer : SnowballStemmer() {

  private val a_0 = arrayOf(
    Among("b'", -1, 1),
    Among("bh", -1, 4),
    Among("bhf", 1, 2),
    Among("bp", -1, 8),
    Among("ch", -1, 5),
    Among("d'", -1, 1),
    Among("d'fh", 5, 2),
    Among("dh", -1, 6),
    Among("dt", -1, 9),
    Among("fh", -1, 2),
    Among("gc", -1, 5),
    Among("gh", -1, 7),
    Among("h-", -1, 1),
    Among("m'", -1, 1),
    Among("mb", -1, 4),
    Among("mh", -1, 10),
    Among("n-", -1, 1),
    Among("nd", -1, 6),
    Among("ng", -1, 7),
    Among("ph", -1, 8),
    Among("sh", -1, 3),
    Among("t-", -1, 1),
    Among("th", -1, 9),
    Among("ts", -1, 3)
    )

  private val a_1 = arrayOf(
    Among("\u00EDochta", -1, 1),
    Among("a\u00EDochta", 0, 1),
    Among("ire", -1, 2),
    Among("aire", 2, 2),
    Among("abh", -1, 1),
    Among("eabh", 4, 1),
    Among("ibh", -1, 1),
    Among("aibh", 6, 1),
    Among("amh", -1, 1),
    Among("eamh", 8, 1),
    Among("imh", -1, 1),
    Among("aimh", 10, 1),
    Among("\u00EDocht", -1, 1),
    Among("a\u00EDocht", 12, 1),
    Among("ir\u00ED", -1, 2),
    Among("air\u00ED", 14, 2)
    )

  private val a_2 = arrayOf(
    Among("\u00F3ideacha", -1, 6),
    Among("patacha", -1, 5),
    Among("achta", -1, 1),
    Among("arcachta", 2, 2),
    Among("eachta", 2, 1),
    Among("grafa\u00EDochta", -1, 4),
    Among("paite", -1, 5),
    Among("ach", -1, 1),
    Among("each", 7, 1),
    Among("\u00F3ideach", 8, 6),
    Among("gineach", 8, 3),
    Among("patach", 7, 5),
    Among("grafa\u00EDoch", -1, 4),
    Among("pataigh", -1, 5),
    Among("\u00F3idigh", -1, 6),
    Among("acht\u00FAil", -1, 1),
    Among("eacht\u00FAil", 15, 1),
    Among("gineas", -1, 3),
    Among("ginis", -1, 3),
    Among("acht", -1, 1),
    Among("arcacht", 19, 2),
    Among("eacht", 19, 1),
    Among("grafa\u00EDocht", -1, 4),
    Among("arcachta\u00ED", -1, 2),
    Among("grafa\u00EDochta\u00ED", -1, 4)
    )

  private val a_3 = arrayOf(
    Among("imid", -1, 1),
    Among("aimid", 0, 1),
    Among("\u00EDmid", -1, 1),
    Among("a\u00EDmid", 2, 1),
    Among("adh", -1, 2),
    Among("eadh", 4, 2),
    Among("faidh", -1, 1),
    Among("fidh", -1, 1),
    Among("\u00E1il", -1, 2),
    Among("ain", -1, 2),
    Among("tear", -1, 2),
    Among("tar", -1, 2)
    )

  private val g_v = charArrayOf(17.toChar(), 65.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 1.toChar(), 17.toChar(), 4.toChar(), 2.toChar())

  private var I_p2 = 0
  private var I_p1 = 0
  private var I_pV = 0

  private fun r_mark_regions(): Boolean {
    I_pV = limit
    I_p1 = limit
    I_p2 = limit
    var v_1 = cursor
    run lab0@ {
      golab1@ while (true) {
        run lab2@ {
          if (!in_grouping(g_v, 97, 250)) {
            return@lab2
          }
          break@golab1
        }
        if (cursor >= limit) {
          return@lab0
        }
        cursor++
      }
      I_pV = cursor
      golab3@ while (true) {
        run lab4@ {
          if (!out_grouping(g_v, 97, 250)) {
            return@lab4
          }
          break@golab3
        }
        if (cursor >= limit) {
          return@lab0
        }
        cursor++
      }
      I_p1 = cursor
      golab5@ while (true) {
        run lab6@ {
          if (!in_grouping(g_v, 97, 250)) {
            return@lab6
          }
          break@golab5
        }
        if (cursor >= limit) {
          return@lab0
        }
        cursor++
      }
      golab7@ while (true) {
        run lab8@ {
          if (!out_grouping(g_v, 97, 250)) {
            return@lab8
          }
          break@golab7
        }
        if (cursor >= limit) {
          return@lab0
        }
        cursor++
      }
      I_p2 = cursor
    }
    cursor = v_1
    return true
  }

  private fun r_initial_morph(): Boolean {
    var among_var: Int
    bra = cursor
    among_var = find_among(a_0)
    if (among_var == 0) {
      return false
    }
    ket = cursor
    when (among_var) {
      1 -> {
        slice_del()
        }
      2 -> {
        slice_from("f")
        }
      3 -> {
        slice_from("s")
        }
      4 -> {
        slice_from("b")
        }
      5 -> {
        slice_from("c")
        }
      6 -> {
        slice_from("d")
        }
      7 -> {
        slice_from("g")
        }
      8 -> {
        slice_from("p")
        }
      9 -> {
        slice_from("t")
        }
      10 -> {
        slice_from("m")
        }
    }
    return true
  }

  private fun r_RV(): Boolean {
    return I_pV <= cursor
  }

  private fun r_R1(): Boolean {
    return I_p1 <= cursor
  }

  private fun r_R2(): Boolean {
    return I_p2 <= cursor
  }

  private fun r_noun_sfx(): Boolean {
    var among_var: Int
    ket = cursor
    among_var = find_among_b(a_1)
    if (among_var == 0) {
      return false
    }
    bra = cursor
    when (among_var) {
      1 -> {
        if (!r_R1()) {
          return false
        }
        slice_del()
        }
      2 -> {
        if (!r_R2()) {
          return false
        }
        slice_del()
        }
    }
    return true
  }

  private fun r_deriv(): Boolean {
    var among_var: Int
    ket = cursor
    among_var = find_among_b(a_2)
    if (among_var == 0) {
      return false
    }
    bra = cursor
    when (among_var) {
      1 -> {
        if (!r_R2()) {
          return false
        }
        slice_del()
        }
      2 -> {
        slice_from("arc")
        }
      3 -> {
        slice_from("gin")
        }
      4 -> {
        slice_from("graf")
        }
      5 -> {
        slice_from("paite")
        }
      6 -> {
        slice_from("\u00F3id")
        }
    }
    return true
  }

  private fun r_verb_sfx(): Boolean {
    var among_var: Int
    ket = cursor
    among_var = find_among_b(a_3)
    if (among_var == 0) {
      return false
    }
    bra = cursor
    when (among_var) {
      1 -> {
        if (!r_RV()) {
          return false
        }
        slice_del()
        }
      2 -> {
        if (!r_R1()) {
          return false
        }
        slice_del()
        }
    }
    return true
  }

  override fun stem(): Boolean {
    var v_1 = cursor
    r_initial_morph()
    cursor = v_1
    r_mark_regions()
    limit_backward = cursor
    cursor = limit
    var v_3 = limit - cursor
    r_noun_sfx()
    cursor = limit - v_3
    var v_4 = limit - cursor
    r_deriv()
    cursor = limit - v_4
    var v_5 = limit - cursor
    r_verb_sfx()
    cursor = limit - v_5
    cursor = limit_backward
    return true
  }

  override fun equals(o: Any?): Boolean {
    return o is IrishStemmer
  }

  override fun hashCode(): Int {
    return "org.tartarus.snowball.ext.IrishStemmer".hashCode()
  }
}
