// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class NorwegianStemmer : SnowballStemmer() {
    private val a_0 = arrayOf(
        Among("a", -1, 1),
        Among("e", -1, 1),
        Among("ede", 1, 1),
        Among("ande", 1, 1),
        Among("ende", 1, 1),
        Among("ane", 1, 1),
        Among("ene", 1, 1),
        Among("hetene", 6, 1),
        Among("erte", 1, 3),
        Among("en", -1, 1),
        Among("heten", 9, 1),
        Among("ar", -1, 1),
        Among("er", -1, 1),
        Among("heter", 12, 1),
        Among("s", -1, 2),
        Among("as", 14, 1),
        Among("es", 14, 1),
        Among("edes", 16, 1),
        Among("endes", 16, 1),
        Among("enes", 16, 1),
        Among("hetenes", 19, 1),
        Among("ens", 14, 1),
        Among("hetens", 21, 1),
        Among("ers", 14, 1),
        Among("ets", 14, 1),
        Among("et", -1, 1),
        Among("het", 25, 1),
        Among("ert", -1, 3),
        Among("ast", -1, 1)
    )

    private val a_1 = arrayOf(
        Among("dt", -1, -1),
        Among("vt", -1, -1)
    )

    private val a_2 = arrayOf(
        Among("leg", -1, 1),
        Among("eleg", 0, 1),
        Among("ig", -1, 1),
        Among("eig", 2, 1),
        Among("lig", 2, 1),
        Among("elig", 4, 1),
        Among("els", -1, 1),
        Among("lov", -1, 1),
        Among("elov", 7, 1),
        Among("slov", 7, 1),
        Among("hetslov", 9, 1)
    )

    private val g_v = charArrayOf(
        17.toChar(),
        65.toChar(),
        16.toChar(),
        1.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        0.toChar(),
        48.toChar(),
        0.toChar(),
        128.toChar()
    )

    private val g_s_ending = charArrayOf(
        119.toChar(),
        125.toChar(),
        149.toChar(),
        1.toChar()
    )

    private var I_x = 0
    private var I_p1 = 0

    private fun r_mark_regions(): Boolean {
        I_p1 = limit
        val v_1 = cursor
        val c = cursor + 3
        if (c > limit) {
            return false
        }
        cursor = c
        I_x = cursor
        cursor = v_1
        while (true) {
            if (in_grouping(g_v, 97, 248)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        while (true) {
            if (out_grouping(g_v, 97, 248)) {
                break
            }
            if (cursor >= limit) {
                return false
            }
            cursor++
        }
        I_p1 = cursor
        if (I_p1 < I_x) {
            I_p1 = I_x
        }
        return true
    }

    private fun r_main_suffix(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        val among_var = find_among_b(a_0)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        when (among_var) {
            1 -> slice_del()
            2 -> {
                if (!in_grouping_b(g_s_ending, 98, 122)) {
                    if (!eq_s_b("k")) {
                        return false
                    }
                    if (!out_grouping_b(g_v, 97, 248)) {
                        return false
                    }
                }
                slice_del()
            }
            3 -> slice_from("er")
        }
        return true
    }

    private fun r_consonant_pair(): Boolean {
        val v_1 = limit - cursor
        if (cursor < I_p1) {
            return false
        }
        val v_3 = limit_backward
        limit_backward = I_p1
        ket = cursor
        if (find_among_b(a_1) == 0) {
            limit_backward = v_3
            return false
        }
        bra = cursor
        limit_backward = v_3
        cursor = limit - v_1
        if (cursor <= limit_backward) {
            return false
        }
        cursor--
        bra = cursor
        slice_del()
        return true
    }

    private fun r_other_suffix(): Boolean {
        if (cursor < I_p1) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_p1
        ket = cursor
        if (find_among_b(a_2) == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        limit_backward = v_2
        slice_del()
        return true
    }

    override fun stem(): Boolean {
        val v_1 = cursor
        r_mark_regions()
        cursor = v_1
        limit_backward = cursor
        cursor = limit
        val v_2 = limit - cursor
        r_main_suffix()
        cursor = limit - v_2
        val v_3 = limit - cursor
        r_consonant_pair()
        cursor = limit - v_3
        val v_4 = limit - cursor
        r_other_suffix()
        cursor = limit - v_4
        cursor = limit_backward
        return true
    }

    override fun equals(other: Any?): Boolean {
        return other is NorwegianStemmer
    }

    override fun hashCode(): Int {
        return NorwegianStemmer::class.qualifiedName!!.hashCode()
    }
}
