// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class RomanianStemmer : SnowballStemmer() {
    private val a_0 = arrayOf(Among("\u015F", -1, 1), Among("\u0163", -1, 2))
    private val a_1 = arrayOf(Among("", -1, 3), Among("I", 0, 1), Among("U", 0, 2))
    private val a_2 = arrayOf(
        Among("ea", -1, 3),
        Among("a\u021Bia", -1, 7),
        Among("aua", -1, 2),
        Among("iua", -1, 4),
        Among("a\u021Bie", -1, 7),
        Among("ele", -1, 3),
        Among("ile", -1, 5),
        Among("iile", 6, 4),
        Among("iei", -1, 4),
        Among("atei", -1, 6),
        Among("ii", -1, 4),
        Among("ului", -1, 1),
        Among("ul", -1, 1),
        Among("elor", -1, 3),
        Among("ilor", -1, 4),
        Among("iilor", 14, 4)
    )
    private val a_3 = arrayOf(
        Among("icala", -1, 4),
        Among("iciva", -1, 4),
        Among("ativa", -1, 5),
        Among("itiva", -1, 6),
        Among("icale", -1, 4),
        Among("a\u021Biune", -1, 5),
        Among("i\u021Biune", -1, 6),
        Among("atoare", -1, 5),
        Among("itoare", -1, 6),
        Among("\u0103toare", -1, 5),
        Among("icitate", -1, 4),
        Among("abilitate", -1, 1),
        Among("ibilitate", -1, 2),
        Among("ivitate", -1, 3),
        Among("icive", -1, 4),
        Among("ative", -1, 5),
        Among("itive", -1, 6),
        Among("icali", -1, 4),
        Among("atori", -1, 5),
        Among("icatori", 18, 4),
        Among("itori", -1, 6),
        Among("\u0103tori", -1, 5),
        Among("icitati", -1, 4),
        Among("abilitati", -1, 1),
        Among("ivitati", -1, 3),
        Among("icivi", -1, 4),
        Among("ativi", -1, 5),
        Among("itivi", -1, 6),
        Among("icit\u0103i", -1, 4),
        Among("abilit\u0103i", -1, 1),
        Among("ivit\u0103i", -1, 3),
        Among("icit\u0103\u021Bi", -1, 4),
        Among("abilit\u0103\u021Bi", -1, 1),
        Among("ivit\u0103\u021Bi", -1, 3),
        Among("ical", -1, 4),
        Among("ator", -1, 5),
        Among("icator", 35, 4),
        Among("itor", -1, 6),
        Among("\u0103tor", -1, 5),
        Among("iciv", -1, 4),
        Among("ativ", -1, 5),
        Among("itiv", -1, 6),
        Among("ical\u0103", -1, 4),
        Among("iciv\u0103", -1, 4),
        Among("ativ\u0103", -1, 5),
        Among("itiv\u0103", -1, 6)
    )
    private val a_4 = arrayOf(
        Among("ica", -1, 1),
        Among("abila", -1, 1),
        Among("ibila", -1, 1),
        Among("oasa", -1, 1),
        Among("ata", -1, 1),
        Among("ita", -1, 1),
        Among("anta", -1, 1),
        Among("ista", -1, 3),
        Among("uta", -1, 1),
        Among("iva", -1, 1),
        Among("ic", -1, 1),
        Among("ice", -1, 1),
        Among("abile", -1, 1),
        Among("ibile", -1, 1),
        Among("isme", -1, 3),
        Among("iune", -1, 2),
        Among("oase", -1, 1),
        Among("ate", -1, 1),
        Among("itate", 17, 1),
        Among("ite", -1, 1),
        Among("ante", -1, 1),
        Among("iste", -1, 3),
        Among("ute", -1, 1),
        Among("ive", -1, 1),
        Among("ici", -1, 1),
        Among("abili", -1, 1),
        Among("ibili", -1, 1),
        Among("iuni", -1, 2),
        Among("atori", -1, 1),
        Among("osi", -1, 1),
        Among("ati", -1, 1),
        Among("itati", 30, 1),
        Among("iti", -1, 1),
        Among("anti", -1, 1),
        Among("isti", -1, 3),
        Among("uti", -1, 1),
        Among("i\u0219ti", -1, 3),
        Among("ivi", -1, 1),
        Among("it\u0103i", -1, 1),
        Among("o\u0219i", -1, 1),
        Among("it\u0103\u021Bi", -1, 1),
        Among("abil", -1, 1),
        Among("ibil", -1, 1),
        Among("ism", -1, 3),
        Among("ator", -1, 1),
        Among("os", -1, 1),
        Among("at", -1, 1),
        Among("it", -1, 1),
        Among("ant", -1, 1),
        Among("ist", -1, 3),
        Among("ut", -1, 1),
        Among("iv", -1, 1),
        Among("ic\u0103", -1, 1),
        Among("abil\u0103", -1, 1),
        Among("ibil\u0103", -1, 1),
        Among("oas\u0103", -1, 1),
        Among("at\u0103", -1, 1),
        Among("it\u0103", -1, 1),
        Among("ant\u0103", -1, 1),
        Among("ist\u0103", -1, 3),
        Among("ut\u0103", -1, 1),
        Among("iv\u0103", -1, 1)
    )
    private val a_5 = arrayOf(
        Among("ea", -1, 1),
        Among("ia", -1, 1),
        Among("esc", -1, 1),
        Among("\u0103sc", -1, 1),
        Among("ind", -1, 1),
        Among("\u00E2nd", -1, 1),
        Among("are", -1, 1),
        Among("ere", -1, 1),
        Among("ire", -1, 1),
        Among("\u00E2re", -1, 1),
        Among("se", -1, 2),
        Among("ase", 10, 1),
        Among("sese", 10, 2),
        Among("ise", 10, 1),
        Among("use", 10, 1),
        Among("\u00E2se", 10, 1),
        Among("e\u0219te", -1, 1),
        Among("\u0103\u0219te", -1, 1),
        Among("eze", -1, 1),
        Among("ai", -1, 1),
        Among("eai", 19, 1),
        Among("iai", 19, 1),
        Among("sei", -1, 2),
        Among("e\u0219ti", -1, 1),
        Among("\u0103\u0219ti", -1, 1),
        Among("ui", -1, 1),
        Among("ezi", -1, 1),
        Among("\u00E2i", -1, 1),
        Among("a\u0219i", -1, 1),
        Among("se\u0219i", -1, 2),
        Among("ase\u0219i", 29, 1),
        Among("sese\u0219i", 29, 2),
        Among("ise\u0219i", 29, 1),
        Among("use\u0219i", 29, 1),
        Among("\u00E2se\u0219i", 29, 1),
        Among("i\u0219i", -1, 1),
        Among("u\u0219i", -1, 1),
        Among("\u00E2\u0219i", -1, 1),
        Among("a\u021Bi", -1, 2),
        Among("ea\u021Bi", 38, 1),
        Among("ia\u021Bi", 38, 1),
        Among("e\u021Bi", -1, 2),
        Among("i\u021Bi", -1, 2),
        Among("\u00E2\u021Bi", -1, 2),
        Among("ar\u0103\u021Bi", -1, 1),
        Among("ser\u0103\u021Bi", -1, 2),
        Among("aser\u0103\u021Bi", 45, 1),
        Among("seser\u0103\u021Bi", 45, 2),
        Among("iser\u0103\u021Bi", 45, 1),
        Among("user\u0103\u021Bi", 45, 1),
        Among("\u00E2ser\u0103\u021Bi", 45, 1),
        Among("ir\u0103\u021Bi", -1, 1),
        Among("ur\u0103\u021Bi", -1, 1),
        Among("\u00E2r\u0103\u021Bi", -1, 1),
        Among("am", -1, 1),
        Among("eam", 54, 1),
        Among("iam", 54, 1),
        Among("em", -1, 2),
        Among("asem", 57, 1),
        Among("sesem", 57, 2),
        Among("isem", 57, 1),
        Among("usem", 57, 1),
        Among("\u00E2sem", 57, 1),
        Among("im", -1, 2),
        Among("\u00E2m", -1, 2),
        Among("\u0103m", -1, 2),
        Among("ar\u0103m", 65, 1),
        Among("ser\u0103m", 65, 2),
        Among("aser\u0103m", 67, 1),
        Among("seser\u0103m", 67, 2),
        Among("iser\u0103m", 67, 1),
        Among("user\u0103m", 67, 1),
        Among("\u00E2ser\u0103m", 67, 1),
        Among("ir\u0103m", 65, 1),
        Among("ur\u0103m", 65, 1),
        Among("\u00E2r\u0103m", 65, 1),
        Among("au", -1, 1),
        Among("eau", 76, 1),
        Among("iau", 76, 1),
        Among("indu", -1, 1),
        Among("\u00E2ndu", -1, 1),
        Among("ez", -1, 1),
        Among("easc\u0103", -1, 1),
        Among("ar\u0103", -1, 1),
        Among("ser\u0103", -1, 2),
        Among("aser\u0103", 84, 1),
        Among("seser\u0103", 84, 2),
        Among("iser\u0103", 84, 1),
        Among("user\u0103", 84, 1),
        Among("\u00E2ser\u0103", 84, 1),
        Among("ir\u0103", -1, 1),
        Among("ur\u0103", -1, 1),
        Among("\u00E2r\u0103", -1, 1),
        Among("eaz\u0103", -1, 1)
    )
    private val a_6 = arrayOf(
        Among("a", -1, 1),
        Among("e", -1, 1),
        Among("ie", 1, 1),
        Among("i", -1, 1),
        Among("\u0103", -1, 1)
    )

    private val g_v = charArrayOf(
        17.toChar(), 65.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(),
        0.toChar(), 0.toChar(), 2.toChar(), 32.toChar(), 0.toChar(), 0.toChar(), 4.toChar()
    )

    private var B_standard_suffix_removed = false
    private var I_p2 = 0
    private var I_p1 = 0
    private var I_pV = 0

    private fun r_norm(): Boolean {
        var among_var: Int
        val v_1 = cursor
        run {
            while (true) {
                val v_2 = cursor
                run {
                    while (true) {
                        val v_3 = cursor
                        run {
                            bra = cursor
                            among_var = find_among(a_0)
                            if (among_var == 0) {
                                return@run
                            }
                            ket = cursor
                            when (among_var) {
                                1 -> slice_from("\u0219")
                                2 -> slice_from("\u021B")
                            }
                            cursor = v_3
                            return@run
                        }
                        cursor = v_3
                        if (cursor >= limit) {
                            return@run
                        }
                        cursor++
                    }
                }
                cursor = v_2
                break
            }
        }
        cursor = v_1
        return true
    }

    private fun r_prelude(): Boolean {
        while (true) {
            val v_1 = cursor
            run {
                while (true) {
                    val v_2 = cursor
                    run {
                        if (!in_grouping(g_v, 97, 259)) {
                            return@run
                        }
                        bra = cursor
                        run {
                            val v_3 = cursor
                            run {
                                if (!eq_s("u")) {
                                    return@run
                                }
                                ket = cursor
                                if (!in_grouping(g_v, 97, 259)) {
                                    return@run
                                }
                                slice_from("U")
                                return@run
                            }
                            cursor = v_3
                            if (!eq_s("i")) {
                                return@run
                            }
                            ket = cursor
                            if (!in_grouping(g_v, 97, 259)) {
                                return@run
                            }
                            slice_from("I")
                        }
                        cursor = v_2
                        return@run
                    }
                    cursor = v_2
                    if (cursor >= limit) {
                        return@run
                    }
                    cursor++
                }
            }
            cursor = v_1
            break
        }
        return true
    }

    private fun r_mark_regions(): Boolean {
        I_pV = limit
        I_p1 = limit
        I_p2 = limit
        val v_1 = cursor
        run {
            run {
                val v_2 = cursor
                run {
                    if (!in_grouping(g_v, 97, 259)) {
                        return@run
                    }
                    run {
                        val v_3 = cursor
                        run {
                            if (!out_grouping(g_v, 97, 259)) {
                                return@run
                            }
                            while (true) {
                                if (in_grouping(g_v, 97, 259)) {
                                    break
                                }
                                if (cursor >= limit) {
                                    return@run
                                }
                                cursor++
                            }
                            return@run
                        }
                        cursor = v_3
                        if (!in_grouping(g_v, 97, 259)) {
                            return@run
                        }
                        while (true) {
                            if (out_grouping(g_v, 97, 259)) {
                                break
                            }
                            if (cursor >= limit) {
                                return@run
                            }
                            cursor++
                        }
                    }
                    return@run
                }
                cursor = v_2
                if (!out_grouping(g_v, 97, 259)) {
                    return@run
                }
                run {
                    val v_6 = cursor
                    run {
                        if (!out_grouping(g_v, 97, 259)) {
                            return@run
                        }
                        while (true) {
                            if (in_grouping(g_v, 97, 259)) {
                                break
                            }
                            if (cursor >= limit) {
                                return@run
                            }
                            cursor++
                        }
                        return@run
                    }
                    cursor = v_6
                    if (!in_grouping(g_v, 97, 259)) {
                        return@run
                    }
                    if (cursor >= limit) {
                        return@run
                    }
                    cursor++
                }
            }
            I_pV = cursor
        }
        cursor = v_1
        val v_8 = cursor
        run {
            while (true) {
                if (in_grouping(g_v, 97, 259)) {
                    break
                }
                if (cursor >= limit) {
                    return@run
                }
                cursor++
            }
            while (true) {
                if (out_grouping(g_v, 97, 259)) {
                    break
                }
                if (cursor >= limit) {
                    return@run
                }
                cursor++
            }
            I_p1 = cursor
            while (true) {
                if (in_grouping(g_v, 97, 259)) {
                    break
                }
                if (cursor >= limit) {
                    return@run
                }
                cursor++
            }
            while (true) {
                if (out_grouping(g_v, 97, 259)) {
                    break
                }
                if (cursor >= limit) {
                    return@run
                }
                cursor++
            }
            I_p2 = cursor
        }
        cursor = v_8
        return true
    }

    private fun r_postlude(): Boolean {
        var among_var: Int
        while (true) {
            val v_1 = cursor
            run {
                bra = cursor
                among_var = find_among(a_1)
                ket = cursor
                when (among_var) {
                    1 -> slice_from("i")
                    2 -> slice_from("u")
                    3 -> {
                        if (cursor >= limit) {
                            return@run
                        }
                        cursor++
                    }
                    else -> return@run
                }
                return@run
            }
            cursor = v_1
            break
        }
        return true
    }

    private fun r_RV(): Boolean {
        return I_pV <= cursor
    }

    private fun r_R1(): Boolean {
        return I_p1 <= cursor
    }

    private fun r_R2(): Boolean {
        return I_p2 <= cursor
    }

    private fun r_step_0(): Boolean {
        var among_var: Int
        ket = cursor
        among_var = find_among_b(a_2)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        if (!r_R1()) {
            return false
        }
        when (among_var) {
            1 -> slice_del()
            2 -> slice_from("a")
            3 -> slice_from("e")
            4 -> slice_from("i")
            5 -> {
                val v_1 = limit - cursor
                run {
                    if (!eq_s_b("ab")) {
                        return@run
                    }
                    return false
                }
                cursor = limit - v_1
                slice_from("i")
            }
            6 -> slice_from("at")
            7 -> slice_from("a\u021Bi")
        }
        return true
    }

    private fun r_combo_suffix(): Boolean {
        var among_var: Int
        val v_1 = limit - cursor
        ket = cursor
        among_var = find_among_b(a_3)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        if (!r_R1()) {
            return false
        }
        when (among_var) {
            1 -> slice_from("abil")
            2 -> slice_from("ibil")
            3 -> slice_from("iv")
            4 -> slice_from("ic")
            5 -> slice_from("at")
            6 -> slice_from("it")
        }
        B_standard_suffix_removed = true
        cursor = limit - v_1
        return true
    }

    private fun r_standard_suffix(): Boolean {
        var among_var: Int
        B_standard_suffix_removed = false
        while (true) {
            val v_1 = limit - cursor
            run {
                if (!r_combo_suffix()) {
                    return@run
                }
                return@run
            }
            cursor = limit - v_1
            break
        }
        ket = cursor
        among_var = find_among_b(a_4)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        if (!r_R2()) {
            return false
        }
        when (among_var) {
            1 -> slice_del()
            2 -> {
                if (!eq_s_b("\u021B")) {
                    return false
                }
                bra = cursor
                slice_from("t")
            }
            3 -> slice_from("ist")
        }
        B_standard_suffix_removed = true
        return true
    }

    private fun r_verb_suffix(): Boolean {
        var among_var: Int
        if (cursor < I_pV) {
            return false
        }
        val v_2 = limit_backward
        limit_backward = I_pV
        ket = cursor
        among_var = find_among_b(a_5)
        if (among_var == 0) {
            limit_backward = v_2
            return false
        }
        bra = cursor
        when (among_var) {
            1 -> {
                run {
                    val v_3 = limit - cursor
                    run {
                        if (!out_grouping_b(g_v, 97, 259)) {
                            return@run
                        }
                        return@run
                    }
                    cursor = limit - v_3
                    if (!eq_s_b("u")) {
                        limit_backward = v_2
                        return false
                    }
                }
                slice_del()
            }
            2 -> slice_del()
        }
        limit_backward = v_2
        return true
    }

    private fun r_vowel_suffix(): Boolean {
        ket = cursor
        if (find_among_b(a_6) == 0) {
            return false
        }
        bra = cursor
        if (!r_RV()) {
            return false
        }
        slice_del()
        return true
    }

    override fun stem(): Boolean {
        r_norm()
        val v_2 = cursor
        r_prelude()
        cursor = v_2
        r_mark_regions()
        limit_backward = cursor
        cursor = limit
        val v_4 = limit - cursor
        r_step_0()
        cursor = limit - v_4
        val v_5 = limit - cursor
        r_standard_suffix()
        cursor = limit - v_5
        val v_6 = limit - cursor
        run {
            run {
                val v_7 = limit - cursor
                run {
                    if (!B_standard_suffix_removed) {
                        return@run
                    }
                    return@run
                }
                cursor = limit - v_7
                if (!r_verb_suffix()) {
                    return@run
                }
            }
        }
        cursor = limit - v_6
        val v_8 = limit - cursor
        r_vowel_suffix()
        cursor = limit - v_8
        cursor = limit_backward
        val v_9 = cursor
        r_postlude()
        cursor = v_9
        return true
    }

    override fun equals(other: Any?): Boolean {
        return other is RomanianStemmer
    }

    override fun hashCode(): Int {
        return "org.tartarus.snowball.ext.RomanianStemmer".hashCode()
    }
}
