// Generated by Snowball 2.2.0 - https://snowballstem.org/

package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class TamilStemmer : SnowballStemmer() {
    private val a_0 = arrayOf(
        Among("\u0BB5\u0BC1", -1, 3),
        Among("\u0BB5\u0BC2", -1, 4),
        Among("\u0BB5\u0BCA", -1, 2),
        Among("\u0BB5\u0BCB", -1, 1)
    )

    private val a_1 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B99", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9E", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BA8", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BAE", -1, -1),
        Among("\u0BAF", -1, -1),
        Among("\u0BB5", -1, -1)
    )

    private val a_2 = arrayOf(
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_3 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_4 = arrayOf(
        Among("", -1, 2),
        Among("\u0BC8", 0, 1),
        Among("\u0BCD", 0, 1)
    )

    private val a_5 = arrayOf(
        Among("\u0BA8\u0BCD\u0BA4", -1, 1),
        Among("\u0BAF", -1, 1),
        Among("\u0BB5", -1, 1),
        Among("\u0BA9\u0BC1", -1, 8),
        Among("\u0BC1\u0B95\u0BCD", -1, 7),
        Among("\u0BC1\u0B95\u0BCD\u0B95\u0BCD", -1, 7),
        Among("\u0B9F\u0BCD\u0B95\u0BCD", -1, 3),
        Among("\u0BB1\u0BCD\u0B95\u0BCD", -1, 4),
        Among("\u0B99\u0BCD", -1, 9),
        Among("\u0B9F\u0BCD\u0B9F\u0BCD", -1, 5),
        Among("\u0BA4\u0BCD\u0BA4\u0BCD", -1, 6),
        Among("\u0BA8\u0BCD\u0BA4\u0BCD", -1, 1),
        Among("\u0BA8\u0BCD", -1, 1),
        Among("\u0B9F\u0BCD\u0BAA\u0BCD", -1, 3),
        Among("\u0BAF\u0BCD", -1, 2),
        Among("\u0BA9\u0BCD\u0BB1\u0BCD", -1, 4),
        Among("\u0BB5\u0BCD", -1, 1)
    )

    private val a_6 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9F", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BB1", -1, -1)
    )

    private val a_7 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9F", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BB1", -1, -1)
    )

    private val a_8 = arrayOf(
        Among("\u0B9E", -1, -1),
        Among("\u0BA3", -1, -1),
        Among("\u0BA8", -1, -1),
        Among("\u0BA9", -1, -1),
        Among("\u0BAE", -1, -1),
        Among("\u0BAF", -1, -1),
        Among("\u0BB0", -1, -1),
        Among("\u0BB2", -1, -1),
        Among("\u0BB3", -1, -1),
        Among("\u0BB4", -1, -1),
        Among("\u0BB5", -1, -1)
    )

    private val a_9 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1),
        Among("\u0BCD", -1, -1)
    )

    private val a_10 = arrayOf(
        Among("\u0B85", -1, -1),
        Among("\u0B87", -1, -1),
        Among("\u0B89", -1, -1)
    )

    private val a_11 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B99", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9E", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BA8", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BAE", -1, -1),
        Among("\u0BAF", -1, -1),
        Among("\u0BB5", -1, -1)
    )

    private val a_12 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9F", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BB1", -1, -1)
    )

    private val a_13 = arrayOf(
        Among("\u0B95\u0BB3\u0BCD", -1, 4),
        Among("\u0BC1\u0B99\u0BCD\u0B95\u0BB3\u0BCD", 0, 1),
        Among("\u0B9F\u0BCD\u0B95\u0BB3\u0BCD", 0, 3),
        Among("\u0BB1\u0BCD\u0B95\u0BB3\u0BCD", 0, 2)
    )

    private val a_14 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BCB", -1, -1)
    )

    private val a_15 = arrayOf(
        Among("\u0BAA\u0BBF", -1, -1),
        Among("\u0BB5\u0BBF", -1, -1)
    )

    private val a_16 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_17 = arrayOf(
        Among("\u0BAA\u0B9F\u0BCD\u0B9F", -1, 3),
        Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BA3", -1, 3),
        Among("\u0BA4\u0BBE\u0BA9", -1, 3),
        Among("\u0BAA\u0B9F\u0BBF\u0BA4\u0BBE\u0BA9", 2, 3),
        Among("\u0BC6\u0BA9", -1, 1),
        Among("\u0BBE\u0B95\u0BBF\u0BAF", -1, 1),
        Among("\u0B95\u0BC1\u0BB0\u0BBF\u0BAF", -1, 3),
        Among("\u0BC1\u0B9F\u0BC8\u0BAF", -1, 1),
        Among("\u0BB2\u0BCD\u0BB2", -1, 2),
        Among("\u0BC1\u0BB3\u0BCD\u0BB3", -1, 1),
        Among("\u0BBE\u0B95\u0BBF", -1, 1),
        Among("\u0BAA\u0B9F\u0BBF", -1, 3),
        Among("\u0BBF\u0BA9\u0BCD\u0BB1\u0BBF", -1, 1),
        Among("\u0BAA\u0BB1\u0BCD\u0BB1\u0BBF", -1, 3),
        Among("\u0BAA\u0B9F\u0BC1", -1, 3),
        Among("\u0BB5\u0BBF\u0B9F\u0BC1", -1, 3),
        Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BC1", -1, 3),
        Among("\u0BB5\u0BBF\u0B9F\u0BCD\u0B9F\u0BC1", -1, 3),
        Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BA4\u0BC1", -1, 3),
        Among("\u0BC6\u0BA9\u0BCD\u0BB1\u0BC1", -1, 1),
        Among("\u0BC1\u0B9F\u0BC8", -1, 1),
        Among("\u0BBF\u0BB2\u0BCD\u0BB2\u0BC8", -1, 1),
        Among("\u0BC1\u0B9F\u0BA9\u0BCD", -1, 1),
        Among("\u0BBF\u0B9F\u0BAE\u0BCD", -1, 1),
        Among("\u0BC6\u0BB2\u0BCD\u0BB2\u0BBE\u0BAE\u0BCD", -1, 3),
        Among("\u0BC6\u0BA9\u0BC1\u0BAE\u0BCD", -1, 1)
    )

    private val a_18 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_19 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_20 = arrayOf(
        Among("\u0BB5\u0BBF\u0B9F", -1, 2),
        Among("\u0BC0", -1, 7),
        Among("\u0BCA\u0B9F\u0BC1", -1, 2),
        Among("\u0BCB\u0B9F\u0BC1", -1, 2),
        Among("\u0BA4\u0BC1", -1, 6),
        Among("\u0BBF\u0BB0\u0BC1\u0BA8\u0BCD\u0BA4\u0BC1", 4, 2),
        Among("\u0BBF\u0BA9\u0BCD\u0BB1\u0BC1", -1, 2),
        Among("\u0BC1\u0B9F\u0BC8", -1, 2),
        Among("\u0BA9\u0BC8", -1, 1),
        Among("\u0B95\u0BA3\u0BCD", -1, 1),
        Among("\u0BBF\u0BA9\u0BCD", -1, 3),
        Among("\u0BAE\u0BC1\u0BA9\u0BCD", -1, 1),
        Among("\u0BBF\u0B9F\u0BAE\u0BCD", -1, 4),
        Among("\u0BBF\u0BB1\u0BCD", -1, 2),
        Among("\u0BAE\u0BC7\u0BB1\u0BCD", -1, 1),
        Among("\u0BB2\u0BCD", -1, 5),
        Among("\u0BBE\u0BAE\u0BB2\u0BCD", 15, 2),
        Among("\u0BBE\u0BB2\u0BCD", 15, 2),
        Among("\u0BBF\u0BB2\u0BCD", 15, 2),
        Among("\u0BAE\u0BC7\u0BB2\u0BCD", 15, 1),
        Among("\u0BC1\u0BB3\u0BCD", -1, 2),
        Among("\u0B95\u0BC0\u0BB4\u0BCD", -1, 1)
    )

    private val a_21 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9F", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BB1", -1, -1)
    )

    private val a_22 = arrayOf(
        Among("\u0B95", -1, -1),
        Among("\u0B9A", -1, -1),
        Among("\u0B9F", -1, -1),
        Among("\u0BA4", -1, -1),
        Among("\u0BAA", -1, -1),
        Among("\u0BB1", -1, -1)
    )

    private val a_23 = arrayOf(
        Among("\u0B85", -1, -1),
        Among("\u0B86", -1, -1),
        Among("\u0B87", -1, -1),
        Among("\u0B88", -1, -1),
        Among("\u0B89", -1, -1),
        Among("\u0B8A", -1, -1),
        Among("\u0B8E", -1, -1),
        Among("\u0B8F", -1, -1),
        Among("\u0B90", -1, -1),
        Among("\u0B92", -1, -1),
        Among("\u0B93", -1, -1),
        Among("\u0B94", -1, -1)
    )

    private val a_24 = arrayOf(
        Among("\u0BBE", -1, -1),
        Among("\u0BBF", -1, -1),
        Among("\u0BC0", -1, -1),
        Among("\u0BC1", -1, -1),
        Among("\u0BC2", -1, -1),
        Among("\u0BC6", -1, -1),
        Among("\u0BC7", -1, -1),
        Among("\u0BC8", -1, -1)
    )

    private val a_25 = arrayOf(
        Among("\u0B95", -1, 1),
        Among("\u0BA4", -1, 1),
        Among("\u0BA9", -1, 1),
        Among("\u0BAA", -1, 1),
        Among("\u0BAF", -1, 1),
        Among("\u0BBE", -1, 5),
        Among("\u0B95\u0BC1", -1, 6),
        Among("\u0BAA\u0B9F\u0BC1", -1, 1),
        Among("\u0BA4\u0BC1", -1, 3),
        Among("\u0BBF\u0BB1\u0BCD\u0BB1\u0BC1", -1, 1),
        Among("\u0BA9\u0BC8", -1, 1),
        Among("\u0BB5\u0BC8", -1, 1),
        Among("\u0BA9\u0BA9\u0BCD", -1, 1),
        Among("\u0BAA\u0BA9\u0BCD", -1, 1),
        Among("\u0BB5\u0BA9\u0BCD", -1, 2),
        Among("\u0BBE\u0BA9\u0BCD", -1, 4),
        Among("\u0BA9\u0BBE\u0BA9\u0BCD", 15, 1),
        Among("\u0BAE\u0BBF\u0BA9\u0BCD", -1, 1),
        Among("\u0BA9\u0BC6\u0BA9\u0BCD", -1, 1),
        Among("\u0BC7\u0BA9\u0BCD", -1, 5),
        Among("\u0BA9\u0BAE\u0BCD", -1, 1),
        Among("\u0BAA\u0BAE\u0BCD", -1, 1),
        Among("\u0BBE\u0BAE\u0BCD", -1, 5),
        Among("\u0B95\u0BC1\u0BAE\u0BCD", -1, 1),
        Among("\u0B9F\u0BC1\u0BAE\u0BCD", -1, 5),
        Among("\u0BA4\u0BC1\u0BAE\u0BCD", -1, 1),
        Among("\u0BB1\u0BC1\u0BAE\u0BCD", -1, 1),
        Among("\u0BC6\u0BAE\u0BCD", -1, 5),
        Among("\u0BC7\u0BAE\u0BCD", -1, 5),
        Among("\u0BCB\u0BAE\u0BCD", -1, 5),
        Among("\u0BBE\u0BAF\u0BCD", -1, 5),
        Among("\u0BA9\u0BB0\u0BCD", -1, 1),
        Among("\u0BAA\u0BB0\u0BCD", -1, 1),
        Among("\u0BC0\u0BAF\u0BB0\u0BCD", -1, 5),
        Among("\u0BB5\u0BB0\u0BCD", -1, 1),
        Among("\u0BBE\u0BB0\u0BCD", -1, 5),
        Among("\u0BA9\u0BBE\u0BB0\u0BCD", 35, 1),
        Among("\u0BAE\u0BBE\u0BB0\u0BCD", 35, 1),
        Among("\u0B95\u0BCA\u0BA3\u0BCD\u0B9F\u0BBF\u0BB0\u0BCD", -1, 1),
        Among("\u0BA9\u0BBF\u0BB0\u0BCD", -1, 5),
        Among("\u0BC0\u0BB0\u0BCD", -1, 5),
        Among("\u0BA9\u0BB3\u0BCD", -1, 1),
        Among("\u0BAA\u0BB3\u0BCD", -1, 1),
        Among("\u0BB5\u0BB3\u0BCD", -1, 1),
        Among("\u0BBE\u0BB3\u0BCD", -1, 5),
        Among("\u0BA9\u0BBE\u0BB3\u0BCD", 44, 1)
    )

    private val a_26 = arrayOf(
        Among("\u0B95\u0BBF\u0BB1", -1, -1),
        Among("\u0B95\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
        Among("\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
        Among("\u0B95\u0BBF\u0BB1\u0BCD", -1, -1),
        Among("\u0B95\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1),
        Among("\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1)
    )

    private var B_found_vetrumai_urupu = false
    private var B_found_a_match = false

    private fun r_has_min_length(): Boolean {
        return length > 4
    }

    private fun r_fix_va_start(): Boolean {
        bra = cursor
        val among_var = find_among(a_0)
        if (among_var == 0) {
            return false
        }
        ket = cursor
        when (among_var) {
            1 -> slice_from("\u0B93")
            2 -> slice_from("\u0B92")
            3 -> slice_from("\u0B89")
            4 -> slice_from("\u0B8A")
        }
        return true
    }

    private fun r_fix_endings(): Boolean {
        val v_1 = cursor
        while (true) {
            val v_2 = cursor
            if (r_fix_ending()) {
                continue
            }
            cursor = v_2
            break
        }
        cursor = v_1
        return true
    }

    private fun r_remove_question_prefixes(): Boolean {
        bra = cursor
        if (!eq_s("\u0B8E")) {
            return false
        }
        if (find_among(a_1) == 0) {
            return false
        }
        if (!eq_s("\u0BCD")) {
            return false
        }
        ket = cursor
        slice_del()
        val v_1 = cursor
        r_fix_va_start()
        cursor = v_1
        return true
    }

    private fun r_fix_ending(): Boolean {
        var among_var: Int
        if (length <= 3) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        run lab0@{
            val v_1 = limit - cursor
            run lab1@{
                ket = cursor
                among_var = find_among_b(a_5)
                if (among_var == 0) {
                    return@lab1
                }
                bra = cursor
                when (among_var) {
                    1 -> slice_del()
                    2 -> {
                        val v_2 = limit - cursor
                        if (find_among_b(a_2) == 0) {
                            return@lab1
                        }
                        cursor = limit - v_2
                        slice_del()
                    }
                    3 -> slice_from("\u0BB3\u0BCD")
                    4 -> slice_from("\u0BB2\u0BCD")
                    5 -> slice_from("\u0B9F\u0BC1")
                    6 -> {
                        if (!B_found_vetrumai_urupu) {
                            return@lab1
                        }
                        val v_3 = limit - cursor
                        run lab2@{
                            if (!eq_s_b("\u0BC8")) {
                                return@lab2
                            }
                            return@lab1
                        }
                        cursor = limit - v_3
                        slice_from("\u0BAE\u0BCD")
                    }
                    7 -> slice_from("\u0BCD")
                    8 -> {
                        val v_4 = limit - cursor
                        run lab3@{
                            if (find_among_b(a_3) == 0) {
                                return@lab3
                            }
                            return@lab1
                        }
                        cursor = limit - v_4
                        slice_del()
                    }
                    9 -> {
                        among_var = find_among_b(a_4)
                        when (among_var) {
                            1 -> slice_del()
                            2 -> slice_from("\u0BAE\u0BCD")
                        }
                    }
                }
                return@lab0
            }
            cursor = limit - v_1
            ket = cursor
            if (!eq_s_b("\u0BCD")) {
                return false
            }
            run lab4@{
                val v_5 = limit - cursor
                run lab5@{
                    if (find_among_b(a_6) == 0) {
                        return@lab5
                    }
                    val v_6 = limit - cursor
                    run lab6@{
                        if (!eq_s_b("\u0BCD")) {
                            cursor = limit - v_6
                            return@lab6
                        }
                        if (find_among_b(a_7) == 0) {
                            cursor = limit - v_6
                            return@lab6
                        }
                    }
                    bra = cursor
                    slice_del()
                    return@lab4
                }
                cursor = limit - v_5
                run lab7@{
                    if (find_among_b(a_8) == 0) {
                        return@lab7
                    }
                    bra = cursor
                    if (!eq_s_b("\u0BCD")) {
                        return@lab7
                    }
                    slice_del()
                    return@lab4
                }
                cursor = limit - v_5
                val v_7 = limit - cursor
                if (find_among_b(a_9) == 0) {
                    return false
                }
                cursor = limit - v_7
                bra = cursor
                slice_del()
            }
        }
        cursor = limit_backward
        return true
    }

    private fun r_remove_pronoun_prefixes(): Boolean {
        bra = cursor
        if (find_among(a_10) == 0) {
            return false
        }
        if (find_among(a_11) == 0) {
            return false
        }
        if (!eq_s("\u0BCD")) {
            return false
        }
        ket = cursor
        slice_del()
        val v_1 = cursor
        r_fix_va_start()
        cursor = v_1
        return true
    }

    private fun r_remove_plural_suffix(): Boolean {
        var among_var: Int
        limit_backward = cursor
        cursor = limit
        ket = cursor
        among_var = find_among_b(a_13)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        when (among_var) {
            1 -> run lab0@{
                val v_1 = limit - cursor
                run lab1@{
                    if (find_among_b(a_12) == 0) {
                        return@lab1
                    }
                    slice_from("\u0BC1\u0B99\u0BCD")
                    return@lab0
                }
                cursor = limit - v_1
                slice_from("\u0BCD")
            }
            2 -> slice_from("\u0BB2\u0BCD")
            3 -> slice_from("\u0BB3\u0BCD")
            4 -> slice_del()
        }
        cursor = limit_backward
        return true
    }

    private fun r_remove_question_suffixes(): Boolean {
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        val v_1 = limit - cursor
        run lab0@{
            ket = cursor
            if (find_among_b(a_14) == 0) {
                return@lab0
            }
            bra = cursor
            slice_from("\u0BCD")
        }
        cursor = limit - v_1
        cursor = limit_backward
        r_fix_endings()
        return true
    }

    private fun r_remove_command_suffixes(): Boolean {
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        ket = cursor
        if (find_among_b(a_15) == 0) {
            return false
        }
        bra = cursor
        slice_del()
        cursor = limit_backward
        return true
    }

    private fun r_remove_um(): Boolean {
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        ket = cursor
        if (!eq_s_b("\u0BC1\u0BAE\u0BCD")) {
            return false
        }
        bra = cursor
        slice_from("\u0BCD")
        cursor = limit_backward
        val v_1 = cursor
        r_fix_ending()
        cursor = v_1
        return true
    }

    private fun r_remove_common_word_endings(): Boolean {
        var among_var: Int
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        ket = cursor
        among_var = find_among_b(a_17)
        if (among_var == 0) {
            return false
        }
        bra = cursor
        when (among_var) {
            1 -> slice_from("\u0BCD")
            2 -> {
                val v_1 = limit - cursor
                run lab0@{
                    if (find_among_b(a_16) == 0) {
                        return@lab0
                    }
                    return false
                }
                cursor = limit - v_1
                slice_from("\u0BCD")
            }
            3 -> slice_del()
        }
        cursor = limit_backward
        r_fix_endings()
        return true
    }

    private fun r_remove_vetrumai_urupukal(): Boolean {
        var among_var: Int
        B_found_vetrumai_urupu = false
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        run lab0@{
            val v_1 = limit - cursor
            run lab1@{
                val v_2 = limit - cursor
                ket = cursor
                among_var = find_among_b(a_20)
                if (among_var == 0) {
                    return@lab1
                }
                bra = cursor
                when (among_var) {
                    1 -> slice_del()
                    2 -> slice_from("\u0BCD")
                    3 -> {
                        val v_3 = limit - cursor
                        run lab2@{
                            if (!eq_s_b("\u0BAE")) {
                                return@lab2
                            }
                            return@lab1
                        }
                        cursor = limit - v_3
                        slice_from("\u0BCD")
                    }
                    4 -> {
                        if (length < 7) {
                            return@lab1
                        }
                        slice_from("\u0BCD")
                    }
                    5 -> {
                        val v_4 = limit - cursor
                        run lab3@{
                            if (find_among_b(a_18) == 0) {
                                return@lab3
                            }
                            return@lab1
                        }
                        cursor = limit - v_4
                        slice_from("\u0BCD")
                    }
                    6 -> {
                        val v_5 = limit - cursor
                        run lab4@{
                            if (find_among_b(a_19) == 0) {
                                return@lab4
                            }
                            return@lab1
                        }
                        cursor = limit - v_5
                        slice_del()
                    }
                    7 -> slice_from("\u0BBF")
                }
                cursor = limit - v_2
                return@lab0
            }
            cursor = limit - v_1
            val v_6 = limit - cursor
            ket = cursor
            if (!eq_s_b("\u0BC8")) {
                return false
            }
            run lab5@{
                val v_7 = limit - cursor
                run lab6@{
                    val v_8 = limit - cursor
                    run lab7@{
                        if (find_among_b(a_21) == 0) {
                            return@lab7
                        }
                        return@lab6
                    }
                    cursor = limit - v_8
                    return@lab5
                }
                cursor = limit - v_7
                val v_9 = limit - cursor
                if (find_among_b(a_22) == 0) {
                    return false
                }
                if (!eq_s_b("\u0BCD")) {
                    return false
                }
                cursor = limit - v_9
            }
            bra = cursor
            slice_from("\u0BCD")
            cursor = limit - v_6
        }
        B_found_vetrumai_urupu = true
        val v_10 = limit - cursor
        run lab8@{
            ket = cursor
            if (!eq_s_b("\u0BBF\u0BA9\u0BCD")) {
                return@lab8
            }
            bra = cursor
            slice_from("\u0BCD")
        }
        cursor = limit - v_10
        cursor = limit_backward
        r_fix_endings()
        return true
    }

    private fun r_remove_tense_suffixes(): Boolean {
        B_found_a_match = true
        while (true) {
            val v_1 = cursor
            if (!B_found_a_match) {
                cursor = v_1
                break
            }
            val v_2 = cursor
            r_remove_tense_suffix()
            cursor = v_2
        }
        return true
    }

    private fun r_remove_tense_suffix(): Boolean {
        var among_var: Int
        B_found_a_match = false
        if (!r_has_min_length()) {
            return false
        }
        limit_backward = cursor
        cursor = limit
        val v_1 = limit - cursor
        run lab0@{
            val v_2 = limit - cursor
            ket = cursor
            among_var = find_among_b(a_25)
            if (among_var == 0) {
                return@lab0
            }
            bra = cursor
            when (among_var) {
                1 -> slice_del()
                2 -> {
                    val v_3 = limit - cursor
                    run lab1@{
                        if (find_among_b(a_23) == 0) {
                            return@lab1
                        }
                        return@lab0
                    }
                    cursor = limit - v_3
                    slice_del()
                }
                3 -> {
                    val v_4 = limit - cursor
                    run lab2@{
                        if (find_among_b(a_24) == 0) {
                            return@lab2
                        }
                        return@lab0
                    }
                    cursor = limit - v_4
                    slice_del()
                }
                4 -> {
                    val v_5 = limit - cursor
                    run lab3@{
                        if (!eq_s_b("\u0B9A")) {
                            return@lab3
                        }
                        return@lab0
                    }
                    cursor = limit - v_5
                    slice_from("\u0BCD")
                }
                5 -> slice_from("\u0BCD")
                6 -> {
                    val v_6 = limit - cursor
                    if (!eq_s_b("\u0BCD")) {
                        return@lab0
                    }
                    cursor = limit - v_6
                    slice_del()
                }
            }
            B_found_a_match = true
            cursor = limit - v_2
        }
        cursor = limit - v_1
        val v_7 = limit - cursor
        run lab4@{
            ket = cursor
            if (find_among_b(a_26) == 0) {
                return@lab4
            }
            bra = cursor
            slice_del()
            B_found_a_match = true
        }
        cursor = limit - v_7
        cursor = limit_backward
        r_fix_endings()
        return true
    }

    override fun stem(): Boolean {
        B_found_vetrumai_urupu = false
        val v_1 = cursor
        r_fix_ending()
        cursor = v_1
        if (!r_has_min_length()) {
            return false
        }
        val v_2 = cursor
        r_remove_question_prefixes()
        cursor = v_2
        val v_3 = cursor
        r_remove_pronoun_prefixes()
        cursor = v_3
        val v_4 = cursor
        r_remove_question_suffixes()
        cursor = v_4
        val v_5 = cursor
        r_remove_um()
        cursor = v_5
        val v_6 = cursor
        r_remove_common_word_endings()
        cursor = v_6
        val v_7 = cursor
        r_remove_vetrumai_urupukal()
        cursor = v_7
        val v_8 = cursor
        r_remove_plural_suffix()
        cursor = v_8
        val v_9 = cursor
        r_remove_command_suffixes()
        cursor = v_9
        val v_10 = cursor
        r_remove_tense_suffixes()
        cursor = v_10
        return true
    }

    override fun equals(other: Any?): Boolean {
        return other is TamilStemmer
    }

    override fun hashCode(): Int {
        return "org.tartarus.snowball.ext.TamilStemmer".hashCode()
    }
}
