package org.tartarus.snowball.ext

import org.tartarus.snowball.Among
import org.tartarus.snowball.SnowballStemmer

/**
 * This class implements the stemming algorithm defined by a snowball script.
 *
 * Generated by Snowball 2.2.0 - https://snowballstem.org/
 */
class TurkishStemmer : SnowballStemmer() {

  private val a_0 = arrayOf(
    Among("m", -1, -1),
    Among("n", -1, -1),
    Among("miz", -1, -1),
    Among("niz", -1, -1),
    Among("muz", -1, -1),
    Among("nuz", -1, -1),
    Among("m\u00FCz", -1, -1),
    Among("n\u00FCz", -1, -1),
    Among("m\u0131z", -1, -1),
    Among("n\u0131z", -1, -1)
  )

  private val a_1 = arrayOf(Among("leri", -1, -1), Among("lar\u0131", -1, -1))
  private val a_2 = arrayOf(
    Among("ni", -1, -1),
    Among("nu", -1, -1),
    Among("n\u00FC", -1, -1),
    Among("n\u0131", -1, -1)
  )

  private val a_3 = arrayOf(
    Among("in", -1, -1),
    Among("un", -1, -1),
    Among("\u00FCn", -1, -1),
    Among("\u0131n", -1, -1)
  )

  private val a_4 = arrayOf(Among("a", -1, -1), Among("e", -1, -1))
  private val a_5 = arrayOf(Among("na", -1, -1), Among("ne", -1, -1))
  private val a_6 = arrayOf(
    Among("da", -1, -1),
    Among("ta", -1, -1),
    Among("de", -1, -1),
    Among("te", -1, -1)
  )

  private val a_7 = arrayOf(Among("nda", -1, -1), Among("nde", -1, -1))
  private val a_8 = arrayOf(
    Among("dan", -1, -1),
    Among("tan", -1, -1),
    Among("den", -1, -1),
    Among("ten", -1, -1)
  )

  private val a_9 = arrayOf(Among("ndan", -1, -1), Among("nden", -1, -1))
  private val a_10 = arrayOf(Among("la", -1, -1), Among("le", -1, -1))
  private val a_11 = arrayOf(Among("ca", -1, -1), Among("ce", -1, -1))
  private val a_12 = arrayOf(
    Among("im", -1, -1),
    Among("um", -1, -1),
    Among("\u00FCm", -1, -1),
    Among("\u0131m", -1, -1)
  )

  private val a_13 = arrayOf(
    Among("sin", -1, -1),
    Among("sun", -1, -1),
    Among("s\u00FCn", -1, -1),
    Among("s\u0131n", -1, -1)
  )

  private val a_14 = arrayOf(
    Among("iz", -1, -1),
    Among("uz", -1, -1),
    Among("\u00FCz", -1, -1),
    Among("\u0131z", -1, -1)
  )

  private val a_15 = arrayOf(
    Among("siniz", -1, -1),
    Among("sunuz", -1, -1),
    Among("s\u00FCn\u00FCz", -1, -1),
    Among("s\u0131n\u0131z", -1, -1)
  )

  private val a_16 = arrayOf(Among("lar", -1, -1), Among("ler", -1, -1))
  private val a_17 = arrayOf(
    Among("niz", -1, -1),
    Among("nuz", -1, -1),
    Among("n\u00FCz", -1, -1),
    Among("n\u0131z", -1, -1)
  )

  private val a_18 = arrayOf(
    Among("dir", -1, -1),
    Among("tir", -1, -1),
    Among("dur", -1, -1),
    Among("tur", -1, -1),
    Among("d\u00FCr", -1, -1),
    Among("t\u00FCr", -1, -1),
    Among("d\u0131r", -1, -1),
    Among("t\u0131r", -1, -1)
  )

  private val a_19 = arrayOf(
    Among("cas\u0131na", -1, -1), Among("cesine", -1, -1)
  )

  private val a_20 = arrayOf(
    Among("di", -1, -1),
    Among("ti", -1, -1),
    Among("dik", -1, -1),
    Among("tik", -1, -1),
    Among("duk", -1, -1),
    Among("tuk", -1, -1),
    Among("d\u00FCk", -1, -1),
    Among("t\u00FCk", -1, -1),
    Among("d\u0131k", -1, -1),
    Among("t\u0131k", -1, -1),
    Among("dim", -1, -1),
    Among("tim", -1, -1),
    Among("dum", -1, -1),
    Among("tum", -1, -1),
    Among("d\u00FCm", -1, -1),
    Among("t\u00FCm", -1, -1),
    Among("d\u0131m", -1, -1),
    Among("t\u0131m", -1, -1),
    Among("din", -1, -1),
    Among("tin", -1, -1),
    Among("dun", -1, -1),
    Among("tun", -1, -1),
    Among("d\u00FCn", -1, -1),
    Among("t\u00FCn", -1, -1),
    Among("d\u0131n", -1, -1),
    Among("t\u0131n", -1, -1),
    Among("du", -1, -1),
    Among("tu", -1, -1),
    Among("d\u00FC", -1, -1),
    Among("t\u00FC", -1, -1),
    Among("d\u0131", -1, -1),
    Among("t\u0131", -1, -1)
  )

  private val a_21 = arrayOf(
    Among("sa", -1, -1),
    Among("se", -1, -1),
    Among("sak", -1, -1),
    Among("sek", -1, -1),
    Among("sam", -1, -1),
    Among("sem", -1, -1),
    Among("san", -1, -1),
    Among("sen", -1, -1)
  )

  private val a_22 = arrayOf(
    Among("mi\u015F", -1, -1),
    Among("mu\u015F", -1, -1),
    Among("m\u00FC\u015F", -1, -1),
    Among("m\u0131\u015F", -1, -1)
  )

  private val a_23 = arrayOf(
    Among("b", -1, 1), Among("c", -1, 2), Among("d", -1, 3), Among("\u011F", -1, 4)
  )
  private val g_vowel = charArrayOf(17.toChar(), 65.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 32.toChar(), 8.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 1.toChar())

  private val g_U = charArrayOf(1.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 8.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 1.toChar())

  private val g_vowel1 = charArrayOf(1.toChar(), 64.toChar(), 16.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 1.toChar())

  private val g_vowel2 = charArrayOf(17.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 130.toChar())

  private val g_vowel3 = charArrayOf(1.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 0.toChar(), 1.toChar())

  private val g_vowel4 = charArrayOf(17.toChar())

  private val g_vowel5 = charArrayOf(65.toChar())

  private val g_vowel6 = charArrayOf(65.toChar())

  private var B_continue_stemming_noun_suffixes = false

  private fun r_check_vowel_harmony(): Boolean {
    var v_1 = limit - cursor
    golab0@ while (true) {
      var v_2 = limit - cursor
      run lab1@ {
        if (!(in_grouping_b(g_vowel, 97, 305))) {
          return@lab1
        }
        cursor = limit - v_2
        break@golab0
      }
      cursor = limit - v_2
      if (cursor <= limit_backward) {
        return false
      }
      cursor--
    }
    run lab2@ {
      var v_3 = limit - cursor
      run lab3@ {
        if (!(eq_s_b("a"))) {
          return@lab3
        }
        golab4@ while (true) {
          var v_4 = limit - cursor
          run lab5@ {
            if (!(in_grouping_b(g_vowel1, 97, 305))) {
              return@lab5
            }
            cursor = limit - v_4
            break@golab4
          }
          cursor = limit - v_4
          if (cursor <= limit_backward) {
            return@lab3
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab6@ {
        if (!(eq_s_b("e"))) {
          return@lab6
        }
        golab7@ while (true) {
          var v_5 = limit - cursor
          run lab8@ {
            if (!(in_grouping_b(g_vowel2, 101, 252))) {
              return@lab8
            }
            cursor = limit - v_5
            break@golab7
          }
          cursor = limit - v_5
          if (cursor <= limit_backward) {
            return@lab6
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab9@ {
        if (!(eq_s_b("\u0131"))) {
          return@lab9
        }
        golab10@ while (true) {
          var v_6 = limit - cursor
          run lab11@ {
            if (!(in_grouping_b(g_vowel3, 97, 305))) {
              return@lab11
            }
            cursor = limit - v_6
            break@golab10
          }
          cursor = limit - v_6
          if (cursor <= limit_backward) {
            return@lab9
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab12@ {
        if (!(eq_s_b("i"))) {
          return@lab12
        }
        golab13@ while (true) {
          var v_7 = limit - cursor
          run lab14@ {
            if (!(in_grouping_b(g_vowel4, 101, 105))) {
              return@lab14
            }
            cursor = limit - v_7
            break@golab13
          }
          cursor = limit - v_7
          if (cursor <= limit_backward) {
            return@lab12
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab15@ {
        if (!(eq_s_b("o"))) {
          return@lab15
        }
        golab16@ while (true) {
          var v_8 = limit - cursor
          run lab17@ {
            if (!(in_grouping_b(g_vowel5, 111, 117))) {
              return@lab17
            }
            cursor = limit - v_8
            break@golab16
          }
          cursor = limit - v_8
          if (cursor <= limit_backward) {
            return@lab15
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab18@ {
        if (!(eq_s_b("\u00F6"))) {
          return@lab18
        }
        golab19@ while (true) {
          var v_9 = limit - cursor
          run lab20@ {
            if (!(in_grouping_b(g_vowel6, 246, 252))) {
              return@lab20
            }
            cursor = limit - v_9
            break@golab19
          }
          cursor = limit - v_9
          if (cursor <= limit_backward) {
            return@lab18
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      run lab21@ {
        if (!(eq_s_b("u"))) {
          return@lab21
        }
        golab22@ while (true) {
          var v_10 = limit - cursor
          run lab23@ {
            if (!(in_grouping_b(g_vowel5, 111, 117))) {
              return@lab23
            }
            cursor = limit - v_10
            break@golab22
          }
          cursor = limit - v_10
          if (cursor <= limit_backward) {
            return@lab21
          }
          cursor--
        }
        return@lab2
      }
      cursor = limit - v_3
      if (!(eq_s_b("\u00FC"))) {
        return false
      }
      golab24@ while (true) {
        var v_11 = limit - cursor
        run lab25@ {
          if (!(in_grouping_b(g_vowel6, 246, 252))) {
            return@lab25
          }
          cursor = limit - v_11
          break@golab24
        }
        cursor = limit - v_11
        if (cursor <= limit_backward) {
          return false
        }
        cursor--
      }
    }
    cursor = limit - v_1
    return true
  }

  private fun r_mark_suffix_with_optional_n_consonant(): Boolean {
    val v_1 = limit - cursor
    if (eq_s_b("n")) {
      val v_2 = limit - cursor
      if (in_grouping_b(g_vowel, 97, 305)) {
        cursor = limit - v_2
        return true
      }
    }
    cursor = limit - v_1
    val v_3 = limit - cursor
    val v_4 = limit - cursor
    if (eq_s_b("n")) {
      cursor = limit - v_4
      return false
    }
    cursor = limit - v_3
    val v_5 = limit - cursor
    if (cursor <= limit_backward) {
      return false
    }
    cursor--
    if (!in_grouping_b(g_vowel, 97, 305)) {
      return false
    }
    cursor = limit - v_5
    return true
  }

  private fun r_mark_suffix_with_optional_s_consonant(): Boolean {
    val v_1 = limit - cursor
    if (eq_s_b("s")) {
      val v_2 = limit - cursor
      if (in_grouping_b(g_vowel, 97, 305)) {
        cursor = limit - v_2
        return true
      }
    }
    cursor = limit - v_1
    val v_3 = limit - cursor
    val v_4 = limit - cursor
    if (eq_s_b("s")) {
      cursor = limit - v_4
      return false
    }
    cursor = limit - v_3
    val v_5 = limit - cursor
    if (cursor <= limit_backward) {
      return false
    }
    cursor--
    if (!in_grouping_b(g_vowel, 97, 305)) {
      return false
    }
    cursor = limit - v_5
    return true
  }

  private fun r_mark_suffix_with_optional_y_consonant(): Boolean {
    val v_1 = limit - cursor
    if (eq_s_b("y")) {
      val v_2 = limit - cursor
      if (in_grouping_b(g_vowel, 97, 305)) {
        cursor = limit - v_2
        return true
      }
    }
    cursor = limit - v_1
    val v_3 = limit - cursor
    val v_4 = limit - cursor
    if (eq_s_b("y")) {
      cursor = limit - v_4
      return false
    }
    cursor = limit - v_3
    val v_5 = limit - cursor
    if (cursor <= limit_backward) {
      return false
    }
    cursor--
    if (!in_grouping_b(g_vowel, 97, 305)) {
      return false
    }
    cursor = limit - v_5
    return true
  }

  private fun r_mark_suffix_with_optional_U_vowel(): Boolean {
    val v_1 = limit - cursor
    if (in_grouping_b(g_U, 105, 305)) {
      val v_2 = limit - cursor
      if (out_grouping_b(g_vowel, 97, 305)) {
        cursor = limit - v_2
        return true
      }
    }
    cursor = limit - v_1
    val v_3 = limit - cursor
    val v_4 = limit - cursor
    if (in_grouping_b(g_U, 105, 305)) {
      cursor = limit - v_4
      return false
    }
    cursor = limit - v_3
    val v_5 = limit - cursor
    if (cursor <= limit_backward) {
      return false
    }
    cursor--
    if (!out_grouping_b(g_vowel, 97, 305)) {
      return false
    }
    cursor = limit - v_5
    return true
  }

  private fun r_mark_possessives(): Boolean {
    if (find_among_b(a_0) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_U_vowel()) {
      return false
    }
    return true
  }

  private fun r_mark_sU(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (!(in_grouping_b(g_U, 105, 305))) {
      return false
    }
    if (!r_mark_suffix_with_optional_s_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_lArI(): Boolean {
    if (find_among_b(a_1) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_yU(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (!(in_grouping_b(g_U, 105, 305))) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_nU(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_2) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_nUn(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_3) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_n_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_yA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_4) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_nA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_5) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_DA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_6) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_ndA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_7) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_DAn(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_8) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_ndAn(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_9) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_ylA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_10) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_ki(): Boolean {
    if (!(eq_s_b("ki"))) {
      return false
    }
    return true
  }

  private fun r_mark_ncA(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_11) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_n_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_yUm(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_12) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_sUn(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_13) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_yUz(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_14) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_sUnUz(): Boolean {
    if (find_among_b(a_15) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_lAr(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_16) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_nUz(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_17) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_DUr(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_18) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_cAsInA(): Boolean {
    if (find_among_b(a_19) == 0) {
      return false
    }
    return true
  }

  private fun r_mark_yDU(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_20) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_ysA(): Boolean {
    if (find_among_b(a_21) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_ymUs_(): Boolean {
    if (!r_check_vowel_harmony()) {
      return false
    }
    if (find_among_b(a_22) == 0) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_mark_yken(): Boolean {
    if (!(eq_s_b("ken"))) {
      return false
    }
    if (!r_mark_suffix_with_optional_y_consonant()) {
      return false
    }
    return true
  }

  private fun r_stem_nominal_verb_suffixes(): Boolean {
    ket = cursor
    B_continue_stemming_noun_suffixes = true
    run lab0@ {
      var v_1 = limit - cursor
      run lab1@ {
        run lab2@ {
          var v_2 = limit - cursor
          run lab3@ {
            if (!r_mark_ymUs_()) {
              return@lab3
            }
            return@lab2
          }
          cursor = limit - v_2
          run lab4@ {
            if (!r_mark_yDU()) {
              return@lab4
            }
            return@lab2
          }
          cursor = limit - v_2
          run lab5@ {
            if (!r_mark_ysA()) {
              return@lab5
            }
            return@lab2
          }
          cursor = limit - v_2
          if (!r_mark_yken()) {
            return@lab1
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab6@ {
        if (!r_mark_cAsInA()) {
          return@lab6
        }
        run lab7@ {
          var v_3 = limit - cursor
          run lab8@ {
            if (!r_mark_sUnUz()) {
              return@lab8
            }
            return@lab7
          }
          cursor = limit - v_3
          run lab9@ {
            if (!r_mark_lAr()) {
              return@lab9
            }
            return@lab7
          }
          cursor = limit - v_3
          run lab10@ {
            if (!r_mark_yUm()) {
              return@lab10
            }
            return@lab7
          }
          cursor = limit - v_3
          run lab11@ {
            if (!r_mark_sUn()) {
              return@lab11
            }
            return@lab7
          }
          cursor = limit - v_3
          run lab12@ {
            if (!r_mark_yUz()) {
              return@lab12
            }
            return@lab7
          }
          cursor = limit - v_3
        }
        if (!r_mark_ymUs_()) {
          return@lab6
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab13@ {
        if (!r_mark_lAr()) {
          return@lab13
        }
        bra = cursor
        slice_del()
        var v_4 = limit - cursor
        run lab14@ {
          ket = cursor
          run lab15@ {
            var v_5 = limit - cursor
            run lab16@ {
              if (!r_mark_DUr()) {
                return@lab16
              }
              return@lab15
            }
            cursor = limit - v_5
            run lab17@ {
              if (!r_mark_yDU()) {
                return@lab17
              }
              return@lab15
            }
            cursor = limit - v_5
            run lab18@ {
              if (!r_mark_ysA()) {
                return@lab18
              }
              return@lab15
            }
            cursor = limit - v_5
            if (!r_mark_ymUs_()) {
              cursor = limit - v_4
              return@lab14
            }
          }
        }
        B_continue_stemming_noun_suffixes = false
        return@lab0
      }
      cursor = limit - v_1
      run lab19@ {
        if (!r_mark_nUz()) {
          return@lab19
        }
        run lab20@ {
          var v_6 = limit - cursor
          run lab21@ {
            if (!r_mark_yDU()) {
              return@lab21
            }
            return@lab20
          }
          cursor = limit - v_6
          if (!r_mark_ysA()) {
            return@lab19
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab22@ {
        run lab23@ {
          var v_7 = limit - cursor
          run lab24@ {
            if (!r_mark_sUnUz()) {
              return@lab24
            }
            return@lab23
          }
          cursor = limit - v_7
          run lab25@ {
            if (!r_mark_yUz()) {
              return@lab25
            }
            return@lab23
          }
          cursor = limit - v_7
          run lab26@ {
            if (!r_mark_sUn()) {
              return@lab26
            }
            return@lab23
          }
          cursor = limit - v_7
          if (!r_mark_yUm()) {
            return@lab22
          }
        }
        bra = cursor
        slice_del()
        var v_8 = limit - cursor
        run lab27@ {
          ket = cursor
          if (!r_mark_ymUs_()) {
            cursor = limit - v_8
            return@lab27
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      if (!r_mark_DUr()) {
        return false
      }
      bra = cursor
      slice_del()
      var v_9 = limit - cursor
      run lab28@ {
        ket = cursor
        run lab29@ {
          var v_10 = limit - cursor
          run lab30@ {
            if (!r_mark_sUnUz()) {
              return@lab30
            }
            return@lab29
          }
          cursor = limit - v_10
          run lab31@ {
            if (!r_mark_lAr()) {
              return@lab31
            }
            return@lab29
          }
          cursor = limit - v_10
          run lab32@ {
            if (!r_mark_yUm()) {
              return@lab32
            }
            return@lab29
          }
          cursor = limit - v_10
          run lab33@ {
            if (!r_mark_sUn()) {
              return@lab33
            }
            return@lab29
          }
          cursor = limit - v_10
          run lab34@ {
            if (!r_mark_yUz()) {
              return@lab34
            }
            return@lab29
          }
          cursor = limit - v_10
        }
        if (!r_mark_ymUs_()) {
          cursor = limit - v_9
          return@lab28
        }
      }
    }
    bra = cursor
    slice_del()
    return true
  }

  private fun r_stem_suffix_chain_before_ki(): Boolean {
    ket = cursor
    if (!r_mark_ki()) {
      return false
    }
    run lab0@ {
      var v_1 = limit - cursor
      run lab1@ {
        if (!r_mark_DA()) {
          return@lab1
        }
        bra = cursor
        slice_del()
        var v_2 = limit - cursor
        run lab2@ {
          ket = cursor
          run lab3@ {
            var v_3 = limit - cursor
            run lab4@ {
              if (!r_mark_lAr()) {
                return@lab4
              }
              bra = cursor
              slice_del()
              var v_4 = limit - cursor
              run lab5@ {
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_4
                  return@lab5
                }
              }
              return@lab3
            }
            cursor = limit - v_3
            if (!r_mark_possessives()) {
              cursor = limit - v_2
              return@lab2
            }
            bra = cursor
            slice_del()
            var v_5 = limit - cursor
            run lab6@ {
              ket = cursor
              if (!r_mark_lAr()) {
                cursor = limit - v_5
                return@lab6
              }
              bra = cursor
              slice_del()
              if (!r_stem_suffix_chain_before_ki()) {
                cursor = limit - v_5
                return@lab6
              }
            }
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab7@ {
        if (!r_mark_nUn()) {
          return@lab7
        }
        bra = cursor
        slice_del()
        var v_6 = limit - cursor
        run lab8@ {
          ket = cursor
          run lab9@ {
            var v_7 = limit - cursor
            run lab10@ {
              if (!r_mark_lArI()) {
                return@lab10
              }
              bra = cursor
              slice_del()
              return@lab9
            }
            cursor = limit - v_7
            run lab11@ {
              ket = cursor
              run lab12@ {
                var v_8 = limit - cursor
                run lab13@ {
                  if (!r_mark_possessives()) {
                    return@lab13
                  }
                  return@lab12
                }
                cursor = limit - v_8
                if (!r_mark_sU()) {
                  return@lab11
                }
              }
              bra = cursor
              slice_del()
              var v_9 = limit - cursor
              run lab14@ {
                ket = cursor
                if (!r_mark_lAr()) {
                  cursor = limit - v_9
                  return@lab14
                }
                bra = cursor
                slice_del()
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_9
                  return@lab14
                }
              }
              return@lab9
            }
            cursor = limit - v_7
            if (!r_stem_suffix_chain_before_ki()) {
              cursor = limit - v_6
              return@lab8
            }
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      if (!r_mark_ndA()) {
        return false
      }
      run lab15@ {
        var v_10 = limit - cursor
        run lab16@ {
          if (!r_mark_lArI()) {
            return@lab16
          }
          bra = cursor
          slice_del()
          return@lab15
        }
        cursor = limit - v_10
        run lab17@ {
          if (!r_mark_sU()) {
            return@lab17
          }
          bra = cursor
          slice_del()
          var v_11 = limit - cursor
          run lab18@ {
            ket = cursor
            if (!r_mark_lAr()) {
              cursor = limit - v_11
              return@lab18
            }
            bra = cursor
            slice_del()
            if (!r_stem_suffix_chain_before_ki()) {
              cursor = limit - v_11
              return@lab18
            }
          }
          return@lab15
        }
        cursor = limit - v_10
        if (!r_stem_suffix_chain_before_ki()) {
          return false
        }
      }
    }
    return true
  }

  private fun r_stem_noun_suffixes(): Boolean {
    run lab0@ {
      var v_1 = limit - cursor
      run lab1@ {
        ket = cursor
        if (!r_mark_lAr()) {
          return@lab1
        }
        bra = cursor
        slice_del()
        var v_2 = limit - cursor
        run lab2@ {
          if (!r_stem_suffix_chain_before_ki()) {
            cursor = limit - v_2
            return@lab2
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab3@ {
        ket = cursor
        if (!r_mark_ncA()) {
          return@lab3
        }
        bra = cursor
        slice_del()
        var v_3 = limit - cursor
        run lab4@ {
          run lab5@ {
            var v_4 = limit - cursor
            run lab6@ {
              ket = cursor
              if (!r_mark_lArI()) {
                return@lab6
              }
              bra = cursor
              slice_del()
              return@lab5
            }
            cursor = limit - v_4
            run lab7@ {
              ket = cursor
              run lab8@ {
                var v_5 = limit - cursor
                run lab9@ {
                  if (!r_mark_possessives()) {
                    return@lab9
                  }
                  return@lab8
                }
                cursor = limit - v_5
                if (!r_mark_sU()) {
                  return@lab7
                }
              }
              bra = cursor
              slice_del()
              var v_6 = limit - cursor
              run lab10@ {
                ket = cursor
                if (!r_mark_lAr()) {
                  cursor = limit - v_6
                  return@lab10
                }
                bra = cursor
                slice_del()
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_6
                  return@lab10
                }
              }
              return@lab5
            }
            cursor = limit - v_4
            ket = cursor
            if (!r_mark_lAr()) {
              cursor = limit - v_3
              return@lab4
            }
            bra = cursor
            slice_del()
            if (!r_stem_suffix_chain_before_ki()) {
              cursor = limit - v_3
              return@lab4
            }
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab11@ {
        ket = cursor
        run lab12@ {
          var v_7 = limit - cursor
          run lab13@ {
            if (!r_mark_ndA()) {
              return@lab13
            }
            return@lab12
          }
          cursor = limit - v_7
          if (!r_mark_nA()) {
            return@lab11
          }
        }
        run lab14@ {
          var v_8 = limit - cursor
          run lab15@ {
            if (!r_mark_lArI()) {
              return@lab15
            }
            bra = cursor
            slice_del()
            return@lab14
          }
          cursor = limit - v_8
          run lab16@ {
            if (!r_mark_sU()) {
              return@lab16
            }
            bra = cursor
            slice_del()
            var v_9 = limit - cursor
            run lab17@ {
              ket = cursor
              if (!r_mark_lAr()) {
                cursor = limit - v_9
                return@lab17
              }
              bra = cursor
              slice_del()
              if (!r_stem_suffix_chain_before_ki()) {
                cursor = limit - v_9
                return@lab17
              }
            }
            return@lab14
          }
          cursor = limit - v_8
          if (!r_stem_suffix_chain_before_ki()) {
            return@lab11
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab18@ {
        ket = cursor
        run lab19@ {
          var v_10 = limit - cursor
          run lab20@ {
            if (!r_mark_ndAn()) {
              return@lab20
            }
            return@lab19
          }
          cursor = limit - v_10
          if (!r_mark_nU()) {
            return@lab18
          }
        }
        run lab21@ {
          var v_11 = limit - cursor
          run lab22@ {
            if (!r_mark_sU()) {
              return@lab22
            }
            bra = cursor
            slice_del()
            var v_12 = limit - cursor
            run lab23@ {
              ket = cursor
              if (!r_mark_lAr()) {
                cursor = limit - v_12
                return@lab23
              }
              bra = cursor
              slice_del()
              if (!r_stem_suffix_chain_before_ki()) {
                cursor = limit - v_12
                return@lab23
              }
            }
            return@lab21
          }
          cursor = limit - v_11
          if (!r_mark_lArI()) {
            return@lab18
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab24@ {
        ket = cursor
        if (!r_mark_DAn()) {
          return@lab24
        }
        bra = cursor
        slice_del()
        var v_13 = limit - cursor
        run lab25@ {
          ket = cursor
          run lab26@ {
            var v_14 = limit - cursor
            run lab27@ {
              if (!r_mark_possessives()) {
                return@lab27
              }
              bra = cursor
              slice_del()
              var v_15 = limit - cursor
              run lab28@ {
                ket = cursor
                if (!r_mark_lAr()) {
                  cursor = limit - v_15
                  return@lab28
                }
                bra = cursor
                slice_del()
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_15
                  return@lab28
                }
              }
              return@lab26
            }
            cursor = limit - v_14
            run lab29@ {
              if (!r_mark_lAr()) {
                return@lab29
              }
              bra = cursor
              slice_del()
              var v_16 = limit - cursor
              run lab30@ {
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_16
                  return@lab30
                }
              }
              return@lab26
            }
            cursor = limit - v_14
            if (!r_stem_suffix_chain_before_ki()) {
              cursor = limit - v_13
              return@lab25
            }
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab31@ {
        ket = cursor
        run lab32@ {
          var v_17 = limit - cursor
          run lab33@ {
            if (!r_mark_nUn()) {
              return@lab33
            }
            return@lab32
          }
          cursor = limit - v_17
          if (!r_mark_ylA()) {
            return@lab31
          }
        }
        bra = cursor
        slice_del()
        var v_18 = limit - cursor
        run lab34@ {
          run lab35@ {
            var v_19 = limit - cursor
            run lab36@ {
              ket = cursor
              if (!r_mark_lAr()) {
                return@lab36
              }
              bra = cursor
              slice_del()
              if (!r_stem_suffix_chain_before_ki()) {
                return@lab36
              }
              return@lab35
            }
            cursor = limit - v_19
            run lab37@ {
              ket = cursor
              run lab38@ {
                var v_20 = limit - cursor
                run lab39@ {
                  if (!r_mark_possessives()) {
                    return@lab39
                  }
                  return@lab38
                }
                cursor = limit - v_20
                if (!r_mark_sU()) {
                  return@lab37
                }
              }
              bra = cursor
              slice_del()
              var v_21 = limit - cursor
              run lab40@ {
                ket = cursor
                if (!r_mark_lAr()) {
                  cursor = limit - v_21
                  return@lab40
                }
                bra = cursor
                slice_del()
                if (!r_stem_suffix_chain_before_ki()) {
                  cursor = limit - v_21
                  return@lab40
                }
              }
              return@lab35
            }
            cursor = limit - v_19
            if (!r_stem_suffix_chain_before_ki()) {
              cursor = limit - v_18
              return@lab34
            }
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab41@ {
        ket = cursor
        if (!r_mark_lArI()) {
          return@lab41
        }
        bra = cursor
        slice_del()
        return@lab0
      }
      cursor = limit - v_1
      run lab42@ {
        if (!r_stem_suffix_chain_before_ki()) {
          return@lab42
        }
        return@lab0
      }
      cursor = limit - v_1
      run lab43@ {
        ket = cursor
        run lab44@ {
          var v_22 = limit - cursor
          run lab45@ {
            if (!r_mark_DA()) {
              return@lab45
            }
            return@lab44
          }
          cursor = limit - v_22
          run lab46@ {
            if (!r_mark_yU()) {
              return@lab46
            }
            return@lab44
          }
          cursor = limit - v_22
          if (!r_mark_yA()) {
            return@lab43
          }
        }
        bra = cursor
        slice_del()
        var v_23 = limit - cursor
        run lab47@ {
          ket = cursor
          run lab48@ {
            var v_24 = limit - cursor
            run lab49@ {
              if (!r_mark_possessives()) {
                return@lab49
              }
              bra = cursor
              slice_del()
              var v_25 = limit - cursor
              run lab50@ {
                ket = cursor
                if (!r_mark_lAr()) {
                  cursor = limit - v_25
                  return@lab50
                }
              }
              return@lab48
            }
            cursor = limit - v_24
            if (!r_mark_lAr()) {
              cursor = limit - v_23
              return@lab47
            }
          }
          bra = cursor
          slice_del()
          ket = cursor
          if (!r_stem_suffix_chain_before_ki()) {
            cursor = limit - v_23
            return@lab47
          }
        }
        return@lab0
      }
      cursor = limit - v_1
      ket = cursor
      run lab51@ {
        var v_26 = limit - cursor
        run lab52@ {
          if (!r_mark_possessives()) {
            return@lab52
          }
          return@lab51
        }
        cursor = limit - v_26
        if (!r_mark_sU()) {
          return false
        }
      }
      bra = cursor
      slice_del()
      var v_27 = limit - cursor
      run lab53@ {
        ket = cursor
        if (!r_mark_lAr()) {
          cursor = limit - v_27
          return@lab53
        }
        bra = cursor
        slice_del()
        if (!r_stem_suffix_chain_before_ki()) {
          cursor = limit - v_27
          return@lab53
        }
      }
    }
    return true
  }

  private fun r_post_process_last_consonants(): Boolean {
    var among_var: Int
    ket = cursor
    among_var = find_among_b(a_23)
    if (among_var == 0) {
      return false
    }
    bra = cursor
    when (among_var) {
      1 -> {
        slice_from("p")
        }
      2 -> {
        slice_from("\u00E7")
        }
      3 -> {
        slice_from("t")
        }
      4 -> {
        slice_from("k")
        }
    }
    return true
  }

  private fun r_append_U_to_stems_ending_with_d_or_g(): Boolean {
    ket = cursor
    bra = cursor
    run lab0@ {
      var v_1 = limit - cursor
      run lab1@ {
        if (!(eq_s_b("d"))) {
          return@lab1
        }
        return@lab0
      }
      cursor = limit - v_1
      if (!(eq_s_b("g"))) {
        return false
      }
    }
    golab2@ while (true) {
      var v_2 = limit - cursor
      run lab3@ {
        if (!(in_grouping_b(g_vowel, 97, 305))) {
          return@lab3
        }
        cursor = limit - v_2
        break@golab2
      }
      cursor = limit - v_2
      if (cursor <= limit_backward) {
        return false
      }
      cursor--
    }
    run lab4@ {
      var v_3 = limit - cursor
      run lab5@ {
        run lab6@ {
          var v_4 = limit - cursor
          run lab7@ {
            if (!(eq_s_b("a"))) {
              return@lab7
            }
            return@lab6
          }
          cursor = limit - v_4
          if (!(eq_s_b("\u0131"))) {
            return@lab5
          }
        }
        slice_from("\u0131")
        return@lab4
      }
      cursor = limit - v_3
      run lab8@ {
        run lab9@ {
          var v_5 = limit - cursor
          run lab10@ {
            if (!(eq_s_b("e"))) {
              return@lab10
            }
            return@lab9
          }
          cursor = limit - v_5
          if (!(eq_s_b("i"))) {
            return@lab8
          }
        }
        slice_from("i")
        return@lab4
      }
      cursor = limit - v_3
      run lab11@ {
        run lab12@ {
          var v_6 = limit - cursor
          run lab13@ {
            if (!(eq_s_b("o"))) {
              return@lab13
            }
            return@lab12
          }
          cursor = limit - v_6
          if (!(eq_s_b("u"))) {
            return@lab11
          }
        }
        slice_from("u")
        return@lab4
      }
      cursor = limit - v_3
      run lab14@ {
        var v_7 = limit - cursor
        run lab15@ {
          if (!(eq_s_b("\u00F6"))) {
            return@lab15
          }
          return@lab14
        }
        cursor = limit - v_7
        if (!(eq_s_b("\u00FC"))) {
          return false
        }
      }
      slice_from("\u00FC")
    }
    return true
  }

  private fun r_is_reserved_word(): Boolean {
    if (!(eq_s_b("ad"))) {
      return false
    }
    var v_1 = limit - cursor
    run lab0@ {
      if (!(eq_s_b("soy"))) {
        cursor = limit - v_1
        return@lab0
      }
    }
    if (cursor > limit_backward) {
      return false
    }
    return true
  }

  private fun r_more_than_one_syllable_word(): Boolean {
    var v_1 = cursor
    for (v_2 in 2 downTo 1) {
      golab0@ while (true) {
        run lab1@ {
          if (!(in_grouping(g_vowel, 97, 305))) {
            return@lab1
          }
          break@golab0
        }
        if (cursor >= limit) {
          return false
        }
        cursor++
      }
    }
    cursor = v_1
    return true
  }

  private fun r_postlude(): Boolean {
    limit_backward = cursor
    cursor = limit
    val v_1 = limit - cursor
    if (r_is_reserved_word()) {
      return false
    }
    cursor = limit - v_1
    var v_2 = limit - cursor
    r_append_U_to_stems_ending_with_d_or_g()
    cursor = limit - v_2
    var v_3 = limit - cursor
    r_post_process_last_consonants()
    cursor = limit - v_3
    cursor = limit_backward
    return true
  }

    override fun stem(): Boolean {
    if (!r_more_than_one_syllable_word()) {
      return false
    }
    limit_backward = cursor
    cursor = limit
    var v_1 = limit - cursor
    r_stem_nominal_verb_suffixes()
    cursor = limit - v_1
    if (!(B_continue_stemming_noun_suffixes)) {
      return false
    }
    var v_2 = limit - cursor
    r_stem_noun_suffixes()
    cursor = limit - v_2
    cursor = limit_backward
    if (!r_postlude()) {
      return false
    }
    return true
  }

    override fun equals(other: Any?): Boolean {
    return other is TurkishStemmer
  }

    override fun hashCode(): Int {
    return "org.tartarus.snowball.ext.TurkishStemmer".hashCode()
  }
}
