/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 7.0 */
/* JavaCCOptions:KEEP_LINE_COLUMN=true */
package org.gnit.lucenekmp.queryparser.flexible.standard.parser

import org.gnit.lucenekmp.queryparser.flexible.core.QueryNodeParseException
import org.gnit.lucenekmp.queryparser.flexible.core.messages.QueryParserMessages
import org.gnit.lucenekmp.queryparser.flexible.messages.Message
import org.gnit.lucenekmp.queryparser.flexible.messages.MessageImpl

/**
 * This exception is thrown when parse errors are encountered.
 * You can explicitly create objects of this exception type by
 * calling the method generateParseException in the generated
 * parser.
 *
 * You can modify this class to customize your error reporting
 * mechanisms so long as you retain the public fields.
 */
class ParseException : QueryNodeParseException {
    /**
     * The version identifier for this Serializable class.
     * Increment only if the *serialized* form of the
     * class changes.
     */

    /**
     * This is the last token that has been consumed successfully. If this object has been created
     * due to a parse error, the token following this token will (therefore) be the first error token.
     */
    var currentToken: Token? = null

    /**
     * Each entry in this array is an array of integers. Each array of integers represents a
     * sequence of tokens (by their ordinal values) that is expected at this point of the parse.
     */
    var expectedTokenSequences: Array<IntArray>? = null

    /**
     * This is a reference to the "tokenImage" array of the generated parser within which the parse
     * error occurred. This array is defined in the generated ...Constants interface.
     */
    var tokenImage: Array<String>? = null

    /**
     * This constructor is used by the method "generateParseException" in the generated parser.
     * Calling this constructor generates a new object of this type with the fields "currentToken",
     * "expectedTokenSequences", and "tokenImage" set.
     */
    constructor(
        currentTokenVal: Token,
        expectedTokenSequencesVal: Array<IntArray>,
        tokenImageVal: Array<String>,
    ) : super(
        MessageImpl(
            QueryParserMessages.INVALID_SYNTAX,
            initialise(currentTokenVal, expectedTokenSequencesVal, tokenImageVal),
        ),
    ) {
        currentToken = currentTokenVal
        expectedTokenSequences = expectedTokenSequencesVal
        tokenImage = tokenImageVal
    }

    /**
     * The following constructors are for use by you for whatever purpose you can think of.
     * Constructing the exception in this manner makes the exception behave in the normal way -
     * i.e., as documented in the class "Throwable". The fields "errorToken",
     * "expectedTokenSequences", and "tokenImage" do not contain relevant information. The JavaCC
     * generated code does not use these constructors.
     */
    constructor() : super(MessageImpl(QueryParserMessages.INVALID_SYNTAX, "Error"))

    /** Constructor with message. */
    constructor(message: Message) : super(message)

    companion object {
        /**
         * The end of line string for this machine.
         */
        protected const val EOL: String = "\n"

        /**
         * It uses "currentToken" and "expectedTokenSequences" to generate a parse error message and
         * returns it. If this object has been created due to a parse error, and you do not catch it
         * (it gets thrown from the parser) the correct error message gets displayed.
         */
        private fun initialise(
            currentToken: Token,
            expectedTokenSequences: Array<IntArray>,
            tokenImage: Array<String>,
        ): String {
            val expected = StringBuilder()
            var maxSize = 0
            for (i in expectedTokenSequences.indices) {
                if (maxSize < expectedTokenSequences[i].size) {
                    maxSize = expectedTokenSequences[i].size
                }
                for (j in expectedTokenSequences[i].indices) {
                    expected.append(tokenImage[expectedTokenSequences[i][j]]).append(' ')
                }
                if (expectedTokenSequences[i][expectedTokenSequences[i].size - 1] != 0) {
                    expected.append("...")
                }
                expected.append(EOL).append("    ")
            }
            var retval = "Encountered \""
            var tok = requireNotNull(currentToken.next)
            for (i in 0..<maxSize) {
                if (i != 0) retval += " "
                if (tok.kind == 0) {
                    retval += tokenImage[0]
                    break
                }
                retval += " " + tokenImage[tok.kind]
                retval += " \""
                retval += add_escapes(requireNotNull(tok.image))
                retval += " \""
                tok = requireNotNull(tok.next)
            }
            if (currentToken.next != null) {
                retval += "\" at line ${currentToken.next!!.beginLine}, column ${currentToken.next!!.beginColumn}"
            }
            retval += ".$EOL"

            if (expectedTokenSequences.isEmpty()) {
                // Nothing to add here
            } else {
                if (expectedTokenSequences.size == 1) {
                    retval += "Was expecting:$EOL    "
                } else {
                    retval += "Was expecting one of:$EOL    "
                }
                retval += expected.toString()
            }

            return retval
        }

        /**
         * Used to convert raw characters to their escaped version when these raw version cannot be
         * used as part of an ASCII string literal.
         */
        fun add_escapes(str: String): String {
            val retval = StringBuilder()
            var ch: Char
            for (i in str.indices) {
                when (str[i]) {
                    '\b' -> retval.append("\\b")
                    '\t' -> retval.append("\\t")
                    '\n' -> retval.append("\\n")
                    '\u000c' -> retval.append("\\f")
                    '\r' -> retval.append("\\r")
                    '"' -> retval.append("\\\"")
                    '\'' -> retval.append("\\\'")
                    '\\' -> retval.append("\\\\")
                    else -> {
                        ch = str[i]
                        if (ch < 0x20.toChar() || ch > 0x7e.toChar()) {
                            val s = "0000" + ch.code.toString(16)
                            retval.append("\\u" + s.substring(s.length - 4, s.length))
                        } else {
                            retval.append(ch)
                        }
                    }
                }
            }
            return retval.toString()
        }
    }
}
/* (filtered)*/
