/* StandardSyntaxParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. StandardSyntaxParserTokenManager.java */
package org.gnit.lucenekmp.queryparser.flexible.standard.parser

import okio.IOException
import org.gnit.lucenekmp.queryparser.charstream.CharStream
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.EOF
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.AND
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OR
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NOT
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.FN_PREFIX
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.PLUS
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.MINUS
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RPAREN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_COLON
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_EQUAL
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_LESSTHAN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_LESSTHANEQ
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_MORETHAN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OP_MORETHANEQ
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.CARAT
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.TILDE
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.QUOTED
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NUMBER
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.TERM
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.REGEXPTERM
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGEIN_START
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGEEX_START
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.LPAREN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.ATLEAST
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.AFTER
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.BEFORE
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.CONTAINED_BY
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.CONTAINING
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.EXTEND
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.FN_OR
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.FUZZYTERM
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.MAXGAPS
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.MAXWIDTH
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NON_OVERLAPPING
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NOT_CONTAINED_BY
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NOT_CONTAINING
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.NOT_WITHIN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.ORDERED
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.OVERLAPPING
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.PHRASE
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.UNORDERED
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.UNORDERED_NO_OVERLAPS
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.WILDCARD
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.WITHIN
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGE_TO
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGEIN_END
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGEEX_END
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGE_QUOTED
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.RANGE_GOOP
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.Function
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.Range
import org.gnit.lucenekmp.queryparser.flexible.standard.parser.StandardSyntaxParserConstants.Companion.DEFAULT

/** Token Manager. */
class StandardSyntaxParserTokenManager : StandardSyntaxParserConstants {
    private var inputStream: CharStream
    private var input: String = ""
    private var offset: Int = 0
    private var curLexState: Int = DEFAULT

    /** Constructor. */
    constructor(stream: CharStream) {
        inputStream = stream
        loadInput()
    }

    /** Constructor. */
    constructor(stream: CharStream, lexState: Int) {
        inputStream = stream
        loadInput()
        SwitchTo(lexState)
    }

    /** Reinitialise parser. */
    fun ReInit(stream: CharStream) {
        inputStream = stream
        curLexState = DEFAULT
        loadInput()
    }

    /** Reinitialise parser. */
    fun ReInit(stream: CharStream, lexState: Int) {
        ReInit(stream)
        SwitchTo(lexState)
    }

    /** Switch to specified lex state. */
    fun SwitchTo(lexState: Int) {
        if (lexState >= 3 || lexState < 0) {
            throw TokenMgrError(
                "Error: Ignoring invalid lexical state : $lexState. State unchanged.",
                TokenMgrError.INVALID_LEXICAL_STATE
            )
        } else {
            curLexState = lexState
        }
    }

    private fun loadInput() {
        val builder = StringBuilder()
        try {
            builder.append(inputStream.BeginToken())
            while (true) {
                builder.append(inputStream.readChar())
            }
        } catch (_: IOException) {
            // end of stream
        }
        input = builder.toString()
        offset = 0
    }

    /** Get the next Token. */
    fun getNextToken(): Token {
        while (offset < input.length && isWhitespace(input[offset])) {
            offset++
        }
        if (offset >= input.length) {
            return token(EOF, "", offset, offset)
        }

        val start = offset
        val result = when (curLexState) {
            Range -> lexRange()
            Function -> lexFunction()
            else -> lexDefault()
        }
        return token(result.first, input.substring(start, offset), start, offset)
    }

    private fun lexRange(): Pair<Int, Int> {
        val c = input[offset]
        if (c == ']') {
            offset++
            curLexState = DEFAULT
            return RANGEIN_END to offset
        }
        if (c == '}') {
            offset++
            curLexState = DEFAULT
            return RANGEEX_END to offset
        }
        if (c == '"') {
            offset++
            var hasCharacter = false
            while (offset < input.length) {
                if (input[offset] == '\\' && offset + 1 < input.length && input[offset + 1] == '"') {
                    offset += 2
                    hasCharacter = true
                } else if (input[offset] == '"') {
                    offset++
                    if (hasCharacter) return RANGE_QUOTED to offset
                    break
                } else {
                    offset++
                    hasCharacter = true
                }
            }
            lexicalError(start = offset)
        }
        while (offset < input.length && !isWhitespace(input[offset]) &&
            input[offset] != ']' && input[offset] != '}'
        ) {
            offset++
        }
        if (offset == 0 || (offset > 0 && isWhitespace(input[offset - 1]))) {
            lexicalError(start = offset)
        }
        val actual = input.substring(findTokenStart(offset), offset)
        return (if (actual == "TO") RANGE_TO else RANGE_GOOP) to offset
    }

    private fun findTokenStart(end: Int): Int {
        var i = end - 1
        while (i >= 0 && !isWhitespace(input[i]) && input[i] != '[' && input[i] != '{' &&
            input[i] != ']' && input[i] != '}'
        ) {
            i--
        }
        return i + 1
    }

    private fun lexFunction(): Pair<Int, Int> {
        if (input[offset] == '(') {
            offset++
            curLexState = DEFAULT
            return LPAREN to offset
        }
        val start = offset
        while (offset < input.length && input[offset].isLetter()) offset++
        val word = input.substring(start, offset)
        val kind = when (word) {
            "atleast", "atLeast" -> ATLEAST
            "after" -> AFTER
            "before" -> BEFORE
            "containedBy", "containedby" -> CONTAINED_BY
            "containing" -> CONTAINING
            "extend" -> EXTEND
            "or" -> FN_OR
            "fuzzyterm", "fuzzyTerm" -> FUZZYTERM
            "maxgaps", "maxGaps" -> MAXGAPS
            "maxwidth", "maxWidth" -> MAXWIDTH
            "nonOverlapping", "nonoverlapping" -> NON_OVERLAPPING
            "notContainedBy", "notcontainedby" -> NOT_CONTAINED_BY
            "notContaining", "notcontaining" -> NOT_CONTAINING
            "notWithin", "notwithin" -> NOT_WITHIN
            "ordered" -> ORDERED
            "overlapping" -> OVERLAPPING
            "phrase" -> PHRASE
            "unordered" -> UNORDERED
            "unorderedNoOverlaps", "unorderednooverlaps" -> UNORDERED_NO_OVERLAPS
            "wildcard" -> WILDCARD
            "within" -> WITHIN
            else -> lexicalError(start)
        }
        return kind to offset
    }

    private fun lexDefault(): Pair<Int, Int> {
        val start = offset
        fun take(kind: Int, count: Int = 1): Pair<Int, Int> {
            offset += count
            return kind to offset
        }

        if (input.startsWith("fn:", offset)) {
            offset += 3
            curLexState = Function
            return FN_PREFIX to offset
        }
        if (input.startsWith("<=", offset)) return take(OP_LESSTHANEQ, 2)
        if (input.startsWith(">=", offset)) return take(OP_MORETHANEQ, 2)

        when (input[offset]) {
            '!' -> return take(NOT)
            '+' -> return take(PLUS)
            '-' -> return take(MINUS)
            ')' -> return take(RPAREN)
            ':' -> return take(OP_COLON)
            '=' -> return take(OP_EQUAL)
            '<' -> return take(OP_LESSTHAN)
            '>' -> return take(OP_MORETHAN)
            '^' -> return take(CARAT)
            '~' -> return take(TILDE)
            '@' -> return take(56)
            '(' -> return take(LPAREN)
            '[' -> {
                offset++
                curLexState = Range
                return RANGEIN_START to offset
            }
            '{' -> {
                offset++
                curLexState = Range
                return RANGEEX_START to offset
            }
            '"' -> {
                offset++
                while (offset < input.length) {
                    if (input[offset] == '\\' && offset + 1 < input.length) {
                        offset += 2
                    } else if (input[offset] == '"') {
                        offset++
                        return QUOTED to offset
                    } else {
                        offset++
                    }
                }
                lexicalError(start)
            }
            '/' -> {
                offset++
                while (offset < input.length) {
                    if (input[offset] == '\\' && offset + 1 < input.length && input[offset + 1] == '/') {
                        offset += 2
                    } else if (input[offset] == '/') {
                        offset++
                        return REGEXPTERM to offset
                    } else {
                        offset++
                    }
                }
                lexicalError(start)
            }
        }

        if (!isTermStart(offset)) lexicalError(start)
        while (offset < input.length && isTermChar(offset)) {
            if (input[offset] == '\\') offset += 2 else offset++
        }
        val image = input.substring(start, offset)
        return when {
            image == "AND" || image == "&&" -> AND to offset
            image == "OR" || image == "||" -> OR to offset
            image == "NOT" -> NOT to offset
            NUMBER_REGEX.matches(image) -> NUMBER to offset
            else -> TERM to offset
        }
    }

    private fun isTermStart(index: Int): Boolean {
        if (index >= input.length) return false
        if (input[index] == '\\') return index + 1 < input.length
        return !isWhitespace(input[index]) && input[index] !in TERM_START_EXCLUDED
    }

    private fun isTermChar(index: Int): Boolean {
        if (index >= input.length) return false
        return isTermStart(index) || input[index] == '-' || input[index] == '+'
    }

    private fun token(kind: Int, image: String, start: Int, end: Int): Token {
        val token = Token.newToken(kind, image)
        val begin = lineColumn(start)
        val finish = lineColumn((end - 1).coerceAtLeast(start))
        token.beginLine = begin.first
        token.beginColumn = begin.second
        token.endLine = finish.first
        token.endColumn = finish.second
        return token
    }

    private fun lineColumn(at: Int): Pair<Int, Int> {
        var line = 1
        var column = 1
        for (i in 0 until at.coerceAtMost(input.length)) {
            if (input[i] == '\n') {
                line++
                column = 1
            } else {
                column++
            }
        }
        return line to column
    }

    private fun lexicalError(start: Int): Nothing {
        val position = lineColumn(start)
        val encountered = if (start < input.length) input[start] else 0.toChar()
        throw TokenMgrError(
            start >= input.length,
            curLexState,
            position.first,
            position.second,
            input.substring(0, start.coerceAtMost(input.length)),
            encountered.code,
            TokenMgrError.LEXICAL_ERROR
        )
    }

    companion object {
        private val NUMBER_REGEX = Regex("[0-9]+(?:\\.[0-9]+)?")
        private val TERM_START_EXCLUDED = setOf(
            '+', '-', '!', '(', ')', ':', '^', '@', '<', '>', '=', '[', ']', '"', '{', '}',
            '~', '\\', '/'
        )

        /** Literal token values. */
        val jjstrLiteralImages: Array<String?> = arrayOf(
            "", null, null, null, null, null, null, null, null, null, null, "fn:",
            "+", "-", ")", ":", "=", "<", "<=", ">", ">=", "^", "~", null, null,
            null, null, "[", "{", "(", null, "after", "before", null, "containing",
            "extend", "or", null, null, null, null, null, null, null, "ordered",
            "overlapping", "phrase", "unordered", null, "wildcard", "within", "TO", "]", "}",
            null, null, "@"
        )

        /** Lexer state names. */
        val lexStateNames = arrayOf("Function", "Range", "DEFAULT")

        /** Lex State array. */
        val jjnewLexState = intArrayOf(
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 2, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, 2, 2, -1, -1, -1
        )

        private fun isWhitespace(c: Char): Boolean {
            return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\u3000'
        }
    }
}
