/* Generated By:JavaCC: Do not edit this line. StandardSyntaxParserConstants.java */
package org.gnit.lucenekmp.queryparser.flexible.standard.parser

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface StandardSyntaxParserConstants {
    companion object {
        /** End of File. */
        const val EOF = 0
        /** RegularExpression Id. */
        const val _NUM_CHAR = 1
        /** RegularExpression Id. */
        const val _ESCAPED_CHAR = 2
        /** RegularExpression Id. */
        const val _TERM_START_CHAR = 3
        /** RegularExpression Id. */
        const val _TERM_CHAR = 4
        /** RegularExpression Id. */
        const val _WHITESPACE = 5
        /** RegularExpression Id. */
        const val _QUOTED_CHAR = 6
        /** RegularExpression Id. */
        const val AND = 8
        /** RegularExpression Id. */
        const val OR = 9
        /** RegularExpression Id. */
        const val NOT = 10
        /** RegularExpression Id. */
        const val FN_PREFIX = 11
        /** RegularExpression Id. */
        const val PLUS = 12
        /** RegularExpression Id. */
        const val MINUS = 13
        /** RegularExpression Id. */
        const val RPAREN = 14
        /** RegularExpression Id. */
        const val OP_COLON = 15
        /** RegularExpression Id. */
        const val OP_EQUAL = 16
        /** RegularExpression Id. */
        const val OP_LESSTHAN = 17
        /** RegularExpression Id. */
        const val OP_LESSTHANEQ = 18
        /** RegularExpression Id. */
        const val OP_MORETHAN = 19
        /** RegularExpression Id. */
        const val OP_MORETHANEQ = 20
        /** RegularExpression Id. */
        const val CARAT = 21
        /** RegularExpression Id. */
        const val TILDE = 22
        /** RegularExpression Id. */
        const val QUOTED = 23
        /** RegularExpression Id. */
        const val NUMBER = 24
        /** RegularExpression Id. */
        const val TERM = 25
        /** RegularExpression Id. */
        const val REGEXPTERM = 26
        /** RegularExpression Id. */
        const val RANGEIN_START = 27
        /** RegularExpression Id. */
        const val RANGEEX_START = 28
        /** RegularExpression Id. */
        const val LPAREN = 29
        /** RegularExpression Id. */
        const val ATLEAST = 30
        /** RegularExpression Id. */
        const val AFTER = 31
        /** RegularExpression Id. */
        const val BEFORE = 32
        /** RegularExpression Id. */
        const val CONTAINED_BY = 33
        /** RegularExpression Id. */
        const val CONTAINING = 34
        /** RegularExpression Id. */
        const val EXTEND = 35
        /** RegularExpression Id. */
        const val FN_OR = 36
        /** RegularExpression Id. */
        const val FUZZYTERM = 37
        /** RegularExpression Id. */
        const val MAXGAPS = 38
        /** RegularExpression Id. */
        const val MAXWIDTH = 39
        /** RegularExpression Id. */
        const val NON_OVERLAPPING = 40
        /** RegularExpression Id. */
        const val NOT_CONTAINED_BY = 41
        /** RegularExpression Id. */
        const val NOT_CONTAINING = 42
        /** RegularExpression Id. */
        const val NOT_WITHIN = 43
        /** RegularExpression Id. */
        const val ORDERED = 44
        /** RegularExpression Id. */
        const val OVERLAPPING = 45
        /** RegularExpression Id. */
        const val PHRASE = 46
        /** RegularExpression Id. */
        const val UNORDERED = 47
        /** RegularExpression Id. */
        const val UNORDERED_NO_OVERLAPS = 48
        /** RegularExpression Id. */
        const val WILDCARD = 49
        /** RegularExpression Id. */
        const val WITHIN = 50
        /** RegularExpression Id. */
        const val RANGE_TO = 51
        /** RegularExpression Id. */
        const val RANGEIN_END = 52
        /** RegularExpression Id. */
        const val RANGEEX_END = 53
        /** RegularExpression Id. */
        const val RANGE_QUOTED = 54
        /** RegularExpression Id. */
        const val RANGE_GOOP = 55

        /** Lexical state. */
        const val Function = 0
        /** Lexical state. */
        const val Range = 1
        /** Lexical state. */
        const val DEFAULT = 2

        /** Literal token values. */
        val tokenImage = arrayOf(
            "<EOF>",
            "<_NUM_CHAR>",
            "<_ESCAPED_CHAR>",
            "<_TERM_START_CHAR>",
            "<_TERM_CHAR>",
            "<_WHITESPACE>",
            "<_QUOTED_CHAR>",
            "<token of kind 7>",
            "<AND>",
            "<OR>",
            "<NOT>",
            "\"fn:\"",
            "\"+\"",
            "\"-\"",
            "\")\"",
            "\":\"",
            "\"=\"",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\"^\"",
            "\"~\"",
            "<QUOTED>",
            "<NUMBER>",
            "<TERM>",
            "<REGEXPTERM>",
            "\"[\"",
            "\"{\"",
            "\"(\"",
            "<ATLEAST>",
            "\"after\"",
            "\"before\"",
            "<CONTAINED_BY>",
            "\"containing\"",
            "\"extend\"",
            "\"or\"",
            "<FUZZYTERM>",
            "<MAXGAPS>",
            "<MAXWIDTH>",
            "<NON_OVERLAPPING>",
            "<NOT_CONTAINED_BY>",
            "<NOT_CONTAINING>",
            "<NOT_WITHIN>",
            "\"ordered\"",
            "\"overlapping\"",
            "\"phrase\"",
            "\"unordered\"",
            "<UNORDERED_NO_OVERLAPS>",
            "\"wildcard\"",
            "\"within\"",
            "\"TO\"",
            "\"]\"",
            "\"}\"",
            "<RANGE_QUOTED>",
            "<RANGE_GOOP>",
            "\"@\"", 
        )
    }
}
