/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 7.0 */
/* JavaCCOptions: */
package org.gnit.lucenekmp.queryparser.flexible.standard.parser

/** Token Manager Error. */
class TokenMgrError : Error {
    /*
     * Ordinals for various reasons why an Error of this type can be thrown.
     */

    /**
     * Indicates the reason why the exception is thrown. It will have one of the above 4 values.
     */
    internal var errorCode: Int = 0

    /*
     * Constructors of various flavors follow.
     */

    /** No arg constructor. */
    constructor()

    /** Constructor with message and reason. */
    constructor(message: String, reason: Int) : super(message) {
        errorCode = reason
    }

    /** Full Constructor. */
    constructor(
        EOFSeen: Boolean,
        lexState: Int,
        errorLine: Int,
        errorColumn: Int,
        errorAfter: String?,
        curChar: Int,
        reason: Int,
    ) : this(
        LexicalErr(EOFSeen, lexState, errorLine, errorColumn, errorAfter, curChar),
        reason,
    )

    companion object {
        /**
         * The version identifier for this Serializable class. Increment only if the *serialized*
         * form of the class changes.
         */
        private const val serialVersionUID = 1L

        /** Lexical error occurred. */
        const val LEXICAL_ERROR = 0

        /** An attempt was made to create a second instance of a static token manager. */
        const val STATIC_LEXER_ERROR = 1

        /** Tried to change to an invalid lexical state. */
        const val INVALID_LEXICAL_STATE = 2

        /** Detected (and bailed out of) an infinite loop in the token manager. */
        const val LOOP_DETECTED = 3

        /**
         * Replaces unprintable characters by their escaped (or unicode escaped) equivalents in the
         * given string
         */
        fun addEscapes(str: String): String {
            val retval = StringBuilder()
            var ch: Char
            for (i in str.indices) {
                when (str[i]) {
                    '\b' -> {
                        retval.append("\\b")
                        continue
                    }
                    '\t' -> {
                        retval.append("\\t")
                        continue
                    }
                    '\n' -> {
                        retval.append("\\n")
                        continue
                    }
                    '\u000C' -> {
                        retval.append("\\f")
                        continue
                    }
                    '\r' -> {
                        retval.append("\\r")
                        continue
                    }
                    '"' -> {
                        retval.append("\\\"")
                        continue
                    }
                    '\'' -> {
                        retval.append("\\'")
                        continue
                    }
                    '\\' -> {
                        retval.append("\\\\")
                        continue
                    }
                    else -> {
                        ch = str[i]
                        if (ch < 0x20.toChar() || ch > 0x7e.toChar()) {
                            val s = "0000" + ch.code.toString(16)
                            retval.append("\\u" + s.substring(s.length - 4, s.length))
                        } else {
                            retval.append(ch)
                        }
                        continue
                    }
                }
            }
            return retval.toString()
        }

        /**
         * Returns a detailed message for the Error when it is thrown by the token manager to
         * indicate a lexical error. Parameters : EOFSeen : indicates if EOF caused the lexical
         * error lexState : lexical state in which this error occurred errorLine : line number when
         * the error occurred errorColumn : column number when the error occurred errorAfter :
         * prefix that was seen before this error occurred curchar : the offending character Note:
         * You can customize the lexical error message by modifying this method.
         */
        fun LexicalErr(
            EOFSeen: Boolean,
            lexState: Int,
            errorLine: Int,
            errorColumn: Int,
            errorAfter: String?,
            curChar: Int,
        ): String {
            return "Lexical error at line " + //
                errorLine + ", column " + //
                errorColumn + ".  Encountered: " + //
                (if (EOFSeen) "<EOF>" else ("'" + addEscapes(curChar.toString()) + "' (" + curChar + ")," )) + //
                (if (errorAfter == null || errorAfter.length == 0) "" else " after prefix \"" + addEscapes(errorAfter) + "\"") + //
                (if (lexState == 0) "" else " (in lexical state $lexState)")
        }
    }
}
/* (filtered)*/
