package org.gnit.lucenekmp.search.similarities

import org.gnit.lucenekmp.search.Explanation
import kotlin.math.ln

/**
 * Language model based on the Jelinek-Mercer smoothing method. From Chengxiang Zhai and John
 * Lafferty. 2001. A study of smoothing methods for language models applied to Ad Hoc information
 * retrieval. In Proceedings of the 24th annual international ACM SIGIR conference on Research and
 * development in information retrieval (SIGIR '01). ACM, New York, NY, USA, 334-342.
 *
 * The model has a single parameter, λ. According to said paper, the optimal value depends
 * on both the collection and the query. The optimal value is around `0.1` for title queries
 * and `0.7` for long queries.
 *
 * Values should be between 0 (exclusive) and 1 (inclusive). Values near zero act score more like
 * a conjunction (coordinate level matching), whereas values near 1 behave the opposite (more like
 * pure disjunction).
 *
 * @lucene.experimental
 */
class LMJelinekMercerSimilarity : LMSimilarity {
    /** The λ parameter.  */
    val lambda: Float

    /** Instantiates with the specified collectionModel and λ parameter.  */
    constructor(collectionModel: CollectionModel, lambda: Float) : this(collectionModel, true, lambda)

    /** Instantiates with the specified collectionModel and parameters.  */
    constructor(collectionModel: CollectionModel, discountOverlaps: Boolean, lambda: Float) : super(
        collectionModel,
        discountOverlaps
    ) {
        require(!(lambda.isNaN() || lambda <= 0 || lambda > 1)) { "lambda must be in the range (0 .. 1]" }
        this.lambda = lambda
    }

    /** Instantiates with the specified λ parameter.  */
    constructor(lambda: Float) {
        require(!(lambda.isNaN() || lambda <= 0 || lambda > 1)) { "lambda must be in the range (0 .. 1]" }
        this.lambda = lambda
    }

    override fun score(stats: BasicStats, freq: Double, docLen: Double): Double {
        return stats.boost * ln(1 + ((1 - lambda) * freq / docLen) / (lambda * (stats as LMStats).collectionProbability))
    }

    override fun explain(subs: MutableList<Explanation>, stats: BasicStats, freq: Double, docLen: Double) {
        if (stats.boost != 1.0) {
            subs.add(Explanation.match(stats.boost.toFloat(), "boost"))
        }
        subs.add(Explanation.match(lambda, "lambda"))
        val p = (stats as LMStats).collectionProbability
        val explP =
            Explanation.match(
                p.toFloat(),
                "P, probability that the current term is generated by the collection"
            )
        subs.add(explP)
        val explFreq =
            Explanation.match(
                freq.toFloat(),
                "freq, number of occurrences of term in the document"
            )
        subs.add(explFreq)
        subs.add(Explanation.match(docLen.toFloat(), "dl, length of field"))
        super.explain(subs, stats, freq, docLen)
    }

    override fun explain(stats: BasicStats, freq: Explanation, docLen: Double): Explanation {
        val subs: MutableList<Explanation> = mutableListOf()
        explain(subs, stats, freq.value.toDouble(), docLen)

        return Explanation.match(
            score(stats, freq.value.toDouble(), docLen).toFloat(),
            "score(${this::class.simpleName}, freq=${freq.value}), computed as boost * log(1 + ((1 - lambda) * freq / dl) /(lambda * P)) from:",
            subs
        )
    }

    override val name: String
        get() = "Jelinek-Mercer(${this.lambda})"
}
