package org.gnit.lucenekmp.search.similarities

import org.gnit.lucenekmp.search.CollectionStatistics
import org.gnit.lucenekmp.search.Explanation
import org.gnit.lucenekmp.search.TermStatistics
import kotlin.jvm.JvmOverloads


/**
 * Abstract superclass for language modeling Similarities. The following inner types are introduced:
 *
 *
 *  * [LMStats], which defines a new statistic, the probability that the collection
 * language model generates the current term;
 *  * [CollectionModel], which is a strategy interface for object that compute the
 * collection language model `p(w|C)`;
 *  * [DefaultCollectionModel], an implementation of the former, that computes the term
 * probability as the number of occurrences of the term in the collection, divided by the
 * total number of tokens.
 *
 *
 * @lucene.experimental
 */
abstract class LMSimilarity
/** Creates a new instance with the default collection language model.  */ @JvmOverloads constructor(
    /** The collection model.  */
    protected val collectionModel: CollectionModel = DefaultCollectionModel(),
    discountOverlaps: Boolean = true
) : SimilarityBase(discountOverlaps) {
    /** Creates a new instance with the specified collection language model and discountOverlaps.  */
    /** Creates a new instance with the specified collection language model.  */

    override fun newStats(field: String, boost: Double): BasicStats {
        return LMStats(field, boost)
    }

    /**
     * Computes the collection probability of the current term in addition to the usual statistics.
     */
    override fun fillBasicStats(
        stats: BasicStats,
        collectionStats: CollectionStatistics,
        termStats: TermStatistics
    ) {
        super.fillBasicStats(stats, collectionStats, termStats)
        val lmStats = stats as LMStats
        lmStats.collectionProbability = collectionModel.computeProbability(stats)
    }

    override fun explain(
        subExpls: MutableList<Explanation>,
        stats: BasicStats,
        freq: Double,
        docLen: Double
    ) {
        subExpls.add(
            Explanation.match(
                collectionModel.computeProbability(stats).toFloat(), "collection probability"
            )
        )
    }

    /**
     * Returns the name of the LM method. The values of the parameters should be included as well.
     *
     *
     * Used in [.toString].
     */
    abstract val name: String

    /**
     * Returns the name of the LM method. If a custom collection model strategy is used, its name is
     * included as well.
     *
     * @see .name
     * @see CollectionModel.name
     * @see DefaultCollectionModel
     */
    override fun toString(): String {
        val coll = collectionModel.name
        return if (coll != null) {
            "LM ${this.name} - $coll"
        } else {
            "LM ${this.name}"
        }
    }

    /** Stores the collection distribution of the current term.  */
    class LMStats
    /** Creates LMStats for the provided field and query-time boost  */
        (field: String, boost: Double) : BasicStats(field, boost) {
        /** Returns the probability that the current term is generated by the collection.  */
        /** Sets the probability that the current term is generated by the collection.  */
        /** The probability that the current term is generated by the collection.  */
        var collectionProbability: Double = 0.0
    }

    /** A strategy for computing the collection language model.  */
    interface CollectionModel {
        /**
         * Computes the probability `p(w|C)` according to the language model strategy for the
         * current term.
         */
        fun computeProbability(stats: BasicStats): Double

        /** The name of the collection model strategy.  */
        val name: String?
    }

    /**
     * Models `p(w|C)` as the number of occurrences of the term in the collection, divided by
     * the total number of tokens `+ 1`.
     */
    class DefaultCollectionModel
    /** Sole constructor: parameter-free  */
        : CollectionModel {
        override fun computeProbability(stats: BasicStats): Double {
            return (stats.totalTermFreq + 1.0) / (stats.numberOfFieldTokens + 1.0)
        }

        override val name: String? = null
    }
}
